### ISSUE TITLE
set-alias in zsh translates in load to function but unload as an unalias

### ISSUE THREAD

**Issue by matthew-page** [cea-hpc/modules#127]
On a set-alias in a modulefile the modulecmd zsh load will make a function such as : 
    myfunc() {  eval `RunMyFunc -set ${1+"$@"}`;}

but on an unload it sends out unalias insted of typeset -f : 
   unalias myfunc

**Comment by matthew-page** [comment]
(note this was tested on 3.2.10 , C version

**Comment by xdelaruelle** [comment]
Behavior will change in 4.0, where a set-alias will always produce a shell alias, so unalias at unload time will be correct.

**Comment by matthew-page** [comment]
yes but it does the right thing for bash, its just zsh and sh that is messed up...is there a patch on 3.2.10 available?  It was hard enough to migrate from 3.1.6 to 3.2.10 because of the structural changes in the build (new dir "Modules" messed up my enterprise customers quite a bit as well as the missing init/perl having been replaced by init/perl.pm as they had coded into various systems the presumption of the prior structure).

**Comment by xdelaruelle** [comment]
No fix is excepted for the compatibility v3.2 version. For v4.0 a lot of work has been done to make the migration from v3.2 smooth enough (it will install both v4 and v3.2 by default then you can easily switch from one flavor to the other to familiarize with the new main version). I understand such kind of migration is not an easy step at sites, but there is much gain if you look at the bugs it fixes and the new features it provides.

In the issue you describe, I wonder if you really need a shell function for that, maybe a regular shell alias can do the job:

```tcl
set-alias myfunc "eval RunMyFunc -set "
```

Maybe the `eval` can also be suppressed. Then you can call the alias with `myfunc arg1 arg2 ...`
