### ISSUE TITLE
test modules.70-maint/020-update.exp fails on RHEL 6.9 and RHEL 7.4

### ISSUE THREAD

**Issue by ebagrenrut** [cea-hpc/modules#131]
Test modules.70-maint/020-update.exp now fails on RHEL 6.9 and RHEL 7.4:

> Running ./testsuite/modules.70-maint/020-update.exp ...
>   ...  version_test(BEGINENV=1)
> version_test: 0
>   ...  version_test(BEGINENV=99)
> version_test: 1
>   ...  version_test(BEGINENV=1)
> version_test: 0
>   ...  version_test(BEGINENV=99)
>version_test: 1
>   ...  Testing 'modulecmd csh update'
> starting ./modulecmd csh update
> OUT: ''
> ERR: 'ModuleCmd_Update.c(224):ERROR:50: Cannot open file './testsuite/.modulesbeginenv.yyy' for   'reading''
> EXIT: '1'
>   ...  Testing 'modulecmd csh update'
> starting ./modulecmd csh update
> OUT: 'setenv MODULEPATH ./testsuite/modulefiles ;setenv MODULEPATH_modshare /usr/share/modulefiles:1:/etc/modulefiles:1 ;setenv testsuite yes ;'
> ERR: ''
> EXIT: '0'
> FAIL: update (csh)
> OUT: 'setenv MODULEPATH ./testsuite/modulefiles ;setenv MODULEPATH_modshare /usr/share/modulefiles:1:/etc/modulefiles:1 ;setenv testsuite yes ;'
> EXP (re): 'setenv MODULEPATH ./testsuite/modulefiles ;setenv testsuite yes ;'
>   ...  version_test(BEGINENV=1)
> version_test: 0
>   ...  version_test(BEGINENV=99)
> version_test: 1

Interestingly, this did not fail yesterday when I ran it while I was trying to build 0.1 beta. 

To reproduce:
On RHEL 6 or 7:

1. ./configure
1. make
1. make test

**Comment by xdelaruelle** [comment]
When you launch the testsuite, do you have "module" already installed an enabled in your session ?

**Comment by ebagrenrut** [comment]
I do, yes. 1.923.

**Comment by ebagrenrut** [comment]
I can confirm that when running tests on a system without Modules installed, the same test does not fail. However, having a system without Modules installed just to build the Modules RPM seems rather inconvenient.

**Comment by xdelaruelle** [comment]
Thanks a lot for these information. This is not a sane situation you are right :), I should be able to quickly fix it.

**Comment by xdelaruelle** [comment]
Above commit should fix this testsuite issue.

Thanks again for the report.
Xavier

**Comment by ebagrenrut** [comment]
Conrfirmed. Tests pass now. Thanks!
