### ISSUE TITLE
module add /full/path/to/module causes lstats to be done on your current pwd

### ISSUE THREAD

**Issue by wenzler** [cea-hpc/modules#132]
Hi,
I tested this on 1.923 and 4.0beta
After

> module add /foo/bar/modulefile

every module list command walks through the current working directory ($PWD) 
and looks at _all_ files in subdirectories alike:

> getcwd("/home/username", 4097)           = 14
> lstat("/home", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
> lstat("/home/username", {st_mode=S_IFDIR|0755, st_size=20480, ...}) = 0
> lstat("/home/username/Documents", {st_mode=S_IFDIR|0755, st_size=57344, ...}) = 0
> open("./Documents/somedocument.txt", O_RDONLY) = 12
> ....

This causes 

> module list

 to take endlessly long.

I tried to add support for ./modulefile loads and was confused after finding out this behavior is
in the vanilla release regardless of my patch, but maybe you can tell if this is a valid solution and you want to adopt it (after fixing the walk problem ;)
```
--- Download/modulecmd.tcl.in~	2017-09-28 15:51:39.000000000 +0200
+++ Download/modulecmd.tcl.in	2017-09-28 15:53:01.997080148 +0200
@@ -2122,7 +2122,8 @@
    reportDebug "getPathToModule: finding '$mod' in '$indir' (excdir='')"
 
    # Check for $mod specified as a full pathname
-   if {[string match {/*} $mod]} {
+   if { [regexp {^(\.)?(/.*)} $mod -> relative_path mod_stripped] } {
+      if { $relative_path == "." } { set mod "[pwd]$mod_stripped" }
       # note that a raw filename as an argument returns the full
       # path as the module name
       lassign [checkValidModule $mod] check_valid check_msg
```

Thanks and BR

**Comment by xdelaruelle** [comment]
@wenzler Walk problem fixed, thanks for this report :). I have some guidelines for you regarding the addition you want to make. I have just introduced a `isModuleFullPath` procedure, this is where you should look to make modulefile specified with a starting `../` or `./` detected as full path. I encourage you to use `string match` for this detection. Then in `getPathToModule`, if full path test is true, call to `getAbsolutePath` procedure to transform relative path into clean and absolute pathname.

Then some non-regression tests would be welcomed to cover the new code. I think 2 load tests (one with `../`, another for `./`) and 2 unload tests (one with `../`, another for `./`) will help to guaranty correct behavior over time. Files to modify are `testsuite/modules.50-cmds/180-unload.exp` and `testsuite/modules.50-cmds/190-load.exp`.

Best regards,
Xavier
