### ISSUE TITLE
4.0.0, configure --prefix <> ; make all ; make install does not obey prefix

### ISSUE THREAD

**Issue by zerothi** [cea-hpc/modules#135]
When trying to compile 4.0.0, I cannot get the prefix to work:
```
./configure --prefix /opt/modules
make all
make install
```
issues this warning:
```
mkdir -p /usr/local/Modules/libexec
mkdir: cannot create directory '/usr/local/Modules': Permission denied
Makefile:152: recipe for target 'install' failed
make: *** [install] Error 1
```
which I presume is the default dir. 

Note, I haven't tried with `DESTDIR` env-var, but I presume you want `--prefix` to work?

**Comment by xdelaruelle** [comment]
Could you try with `--prefix=/opt/modules`. I assume the `=` is currently mandatory.

**Comment by zerothi** [comment]
that worked, thanks!
