### ISSUE TITLE
4.0 fails to build on RHEL 6.9

### ISSUE THREAD

**Issue by ebagrenrut** [cea-hpc/modules#136]
It seems that the introduction if sphinx has caused 4.0 (and master) to fail to build on RHEL 6.9. It does build successfully on RHEL 7.4.

make -C doc man txt
make[1]: Entering directory `/home/gabe/src/modules/doc'
/usr/bin/sphinx-build -q -t pathsubs -b man "source" "build"

Sphinx error:
Builder name man not registered
make[1]: *** [build/module.1.in] Error 1
make[1]: Leaving directory `/home/gabe/src/modules/doc'
make: *** [pkgdoc] Error 2

According to the man page for sphinx-build on RHEL 6.9,there is no _man_ builder available.

**Comment by xdelaruelle** [comment]
You need a version of sphinx >= 1.0. So on EL6, package `python-sphinx10` should be installed

**Comment by ebagrenrut** [comment]
Thanks, it now builds, though the sphinx does produce errors about the 'caption' directive, which doesn't seem to exist in sphinx 1.0.8. I think it wasn't introduced until sphinx 1.3.

/home/gabe/src/modules/doc/source/index.rst:66: ERROR: Error in "toctree" directive:
unknown option: "caption".

.. toctree::
   :hidden:
   :maxdepth: 2
   :caption: Installation

   INSTALL
   MIGRATING

I am able to build the RPMs, so this error does not cause a failure.

Thanks!

**Comment by degremont** [comment]
Hum... closed?

Should not the specfile be updated to add this dependency?

```
%if 0%{?rhel} && 0%{?rhel} <= 6
BuildRequires:  python-sphinx10
%fi
```

**Comment by xdelaruelle** [comment]
@degremont There is no impact when installing from tarball as docs are pre-built in there. RPM build takes tarball as source, so the issue is not present when building RPM. Issue only occurs when building from git repository.

**Comment by degremont** [comment]
Ok, I got it... thanks
