### ISSUE TITLE
module source and setenv behavior

### ISSUE THREAD

**Issue by amal-khailtash** [cea-hpc/modules#137]
Should "module source" treat "setenv" as "unsetenv" when unloading a parent module?

Module a:
```
#%Module1.0
#a
module source path/to/modulefiles/.b
```

Module .b (only sourced)
```
#%Module1.0
#.b
setenv X x
```

Is this the expected output?
```
$ module load a
$ echo $X
x
$ module unload a
$ echo $X
x
```

I assumed X should be unset.

**Comment by ebagrenrut** [comment]
You module .b will be sourced both during load and unload. Hence X is
always set.

Gabe

**Comment by xdelaruelle** [comment]
It may be interesting here to add an `unsource` sub-command that source file in an unload mode. When modulefile is interpreted in an unload mode, `source` commands should be converted into `unsource` commands.

**Comment by amal-khailtash** [comment]
Yes, basically I wanted to have the same behavior as setenv/unsetenv with source command.  It seems that [module-info mode load] is always True for source command, so I could not do unsetenv by using [module-info mode unload].

**Comment by xdelaruelle** [comment]
Here I will focus on the ``unload`` mode for ``source`` sub-command. An ``unsource`` sub-command requires a bit more thoughts.
