### ISSUE TITLE
PAGER (v4.1.0) is killing us

### ISSUE THREAD

**Issue by MaiMunCho** [cea-hpc/modules#146]
Just tried 4.1.0 and immediately deleted it! 
The introduced PAGER is at least annoying and breaks almost everything at our site!
So please:
- either remove it or
- allow for NOT using it @configure&build time

Kind regards
MC

**Comment by xdelaruelle** [comment]
Pager can be disabled at configure time with the ``--without-pager`` argument.

Could you precise:
* on what OS (name and version) you tested it.
* what is the debugging output of a simple command ``module -D help``
* it can also be useful if you can paste here some broken output

Thanks,
Xavier

**Comment by MaiMunCho** [comment]
Dear Xavier,

first of all many thanks for your continuous and excellent work! 

We are using modules since more than 10 years (starting with the C version and nowadays using the tcl version) on daily basis. It is basically one setup (mainly for EDA tools) on multiple operating systems: Solaris (sparc, x86 10, 11), Linux (CentOS 6), FreeBSD 11.

I will prepare a (or some) sample scenario(s), where I think, the PAGER is a stopper.

Kind regards,
MC

**Comment by MaiMunCho** [comment]
Dear Xavier,

We are using modules both interactively and (mainly) in scripts. The PAGER blocker was with the later.

After configuring modules with '--without-pager', those issues are gone.  
Sorry, didn't discover it straight away by myself. The documentation has to mention it along with the possibilities to suppress/change this functionality at run time (command line options, environment variables). But my suggestion is to make it ('--with-pager') non default! 

The rest is of topic, but I will use this thread to mention it.

As already said, we are using the same setup for different operating systems and for different shells:
sh (for scripts), ksh (interactive and for scripts), bash and tcsh (for interactive use):

- hard coded paths are an issue:
  = there is  no '/bin/basename'  (and '/bin/false', which was fortunately removed in this version) on FreeBSD
  =  it is unlikely, that '/usr/local/bin/tclsh' exists on different operating systems. I'm changing it at the moment to 'tclsh', ensuring, that it is somewhere in the PATH. A more convenient, portable and configurable approach should be needed here ...

- there are no 'local' variables in the pure bourne shell ('sh'), so you have to consider this for 'locf', here my temporary (dirty) solution:

`
*** modulecmd.tcl.in	Wed Jan 17 08:52:08 2018
--- modulecmd.tcl.in.orig	Tue Jan 16 15:03:48 2018
***************
*** 3555,3566 ****
        }
        {sh} {
           # adapt shell function to define local variable, as 'typeset' is
!          # not known by dash and 'local' is not known by ksh and both are not known by sh
           if {$g_shell eq "sh"} {
-             set locf ""
-          } elseif {$g_shell eq "dash"} {
              set locf "local"
-          }
           } else {
              set locf "typeset"
           }
--- 3555,3563 ----
        }
        {sh} {
           # adapt shell function to define local variable, as 'typeset' is
!          # not known by dash and 'local' is not known by ksh
           if {$g_shell eq "sh"} {
              set locf "local"
           } else {
              set locf "typeset"
           }
***************
*** 3591,3597 ****
           *) $locf _mlshdbg='' ;;
        esac;
     fi;
!    $locf _mlre=''; $locf _mlv=''; $locf _mlrv='';
     if \[ -n \"\${IFS+x}\" \]; then
        $locf _mlIFS=\$IFS;
     fi;
--- 3588,3594 ----
           *) $locf _mlshdbg='' ;;
        esac;
     fi;
!    $locf _mlre=''; $locf _mlv; $locf _mlrv;
     if \[ -n \"\${IFS+x}\" \]; then
        $locf _mlIFS=\$IFS;
     fi;
`

**Comment by MaiMunCho** [comment]
Sorry, the 'diff' output was completely malformed above ;(

**Comment by xdelaruelle** [comment]
Functionality can also be disabled at runtime with ``--no-pager`` command-line switches or ``MODULES_PAGER`` environment variable. More details can be found in the ``module(1)`` manpage [1], |2].

Thanks for these additional informations. ``modulecmd.tcl`` detects if it is run interactively or not. Paginate output is enabled only in interactive mode. So I suspect that in your setup this detection code is not working properly. Could you precise on what of your systems you encounter the issue and what is the debugging output you get when running the ``module -D help`` command in a script ? Do you also get the issue on CentOS 6 ?

Regards,
Xavier

[1] https://modules.readthedocs.io/en/latest/module.html#command-line-switches
[2] https://modules.readthedocs.io/en/latest/module.html#environment

**Comment by dberzano** [comment]
@xdelaruelle it is understood that the pager can be disabled. However, you are effectively breaking the user space by changing the default behaviour. You should optionally _enable_ it and give an option/envvar to do so, not the other way around, IMHO.

**Comment by xdelaruelle** [comment]
@dberzano Are you encountering issues with this feature ? I still need a case to work on here.

This feature is enabled by default to mimic same default behaviour you can find on ``git``. For me this feature is mature enough to be enabled by default. But I understand it can be seen as a big change for someone using previous versions of modules.

**Comment by dberzano** [comment]
Hello @xdelaruelle, thanks for your reply. First off, thanks for having taken over this development! Let me provide you with some context first.

We use environment-modules in our experiment's build tool. For the record: I manage releases for the ALICE experiment @ LHC, our build tool is [aliBuild](https://github.com/alisw/alibuild), and we have, as per our analytics, almost 300 active unique users per month.

In general, all recent changes broke our environment for macOS users (analytics show that 50% of our active users have macOS), since Homebrew picks the latest & greatest version of environment-modules.

At the moment, we are fine with:

```
export MODULES_USE_COMPAT_VERSION=1
```

In general, I find pagers enabled by default annoying (it's the case with `systemctl` already), but this is just my personal opinion. Most of us use graphic terminal emulators now and scroll using a trackpad, not via `less`.

On a general perspective, what I think is that user space should never be broken, and this change breaks the user space - we know that [Linus Torvalds feels pretty passionate about that](https://lkml.org/lkml/2012/12/23/75), I am way more moderate than him :-)

I also understand, however, that this is a new _major_ version, so userspace changes are somehow tolerated (well: 4.x is, but this change's been introduced between 4.0.0 and 4.1.0).

Say, given the number of people currently using environment-modules around the world, I would be very careful about changing a default behaviour :-)

**Comment by xdelaruelle** [comment]
@dberzano Thanks for your detailed feedback. I may have been too fast to set it a default, should not have been a default before 5.0 maybe. Anyway, if you spot bugs at your site on this specific feature or any other do not hesitate to report them.

**Comment by xdelaruelle** [comment]
Fixes are ongoing. I have setup some Solaris and FreeBSD testbed and I now understand the encountered issue. 2 fixes will be made here:
* only start the pager (if enabled) if some text need to be printed
* ignore ``PAGER`` variable, only look for ``MODULES_PAGER`` to avoid side-effect coming from a generic pager definition
