### ISSUE TITLE
Hard coded paths and local variables

### ISSUE THREAD

**Issue by MaiMunCho** [cea-hpc/modules#147]
We are using the same setup for different operating systems (Solaris, Linux, FreeBSD) and for different shells: sh (for scripts), ksh (interactive and for scripts), bash and tcsh (for interactive use):

-  hard coded paths are an issue:
    -  there is no '/bin/basename' (and '/bin/false', which was fortunately removed in this version) on FreeBSD
     -  it is unlikely, that '/usr/local/bin/tclsh' exists on different operating systems. I'm changing it at the moment to 'tclsh', ensuring, that it is somewhere in the PATH. A more convenient, portable and configurable approach should be needed here ...

-   there are no 'local' variables in the pure bourne shell ('sh'), so you have to consider this for 'locf', here my temporary (dirty) solution: 
[modulecmd.tcl.in.diff.txt](https://github.com/cea-hpc/modules/files/1638648/modulecmd.tcl.in.diff.txt)

**Comment by xdelaruelle** [comment]
Thanks for your report. Modules v4 may currently be too Linux-centric. So I will look what can be done to integrate other systems to the continuous integration test suite.

- I assume the ``/bin/basename`` you found was in the ``profile.sh`` script
- Path to ``tclsh`` is defined at ``./configure`` time. You can control it with the ``--with-tclsh`` option
- Could you precise on what pure bourne shell ('sh') you get the ``local`` issue ?

Regards,
Xavier

**Comment by xdelaruelle** [comment]
Just setup a Solaris testbed. ``sh`` on this system is a ``ksh93``, so it reacts to ``typeset`` not to ``local``.
