### ISSUE TITLE
Order of modulerc directory listings

### ISSUE THREAD

**Issue by IndyMark** [cea-hpc/modules#148]
My modulerc file has (2) paths listed in it:
module use /share/apps/CentOS-7/modules/r-4.1.0/modulefiles
module use /share/apps/CentOS_6.4/modules/r-3_2_10/modulefiles

where the 1st path is our "new" modulefiles directory and the 2nd one is our "old" modulefiles directory.  I want the modules in the first/new directory to be listed first and the modules in the second/old directory to be listed second.  I have tried various combinations, but they always seem to list backwards of what I'm shooting for.  Is there any way to force the order?

**Comment by xdelaruelle** [comment]
``module use`` prepends the new path in the modulepath list by default. So in your example the second path gets the priority. You can make it append the new path rather prepending it with ``--append`` argument.

**Comment by IndyMark** [comment]
Thank you!  I can confirm it works like I want now.  I know I played around with --append and thought I had already tried that, but apparently not.
