### ISSUE TITLE
sourcing init/bash fails if `-u` set

### ISSUE THREAD

**Issue by nolta** [cea-hpc/modules#151]
With modules 4.1, the following script:

```bash
#!/bin/bash
set -eu
. /path/to/modules/init/profile.sh
```
fails because `MODULES_SILENT_SHELL_DEBUG` and `MODULES_RUN_QUARANTINE` aren't defined.

Fix is probably as simple as replacing `$X` with `${X-}`.

**Comment by xdelaruelle** [comment]
Quite easy to fix as you say. Will add some non-regression tests to check that on a regular basis. Thanks for the report.

**Comment by nolta** [comment]
Thanks!
