### ISSUE TITLE
Annoying messages about DYLD_LIBRARY_PATH_modshare on Mac 

### ISSUE THREAD

**Issue by aphecetche** [cea-hpc/modules#153]
Hi,

A (very) annoying change in latest release(s?) is, on Mac, the definition of the DYLD_LIBRARY_PATH_modshare variable, which results in tons (well, if you use tons of module files using the DYLD_LIBRARY_PATH variable, that is ;-) ) of warning messages like :  
 
❯ module list
dyld: warning, unknown environment variable: DYLD_LIBRARY_PATH_modshare
dyld: warning, unknown environment variable: DYLD_LIBRARY_PATH_modshare
Currently Loaded Modulefiles:
 1) alice   2) BASE/1.0   3) protobuf/v3.0.2-1

I guess the solution would be, for this variable in particular (the DYLD* variables are kind of reserved by dyld program as far as I can guess), to prepend the tag instead of postfixing it, e.g. modshare_DYLD_LIBRARY_PATH.

Does that take sense ?

Regards,

**Comment by xdelaruelle** [comment]
Hi,

It makes sense to use a MODULES prefix. Will do it for the dyld-specific variables for the moment. All *_modshare variable should move to a MODULES_ prefix in a next major release.

Regards,
Xavier

**Comment by aphecetche** [comment]
Great. Thanks.
