### ISSUE TITLE
make install does not honour prefix in init files

### ISSUE THREAD

**Issue by EricDeveaud** [cea-hpc/modules#156]
Hello, 

while testing module pulled from the master branch and installed in a non standard location this way:

``` sh 
PREFIX=/tmp/module
./configure --disable-compat-version --prefix=$PREFIX
make
make install
```

when trying to init this on e I have the following error message

``` sh
 source  $PREFIX/init/sh
couldn't read file "/usr/local/Modules/libexec/modulecmd.tcl": no such file or directory
```

after 
```
sed -i -e "s|/usr/local/Module|$PREFIX|g" $PREFIX/init/sh
```

evrything went OK

regards

Eric

**Comment by xdelaruelle** [comment]
Hello Eric,

Thanks for your report. It will not be too hard to fix this one.

Regards,
Xavier

**Comment by xdelaruelle** [comment]
@EricDeveaud I cannot reproduce the issue you encounter. For me when typing the commands you mention everything goes well:

```
$ PREFIX=/tmp/module
$ ./configure --disable-compat-version --prefix=$PREFIX
$ make
$ make install
$ source  $PREFIX/init/sh
$ module -D -V
DEBUG CALLING /tmp/module/libexec/modulecmd.tcl sh -D -V
DEBUG initPager: start pager (asked_pager=-, cmd='/usr/bin/less', opts='-eFKRX')
Modules Release 4.1.1 (2018-02-17)
```

Could you report here the full output you get when typing these commands. It will help to understand what is going on.

Regards,
Xavier

**Comment by xdelaruelle** [comment]
@EricDeveaud Could you provide additional elements to help to reproduce the installation issue you encounter. From all tests done, ``--prefix`` configure option is honoured by make install.

**Comment by xdelaruelle** [comment]
Issue cannot be reproduced. From all tests made ``--prefix`` configure option works as expected.
