### ISSUE TITLE
puts doesn't work when writing to files

### ISSUE THREAD

**Issue by al3ph** [cea-hpc/modules#157]
set fh [open [file join $::env(HOME) ".showrc"] a+]
	puts $fh "test"
	close $fh

Fails with Module ERROR: can not find channel named "file6"

Works fine in normal tcl, I suspect the  Module override of puts doesn't work correctly in this case.

cheers

**Comment by xdelaruelle** [comment]
Your assumption is right, overridden `puts` does not work properly with IO channels different other than `stderr` and `stdout`. Fix is on the way.

Cheers,
Xavier

**Comment by al3ph** [comment]
Cool, in a similar vein, opening a file with truncate seems to mess up as well, in my code it fills the file with 0's instead of resetting the size.

I've worked around it by deleting the file instead, but in general it looks like there's an issue with any io that doesn't involve stderr/stdout, i'm guessing you've overridden some low level functions, and that isn't behaving correctly.

**Comment by xdelaruelle** [comment]
Could you paste here some code example for this truncate scenario you mention ? Thanks

**Comment by al3ph** [comment]
Hmm that's odd I can't reproduce it, I wonder if it's a side effect of getting around the puts problem.

Basically I was appending to a file, and when it hit a certain size I read it removed duplicates and then wrote out the reduced data over the top of the file using WRONLY CREAT TRUNC, what happened was the original content was just replaced with 0's and the new data appended on the end.

I'll create a new ticket if I workout how I trigger this oddity.

cheers
