### ISSUE TITLE
Latest release modules 4.1.1 doesn't build on Cygwin

### ISSUE THREAD

**Issue by accesio** [cea-hpc/modules#158]
Hi, 

I get the following error when trying to build on Cygwin 
```bash
~/modules-4.1.1
--------------------------------------------------
creating ./Makefile.inc
creating ./site.exp
GENWINBOX-00 modules-4.1.1 % make
make -C init all
make[1]: Entering directory '/home/JDamon/modules-4.1.1/init'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/JDamon/modules-4.1.1/init'
make -C compat modulecmd
make[1]: Entering directory '/home/JDamon/modules-4.1.1/compat'
make[1]: *** No rule to make target 'modulecmd'.  Stop.
make[1]: Leaving directory '/home/JDamon/modules-4.1.1/compat'
make: *** [Makefile:171: compat/modulecmd] Error 2
```

I've installed tcl and tcl-dev to make this work . All I'm trying to do is install the tcl version of modulecmd

[modules-4.1.1.log](https://github.com/cea-hpc/modules/files/1830553/modules-4.1.1.log)

**Comment by xdelaruelle** [comment]
Hi,

Thanks for your report. I have made some fixes few days ago (630bab5ae1fe8da72e4fc46bfe80c63bf2fd5753, 721fdd033cf453661b5ae3260ca0944609c41f69) to make Modules installable and testable on Cygwin platform. These fixes will be part of the next bugfix release (v4.1.2) which will be out in a few days.

Regards,
Xavier
