### ISSUE TITLE
No support for ksh88

### ISSUE THREAD

**Issue by alef** [cea-hpc/modules#159]
Different issues assuming `/bin/ksh` is _ksh93_ instead of _ksh88_.
Having `ENV=<path>/init/profile.sh` triggers errors in system level scripts.
Partial workaround was to move `init/ksh` away so to force `init/sh`, but this trigger other errors.
I'll see if can provide some patches/PR.

**Comment by xdelaruelle** [comment]
Patches/PR will be greatly appreciated. If you want a fix in next release, be aware that v4.1.2 will be out in the very next days. On what OS do you encounter the issue ?

**Comment by xdelaruelle** [comment]
Found a ksh88 on Solaris (`/usr/sunos/bin/ksh`) and on Linux (`pdksh`). I only spot one issue with an incompatible FPATH assignment:

```
$ /usr/sunos/bin/ksh
$ . /usr/local/Modules/init/ksh
/usr/sunos/bin/ksh: FPATH+=/usr/local/Modules/init/ksh-functions:  not found
```

**Comment by xdelaruelle** [comment]
Also `.` should be used instead of `source` to include an external script (used by `switchml` when compatibility version is installed)
