### ISSUE TITLE
ModulesHelp{} doesn't like $env() since 4.x

### ISSUE THREAD

**Issue by cmarqu** [cea-hpc/modules#160]
With a module like
```
#%Module
proc ModulesHelp { } {
    puts stderr "My help text"
}

setenv FOO foobar42
setenv BAR $env(FOO)
```
I can call ``module help foobar42`` followed by ``module load foobar42`` with the expected behavior with version 3.2.10.
However, with versions 4.1.0 and 4.1.1, I get the following output _if I call help before load_:
```
-------------------------------------------------------------------
Module Specific Help for /home/colin/tools/modulefiles/foobar42:

Module ERROR: can't read "env(FOO)": no such variable
  In '/home/colin/tools/modulefiles/foobar42'
  Please contact <root@localhost>
-------------------------------------------------------------------
```
Loading or ``show``ing the module works fine however, and after it has been loaded, also help works fine.
I know I could work around that problem by using intermediate Tcl variables, but that would be quite a burden.

**Comment by xdelaruelle** [comment]
``setenv`` does nothing in ``help``, ``test`` and ``whatis`` mode currently. It should not be a problem to restore the behavior found on 3.2.10.
