### ISSUE TITLE
when i source /usr/share/module/init/bash,it showed Unable to execute binary file

### ISSUE THREAD

**Issue by jsboer** [cea-hpc/modules#163]
like the title，what should i do.

**Comment by xdelaruelle** [comment]
Could you please report the version of Modules you are using.

Also could you execute the following sequence and copy/paste here the result obtained:

```
echo $SHELL
set -x
source /usr/share/module/init/bash
```

**Comment by xdelaruelle** [comment]
@jsboer Need more information to help you on this. What is the Modules version you are using. Running ``source`` command in debugging mode will help to understand what is failing:

```
echo $SHELL
set -x
source /usr/share/module/init/bash
```

I am pretty sure the issue you get comes from an installation not made for the system you are trying to execute Modules onto.

I am closing this ticket as nothing can be done with the current amount of information we get. Feel free to add more detailed information. I will then re-open the issue if there is something to work on.
