### ISSUE TITLE
special characters in shell alias are not escaped

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#165]
Should review shell alias creation for all shell as special characters are not correctly escaped there:

```
$ cat test
#%Module
set-alias t {echo $(grep "report \"Modules " modulecmd.tcl | tr -d \\ | awk '{print $3}')}
$ module load ./test
bash: unexpected EOF while looking for matching `"'
bash: syntax error: unexpected end of file
```

**Comment by mgsternberg** [comment]
@xdelaruelle: nice example!

I don’t think aliases are set all that often in modulefiles, but the question on the mailing this week showed that they are being used now and then.

NB: If you wish to accommodate csh as well, be mindful of the rabbit hole that is quoting in csh, see http://www.faqs.org/faqs/unix-faq/shell/csh-whynot/  Sec. 4. QUOTING. (This old but relevant rant is the source of my low assessment for csh.)

**Comment by xdelaruelle** [comment]
@mgsternberg: thanks for the hint!

Will use csh-specific version of the above example:

```csh
echo `grep "report "'"'"Modules " modulecmd.tcl | tr -d \\ | awk '{print $3}'`
```

Fish will also need its specific version:

```fish
echo (grep "report \"Modules " modulecmd.tcl | tr -d \\ | awk '{print $3}')
```
