### ISSUE TITLE
4.1.3: Regression with fish and set-alias

### ISSUE THREAD

**Issue by cmarqu** [cea-hpc/modules#174]
Version 4.1.3 is showing a regression for me when I use fish as my shell and have a modulefile like the following:
```
#%Module1.0
set-alias       fooalias    {\${FOO}/myscript.bash}
```

The output I get is
```
Variables cannot be bracketed. In fish, please use {$FOO}.
- (line 1): function fooalias --wraps ${FOO}/myscript.bash --description 'alias fooalias ${FOO}/myscript.bash';  ${FOO}/myscript.bash  $argv; end
                                       ^
from sourcing file -
        called on line 68 of file ~/tools/share/fish/functions/alias.fish

in function “alias”
        called on line 5 of file -
        with parameter list “fooalias ${FOO}/myscript.bash”

from sourcing file -
        called on line 15 of file -

in function “_moduleraw”
        called on line 18 of file -
        with parameter list “load test-alias”

in function “module”
        called on standard input
        with parameter list “load test-alias”

source: Error while reading file “-”
```
This worked in modules 4.1.1 (I don't have 4.1.2 easily available to test...).

**Comment by xdelaruelle** [comment]
Special character escaping was not correctly performed for shell alias until v4.1.3 (it has been fixed on 810e9eff fo #165).

I assume you did not got any error prior to v4.1.3, however the `fooalias` you got on these older version may not be either functional. Please tell us if I am wrong and precise the version of the fish shell you use in that case.

With fish 2.7 I do not encounter the same issue:

```
> module load alias
> module list
Currently Loaded Modulefiles:
 1) alias  
> fooalias
- (line 1): Variables may not be used as commands. In fish, please define a function or use 'eval $FOO/myscript.bash'.
in function “fooalias”
	called on standard input
```

So maybe you should define shell alias differently for fish shell than for other shells:

```tcl
#%Module1.0

if {[module-info shell fish]} {
    set-alias fooalias {eval $FOO/myscript.bash}
} else {
    set-alias fooalias {\${FOO}/myscript.bash}
}
```

**Comment by cmarqu** [comment]
You are right, the module loading problem is gone when I use a current version of fish (2.7.1) - initially I only had a 2.4.0-prerelease.

While I can ask our admin to special-case the modulefile(s) for fish, it doesn't feel right IMO. After all, the strength of modules is the abstraction from the used shell. Do you consider `set-alias` to be special in that regard?

**Comment by cmarqu** [comment]
Oh, I only now realize that modules already creates a fish function from `set-alias`:
```
$ type fooalias 
fooalias is a function with definition
# Defined in - @ line 0
function fooalias --description 'alias fooalias ${FOO}/myscript.bash'
    ${FOO}/myscript.bash $argv

end
```

It would "just" need to rewrite that `${FOO}` into `eval {$FOO}` and it the function would work.

**Comment by cmarqu** [comment]
...and now I realize that it's not modules which produces the function but fish itself: "alias is a simple wrapper for the function builtin, which creates a function wrapping a command." (from https://fishshell.com/docs/current/commands.html).
Sorry for the noise.

**Comment by xdelaruelle** [comment]
Seems good, I am closing this issue.
