### ISSUE TITLE
Makefile compatibility

### ISSUE THREAD

**Issue by mgsternberg** [cea-hpc/modules#175]
@xdelaruelle 

This is a follow-up regarding the recent mailing list thread [Installing Modules 4.1 on Mac OSX ](https://sourceforge.net/p/modules/mailman/message/36358112/).

Xavier, the following `sed` command can do the job from commit 2f91ab6 without `grep`:

``` sh
$ sed -n '/^%changelog/ {n;s/^\*.* //p;q;}' contrib/rpm/environment-modules.spec.in
4.1.3-1
```

A couple of remarks:
* I was wondering how reliable that extraction is. The `%changelog` format seems to be only loosely defined; [current guidelines at Fedora](https://fedoraproject.org/wiki/Packaging:Guidelines?rd=Packaging/Guidelines#Changelogs) suggest (allow?) three format variants.
* Further down in `Makefile`, there is:
  ```
  MODULES_RPM_RELEASE_P2 := $(shell echo $$(($(MODULES_LAST_RPM_RELEASE_P2)+1)))
  ```
  I thought that could be a portability catch as well but I was pleasantly surprised to learn that [POSIX sh _does_ require arithmetic expansion](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_04),since [at least 2008](http://pubs.opengroup.org/onlinepubs/9699919799.2008edition/utilities/V3_chap02.html#tag_18_06_04), possibly earlier.
* That said, the business for `*_P2` etc. looks complicated. I sprinkled some `$(info ...)` statements into the `Makefile` to see what's done, and I get:
  ```
  GIT_CURRENT_TAG="v4.1.3"
  GIT_CURRENT_DESC="v4.1.3-4-g9a203ef"
  GIT_CURRENT_BRANCH="v4.1.x"
  MODULES_RELEASE="4.1.3"
  MODULES_BUILD_DATE="2018-07-02"
  case v4.1.x
  MODULES_BUILD="+4-g9a203ef"
  MODULES_RELEASE_BASE="4.1.3"
  MODULES_RELEASE_SUFFIX=""
  MODULES_LAST_RPM_VERSREL="4.1.3-1"
  MODULES_LAST_RPM_RELEASE="1"
  MODULES_LAST_RPM_RELEASE_P1="1"
  MODULES_LAST_RPM_RELEASE_P2="1"
  incremented MODULES_RPM_RELEASE_P2="2"
  not_tag MODULES_RPM_RELEASE="1.2"
  polished MODULES_RPM_RELEASE="1.2+4.g9a203ef"
  ```
  Does this look right?  I'm not sure what the critical bits are, but some splitting/processing could be done right along with the `sed` above in the same pipeline:
  ```
  $ sed -n '/^%changelog/ {n;s/^\*.* //p;q;}' contrib/rpm/environment-modules.spec.in \
     | ( IFS=".-" read a b c d; echo "as split: ==$a==$b==$c==$d== arith: $((d+1))" )
  as split: ==4==1==3==1== arith: 2
  ```
  I'd be glad to firm this up.

**Comment by xdelaruelle** [comment]
@mgsternberg That's great stuff, I am lacking expertise in sed so your help is greatly welcomed.

It would be nice to remove totally `grep` and `cut` from the installation requirements and only rely on `sed`. In addition to this Makefile, it is also used in configure script.

The `*_P2` business is far from perfect I agree. What you got from your `$(info ...)` test seems correct. Do not hesitate to craft a fix if you can simplify the way it works.

**Comment by mgsternberg** [comment]
@xdelaruelle 
> Do not hesitate to craft a fix if you can simplify the way it works.

OK; I understand the format of the following two key values:
```
GIT_CURRENT_DESC="v4.1.3-4-g9a203ef"
MODULES_LAST_RPM_VERSREL="4.1.3-1"
```
but  I'll need a hint on what the constituent parts mean in the substring `1.2+4.` of
```
MODULES_RPM_RELEASE="1.2+4.g9a203ef"
```

(I've done little so far in the intersection of `git` and `*.spec` files, the only exception being Lustre, which, incidentally, uses underscore `_` for `Release:` to avoid `-`.)

**Comment by xdelaruelle** [comment]
The idea behind `MODULES_RPM_RELEASE` is to set a new RPM release number greater than the previous one found in spec file.

So here in the example `1.2`, `1` is previous release number found in specfile so to get a greater number an additionnal number is added behind a dot (.) character. There may even be a bug here since `1.1` may be more accurate.

Everything after the `+` character is relative to the current git tag, to help track current HEAD commit on generated RPM release number.

**Comment by degremont** [comment]
rpm offers helpers to extract this information. I do not know if rpm is an acceptable requirment in this context though
```
rpm -q --specfile --qf '%{CHANGELOGNAME}\n' modules.spec
```

The parsing is much easier and reliable.

**Comment by mgsternberg** [comment]
@degremont  Right idea, alas the parsing needs to be done for a template file `*.spec.in`, which does not yet adhere to the spec syntax requirements:
```
$ rpm -q --specfile --qf '%{CHANGELOGNAME}\n' contrib/rpm/environment-modules.spec.in
error: line 5: Illegal char '@' in: Release:        @MODULES_RPM_RELEASE@.el6
error: query of specfile contrib/rpm/environment-modules.spec.in failed, can't parse
```

You're correct that this would introduce an `rpm` requirement, and I'd say that this should be fine since `spec` files _solely_ pertain to `rpm`. Perhaps come configure options `./configure --{with|without}-rpm=…` or  `configure --{enable|disable}-rpm` would be needed for that. But that just seems to make things more complicated than they should really be. I don't have a good high-level view of how that fits in.

**Comment by mgsternberg** [comment]
@xdelaruelle  Assuming the `MODULES_RPM_RELEASE` construction is correct, I'm afraid I can't get into suggesting changes for the `*_P2` business without touching upon the numbering scheme. I merely asked because I noticed the "+" in the build tag and thought it unusual (from my limited experience with git+spec), same thing for the "1.2" part, rather than, say "2" or "3" after seing the `echo ...+1` construct in `Makefile`.

Anyway, short of major new routes, at least the following can drop the `grep` dependency, first in `Makefile`:
``` diff
-MODULES_LAST_RPM_VERSREL := $(shell grep -A 1 '%changelog' \
-	contrib/rpm/environment-modules.spec.in | grep '^* ' | grep -Eo '\S+$$')
+MODULES_LAST_RPM_VERSREL := $(shell sed -n '/^%changelog/ {n;s/^\*.* - //p;q;}' \
+	contrib/rpm/environment-modules.spec.in)
```

And for `./configure`, either this:
``` diff
diff --git a/configure b/configure
index 6df113e..ea6525b 100755
--- a/configure
+++ b/configure
@@ -396,8 +396,8 @@ if [ -d '.git' ]; then
   fi
 # elsewhere fetch modules version from version.inc file
 elif [ -r ${progdir}/version.inc ]; then
-  release=$(grep '^MODULES_RELEASE ' ${progdir}/version.inc | cut -d ' ' -f 3)
-  build=$(grep '^MODULES_BUILD ' ${progdir}/version.inc | cut -d ' ' -f 3)
+  release=$(sed -n '/^MODULES_RELEASE/{s/.*= //p;q;}' ${progdir}/version.inc)
+  build=$(sed -n '/^MODULES_BUILD/{s/.*= //p;q;}' ${progdir}/version.inc)
 fi
 VERSION=$release$build
 
```
or a little more radically/risky by pretty much interpreting a slightly munched version.inc directly as shell code:
``` diff
diff --git a/configure b/configure
index 6df113e..d57efd8 100755
--- a/configure
+++ b/configure
@@ -394,12 +394,12 @@ if [ -d '.git' ]; then
   else
      build="+${gitcurbranch}${gitcurdesc#${gitcurtag}}"
   fi
+  VERSION=$release$build
 # elsewhere fetch modules version from version.inc file
 elif [ -r ${progdir}/version.inc ]; then
-  release=$(grep '^MODULES_RELEASE ' ${progdir}/version.inc | cut -d ' ' -f 3)
-  build=$(grep '^MODULES_BUILD ' ${progdir}/version.inc | cut -d ' ' -f 3)
+  eval `sed -n 's/ *:= */=/p' < ${progdir}/version.inc`
+  VERSION=$MODULES_RELEASE$MODULES_BUILD
 fi
-VERSION=$release$build
 
 if [ -z "$VERSION" ]; then
    echo_error "Cannot fetch modules version"
```

That said, the `grep` in `configure` has been quite tame. I would not have seen a need to check for its presence. If a system has `sed` but not a basic `grep` or `cut`, something would be deeply wrong.

**Comment by xdelaruelle** [comment]
@mgsternberg Thanks for these `sed` commands

Regarding the `MODULES_RPM_RELEASE` construction, the general idea is to craft an unofficial release number that will not get in conflict with the official ones. That is why the `P2` is created or increased rather increasing the `P1` part, which is only increased for official release (so manually increased).

Looking at this whole RPM release numbering: this stuff is too much complex for the test purpose it has. So I will cut it down to just join `MODULES_LAST_RPM_VERSREL` with `MODULES_BUILD`, using '.' character rather the unusual `+`.
