### ISSUE TITLE
ModulesVersion should ignore version not located in current directory

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#176]
Currently ModulesVersion sets in .version modulerc file accepts version name not located in current directory:

```sh
$ cat mp/compiler_a/.version
#%Module1.0
set ModulesVersion "branch_7/compiler_a7.2.0"
```

Which leads to erroneous nested default version set:

```sh
$ module avail compiler_a -t
/path/to/modules/mp:
compiler_a/branch_6/compiler_a6.2.0
compiler_a/branch_7/compiler_a7.2.0(default)
compiler_a/compiler_a.1.0
```

That a `module load` command is not able to understand:

```sh
$ module load compiler_a
ERROR: Unable to locate a modulefile for 'compiler_a/compiler_a7.2.0'
```

Such nested version set to ModulesVersion in a .version file should not be taken into account.

Also some clarification to the use of nested element should be added to the module-version description in modulefile manpage and to the "locating modulefile" section in this same manpage.

**Comment by xdelaruelle** [comment]
Similar work done on Modules compatibility version:
https://bugzilla.redhat.com/show_bug.cgi?id=979787

**Comment by bclmary** [comment]
This correction disable a possibility.
Let say I have the following subdirectories:

```
app
    |- app_vendorA
    |    |- app_vendorA_v1
    |    |- app_vendorA_v2
    |- app_vendorB:
         |- app_vendorB_v1
         |- app_vendorB_v2
```

Then it is impossible to define a global default for app, say, app_vendorB_v2 .
Or is there a workaround ?

**Comment by xdelaruelle** [comment]
You still have this possibility with a `.version` file under the `app` directory that sets:

    set ModulesVersion app_vendorB

Then a `.version` file under the `app_vendorB` directory that sets:

    set ModulesVersion  app_vendorB_v2

With that a bare `module load app` will load the `app/app_vendorB/app_vendorB_v2` modulefile.

**Comment by bclmary** [comment]
Thanks for reply :-)
This seems to make no difference with setting only a `.version` file in the last level of folders.
As an example (with `.version` files on each folder levels), if a enter `module avail --default`, I get both vendor versions (the one setted with a `.version` file, and the higher version of the other).

**Comment by xdelaruelle** [comment]
When you do not set a default version, an implicit default is used which corresponds to the highest numerically entry in the directory. In your example, if you do not define a default under the `app` directory, the `app_vendorB` directory will be the implicit default.

`module avail --default` lists all implicitly or explicitly set default versions at all levels. Which means in your example you will not have only 1 entry for all `app` modules, but 1 entry for the default `app/app_vendorA` version and another entry for the default `app/app_vendorB` version.

**Comment by bclmary** [comment]
This is clear. Is there a way to silent implicit default then ?

**Comment by xdelaruelle** [comment]
Not in current version but next feature release (v4.3) will include an option to force users to fully qualify the modulefiles they want to use (#179) which I think will be equivalent to silent implicit default.
