### ISSUE TITLE
Make a ".default" file with the same behavior than "default" file but hidden

### ISSUE THREAD

**Issue by Rehvaro** [cea-hpc/modules#177]
Hello.

We would like to force users to specify a version for each software they want to load.
So `module load intel/2018.3` would work, but `module load intel` would send an error and doesn't load any module.
One way to do that is by using a "default" file in each software module directory, with an error and using the `exit ` function.
It works, but all the default files are visible in `module avail ` and when we use "tab" key.
So, could it be possible to add a _.default_ file acting like the _default_ file, but as the _.version_ file, would also be hidden from the available modules ?

Thanks

**Comment by xdelaruelle** [comment]
Hello,

During the last months I have heard many times the use case you describe here. So I propose to have a proper solution to handle it with for instance an option set at configure time or an environment variable to force users to fully qualify the modulefiles they want to use (#179).

In the mean time, you should be able to workaround this use case by defining the `.default` modulefile as the default version with a `.modulerc` file

```
#%Module
module-version ./.default default
```

However I just hit a bug here as `.default` is an hidden file not part of the initial modulefile search:

```
ERROR: Unable to locate a modulefile for 'foo/.default'
```

I will fix that issue to make this workaround valid.

**Comment by Rehvaro** [comment]
Nothing to add, perfect.
I just want to say thank you !
(I hope it doesn't reopen the issue, if it does, sorry)
