### ISSUE TITLE
$ModulesCurrentModulefile set with forward slashes on Windows

### ISSUE THREAD

**Issue by BrennanGit** [cea-hpc/modules#180]
First, I'd like to say how happy I am to see this project being actively maintained, great work.

It would be nice to have $ModulesCurrentModulefile set with OS appropriate path separators.
We are using this to test whether the modulefile exists within a certain directory from an environment variable.

It's just a small thing but would simplify my life a little.

**Comment by xdelaruelle** [comment]
Thanks for your comment.

I will dig into that for a future feature release. However with a first look, it seems some file-related commands of Tcl use forward slashes even on Windows (like the `pwd` command).

It is say that forward slashes are also natively accepted on Windows. It would help if you describe the issues you encounter using file path with forward slashes on Windows.

**Comment by BrennanGit** [comment]
Thanks for the reply. We are trying to test whether the modulefile exists in an 'installed' store or whether it is checked out within a source repo for development, the relative path to the binaries will be different in each case. 
We do a string match to test whether the current modulefile exists under a user-set environment variable: 
`[string match "$::env(STORE)*" $ModulesCurrentModulefile]`
We can certainly work around it using `file nativename`, just something I thought you might like to know.

**Comment by xdelaruelle** [comment]
For the record: even on a Windows platform, Tcl use an Unix-like represetation of pathname using `/` character rather `\`.

Small Tcl example code:
```tcl
set filepath User\\file.txt
puts "normalize: [file normalize $filepath]"
puts "normalize + nativename: [file nativename [file normalize $filepath]]"
```

Ran through `cmd` shell:
```console
C:\Users\MyUser\Documents>tclsh test.tcl
normalize: C:/Users/MyUser/Documents/User/file.txt
normalize + nativename: C:\Users\MyUser\Documents\User\file.txt  
```

So as mentioned the best way to perform pathname comparison is to apply the `file nativename` procedure:

```tcl
[string match [file nativename $::env(STORE)*] [file nativename $ModulesCurrentModulefile]]
```
