### ISSUE TITLE
Examples for ModulesTest missing

### ISSUE THREAD

**Issue by cmarqu** [cea-hpc/modules#182]
It would be nice to have some examples for a good [ModulesTest](http://modules.readthedocs.io/en/latest/modulefile.html?highlight=modulestest#modulefile-specific-test).

I guess for a module loading a tool, it could be checked that the main tool is found in `$PATH` and can display its version number without crashing, meaning that it finds its libraries and was compiled for the right architecture.

For a module that sets up a project environment, it could be checked that the user is allowed to `cd` into the project directory and maybe `touch` a file there.

Any more?

**Comment by xdelaruelle** [comment]
Maybe checking that any configured directory does exist.

I plan to have a "recipes" section in the user documentation, so it would be nice as you suggest to have something on the ModulesTest feature. Feel free to draft something.

**Comment by cmarqu** [comment]
Okay, here is an example module:
```
#%Module1.0 # -*- mode: tcl; -*-

proc ModulesTest { } {
    set retcode 1  ;# default: 1 meaning PASS

    puts stderr "Running ModulesTest for directory existence..."
    if { [file isdirectory $::env(TESTDIR)] } {
        puts stderr "Is a directory: $::env(TESTDIR)"
    } else {
        puts stderr "ERROR: Is not a directory: $::env(TESTDIR)"
        set retcode 0
    }
    puts stderr "Running ModulesTest for directory existence...done"

    puts stderr "Running ModulesTest for directory permissions..."
    set cmd "cd $::env(TESTDIR)"
    if { [catch $cmd errmsg] } {
        puts stderr "ERROR: Could not enter directory $::env(TESTDIR)"
        set retcode 0
    } else {
        puts stderr "Could enter directory $::env(TESTDIR)"
    }
    puts stderr "Running ModulesTest for directory permissions...done"

    puts stderr "Running ModulesTest for file creation..."
    set cmd "open $::env(TESTFILE) w"
    if { [catch $cmd errmsg] } {
        puts stderr "ERROR: Could not create file $::env(TESTFILE)"
        set retcode 0
    } else {
        puts stderr "Could create file $::env(TESTFILE)"
    }
    puts stderr "Running ModulesTest for file creation...done"

    return ${retcode}
}

setenv TESTDIR /tmp/$env(USER)/testdir
setenv TESTFILE $env(TESTDIR)/testfile
```

**Comment by xdelaruelle** [comment]
This example would perfectly fit in a cookbook recipe.

**Comment by cmarqu** [comment]
I hadn't realized that the infrastructure for this is already present:
https://github.com/cea-hpc/modules/tree/master/doc/source/cookbook

**Comment by xdelaruelle** [comment]
Yes! It would be great if you could provide your example as a cookbook recipe via a pull request.

**Comment by cmarqu** [comment]
Ok, I have started working on this in https://github.com/cmarqu/modules/tree/cookbook-add-modules-test.
