### ISSUE TITLE
Display warning message if module to load/unload is already loaded/unloaded

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#187]
As [described](https://sourceforge.net/p/modules/mailman/modules-interest/thread/3EEB2422-4AE2-4CBE-B803-54CB531DA26E%40pawsey.org.au/#msg36396987) by @mcytu, it would be nice to get a warning message when a `module unload` does not unload anything because the specified module is not loaded.

Following the same trend, it would also be nice to get this kind of warning when a `module load` does not load anything as specified module is already loaded.

The idea here is to add a `./configure` option, a `MODULES_` environment variable and a command-line switch for `load`, `unload` and `switch` commands to control whether or not a warning message should be printed if a module to load or unload is already loaded or unloaded

**Comment by wenzler** [comment]
Sorry, found another difference for non existing modules that might be considered related :)

v3
module rm bla
ERROR: Unable to locate a modulefile for 'bla'

v4 
module rm bla
nothing - exit code is also 0

**Comment by xdelaruelle** [comment]
@wenzler I have just created a dedicated issue for this (#199). Precisely, v3 is silent whereas v4 returns an error when modulefile does not exist

**Comment by xdelaruelle** [comment]
Will report *informational* messages in case the verbosity level is `verbose2` or any higher level.
