### ISSUE TITLE
getenv not working in test/help/whatis modes

### ISSUE THREAD

**Issue by cmarqu** [cea-hpc/modules#188]
I was trying to port over my code in https://github.com/cea-hpc/modules/issues/182 to use ``getenv`` instead of ``$env``, but it seems ``getenv`` does not work in the ``test/whatis/help`` modes (similar to https://github.com/cea-hpc/modules/issues/160). This is in both 4.1.3 and 4.1.4

**Comment by xdelaruelle** [comment]
Right, it affects version v4.1.4 and lower versions. Fixed by #85a45a which will be part of v4.2
