### ISSUE TITLE
ERROR: Unable to locate a modulefile for 'gcc/4.2.1'

### ISSUE THREAD

**Issue by ComplicatedPhenomenon** [cea-hpc/modules#192]
Hi, 
I just had a simple question that's probably going to make me look dumb, but  when I make a try of installed `module4.1.4` and get an error 
```
$ module load gcc/4.2.1
ERROR: Unable to locate a modulefile for 'gcc/4.2.1'
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.43.1)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
Below is the operation I made before this error. I install from a distribution tarball. According to 
```
$ ./configure
$ make
$ sudo make install
```
At first the problem is 
`checking TCL_LIB_SPEC... configure: error: TCL_LIB_SPEC not found, need to use --with-tcl-lib` during first step  `./configure`
Then I download `tcl8.6.8-src.tar.gz` and install it. There seems no error to me during `make` and `sudo make install`.
Then I go through
```
$ module
-bash: module: command not found
$ source init/bash
Modules Release 4.1.4 (2018-08-20)
Usage: module [options] [command] [args ...]
...
```

I've read the manual but still didn't work out a way. Please help me out.
Thanks

**Comment by ComplicatedPhenomenon** [comment]
@xdelaruelle 

Many thanks for your elaborate answer. Something went wrong 
```
$ ./configure --with-tcl=/System/Library/Frameworks/Tcl.framework/Versions/8.5
...
checking for Tcl configuration (tclConfig.sh)... configure: error: /System/Library/Frameworks/Tcl.framework/Versions/8.5 directory doesn't contain tclConfig.sh
```

**Comment by ComplicatedPhenomenon** [comment]
@xdelaruelle 

Many thanks for your elaborate. Something went wrong. And it both occurs on Ubuntu17.10 and OSX.
```
$ ./configure --with-tcl=/System/Library/Frameworks/Tcl.framework/Versions/8.5
...
checking for Tcl configuration (tclConfig.sh)... configure: error: /System/Library/Frameworks/Tcl.framework/Versions/8.5 directory doesn't contain tclConfig.sh
```

**Comment by xdelaruelle** [comment]
@ComplicatedPhenomenon The ``--with-tcl=/System/Library/Frameworks/Tcl.framework/Versions/8.5`` configure option only goes for OSX when Xcode is installed on it. If you are not in this situation what you did with the `tcl8.6.8-src.tar.gz` installation you mentioned is indeed the way to go to install the missing Tcl dependency.

**Comment by ComplicatedPhenomenon** [comment]
@xdelaruelle I have Xcode installed on OSX.  
```
$ ./configure --with-tcl=/System/Library/Frameworks/Tcl.framework/Versions/8.5
...
checking for Tcl configuration (tclConfig.sh)... configure: error: /System/Library/Frameworks/Tcl.framework/Versions/8.5 directory doesn't contain tclConfig.sh
$ tree -L 1 /System/Library/Frameworks/Tcl.framework/Versions/8.5/
/System/Library/Frameworks/Tcl.framework/Versions/8.5/
├── Resources
 │   ├── BridgeSupport
 │   ├── Documentation
 │   ├── Info.plist
 │   ├── Scripts
 │   ├── license.terms
 │   ├── tcl8
 │   └── version.plist
├── Tcl
├── _CodeSignature
 │   └── CodeResources
└── tclsh8.5

6 directories, 6 files
```

**Comment by xdelaruelle** [comment]
@ComplicatedPhenomenon I remember this option is useful when upgrading to Xcode 9.4. Anyway the way you built Modules with the `tcl8.6.8-src.tar.gz` installation is perfectly fine.

**Comment by ComplicatedPhenomenon** [comment]
Hi,@xdelaruelle
You already helped me,  which I didn't realize until now.
> Once you have installed Modules, you need to create or use modulepaths and modulefiles. Modulepaths are directories containing modulefiles, the module use command helps to add new modulepath to the modulefile search path. Then in these directories you should write (or reuse if they already exist in your setup) modulefiles for the apps you want to configure with the module command.

>  So in your case there should be a modulepath directory in which there should be a gcc directory which in turns contains a 4.1.2 modulefile.

All I need to do is write a modulefile for my application and put it under directory `/path/to/modulefiles` . Thanks!
