### ISSUE TITLE
displayElementList can error out with "rows" undefined

### ISSUE THREAD

**Issue by omvsomvs** [cea-hpc/modules#195]
We recently upgraded our modules from an old version to 4.1.1, and some users were having "modules list" die.  After some debugging, I found the problem was at line 5704 when it tested if $cur_rows == $rows.  For some size terminals with one of our common module listings, it would enter evaluate that line twice before rows got set - the first time $last_round was not set, so the error didn't occur and last_round would get set.  But the second time it failed comparing against rows.

As a workaround I initialized rows to 0 inside the test at line 5660 along with columns - this seemed like a pretty safe fix, though not sure if there's other issues in the loop  - logic is a bit hard for me to follow.

I also verified 4.1.4 has the same issue - this function appeared to be mostly unchanged.

Unfortunately, I can't provide our module list to reproduce without some scrubbing, and wanted to at least report the issue before I forgot.

**Comment by xdelaruelle** [comment]
Thanks for the report, the terminal size and the available module list would be key here to track this issue. I would greatly appreciate if you could perform the scrubbing you talk about and provide elements to be able to reproduce the issue

**Comment by omvsomvs** [comment]
Hi Xavier!

Below is the output of module list in 3.2.6, fed through a quick script to mangle the names.  In 4.1.1, terminal widths between 80 and 86 inclusive seemed to cause problems without my hack to init rows == 0

If thats still not sufficient, let me know.  I didn't want to try and hack up an entire test environment yet since we're still dealing with other fallout from our weekend upgrade...

Thanks!

-dan

[dhartman@censored]$ module list
Currently Loaded Modulefiles:
1) abc/def                               
 2) abcdefgh/ijklmnop                     
 3) abc/defg                              
 4) abcd/ef                               
 5) abc/defg-hijkl.mn.op                  
 6) abcdefgh/ijklm.nopqrst                
 7) abcdefg/hijklmnop-qr.st.uvw           
 8) abcdefgh/ijklmnopqrst-u-vwxy.zA-BCD-E 
 9) abcdef/ghijklm-nopq.r_st.uv           
10) abcdefgh/ijklmnop-q-rstu.vw-xyz-A      
11) abcdefg/hijklmn-op.qr.stu             
12) abcdefg/hijkl-mn.op.qrs               
13) abcd/efgh-ij.k                        
14) abcdefg/hijk-lmnop_qr.st.uvw          
15) abcdef/ghijklmno-p.q.r                
16) abcdefgh/ijklmn-o-pqrs.tu             
17) abcdefgh/ijklmnop-q-rstu.vw-xyz       
18) abcdefg/hij-klm.nopq                  
19) abcdefg/hij-kl.mn.opq                 
20) abcdefgh/ijklmnopq_rstuv-w-xyzA.BC-DEF
21) abcdefgh/ijklmnopqrstuv-w-xyzA.BC     
22) abcdefgh/ij-k-lmno.pq                 
23) abcdefgh/ijk-l-mnop.qr-stu            
24) abcdefgh/ijklmnop-qr.st               
25) abcdef/ghijklmno-pq.rs                
26) abcdef/ghi-jklm_no_pqrstuv            
27) abcdefgh/ijk-lm-n-opqr.st             
28) abcdefgh/ijklm-n-opqr.st-uvw          
29) abcdef/ghijklm-nopq_r                 
30) abcdefg/hijkl-mn.op.qrs               
31) abcdefg/hijklmn-op.qr.stu             
32) abcdefgh/ijklmn

**Comment by xdelaruelle** [comment]
Hi Dan,

I confirm that I am able to reproduce the issue with the output list you provided.

Fix is ongoing.
