### ISSUE TITLE
conconfigure can't find version of tcl

### ISSUE THREAD

**Issue by jsboer** [cea-hpc/modules#196]
as the title,what should i do?
```
checking for Tcl configuration (tclConfig.sh)... found /usr/lib/tcl8.4/tclConfig.sh
checking for existence of tclConfig.sh... loading
checking for Tcl version... configure: error: Must specify version (X.Y) if using this option
```

**Comment by xdelaruelle** [comment]
It depends on the OS you are running on. It may requires you add the `--with-tcl-ver=8.4` option to the `./configure` command line.

Moreover the issue you get is for building the compatibility version of Modules. If you just want the new version 4 release, you may skip this compatibility version built with the `--disable-compat-version` configure option.

**Comment by jsboer** [comment]
thank you, it works.
