### ISSUE TITLE
unload firstly loaded module rather lastly loaded

### ISSUE THREAD

**Issue by wenzler** [cea-hpc/modules#198]
Hey,

doing something like
module add gcc/1.0
module add gcc/2.0
module rm gcc

has different results between v4 and v3
v3 removes the first loaded module
v4 the last added module

Is there a way to revert this behavior back to v3 style?

Thanks!

**Comment by xdelaruelle** [comment]
Hi,

Lastly loaded module is preferably unloaded to limit impact on loaded module list when dependencies are woven between these loaded modules.

Is there an issue proceeding that way ? Is there a use case where unloading firstly loaded module is preferable?

Regards,
Xavier

**Comment by wenzler** [comment]
People obviously do weird things and get used to it when writing large amounts of jenkins jobs...
In the end its a deviation towards to the original behavior and not listed on the migration page.

**Comment by wenzler** [comment]
As I'm currently pushing hard towards migration to v4, I will surely have more of these compatibility issues pointed out by our user base (~15000).

Don't want to nag here for sure...
Regardless, please point out a way to send you beer etc

BR
Wenzler

**Comment by xdelaruelle** [comment]
Thanks for the details you provided. Please do not refrain from submitting issues like that. Much appreciate.

I have just updated the "difference between v3.2 and v4" documentation to detail this behavior change you spot. I have also added a ``siteconfig.tcl`` recipe file in the cookbook to get the same behavior than compatibility version. Just copy this ``siteconfig.tcl`` in the ``etc`` directory of your Modules installation.

I will work for the next feature release after v4.2 on a configuration to set to get this *unload firstly loaded modulefile* behavior.

Best regards,
Xavier

**Comment by wenzler** [comment]
Something weird we stumbled upon in 4.2.1 in this regard
module use ~/modules
module add python
module add python/3.6.0
module add mymodule
Loading mymodule
  ERROR: mymodule cannot be loaded due to a conflict.
    HINT: Might try "module unload python" first.

cat ~/modules/mymodule
#%Module1.0
module rm python

**Comment by xdelaruelle** [comment]
Could you please provide the content of the `python` modulefiles. It would help to know if and how these modulefiles declare conflict against `mymodule`.

**Comment by wenzler** [comment]
There is no conflict declarations 
it simply prepend path stuff in there 
but as soon as there are several versions of the same software loaded 
mymodule breaks it

**Comment by xdelaruelle** [comment]
> There is no conflict declarations
> it simply prepend path stuff in there
> but as soon as there are several versions of the same software loaded
> mymodule breaks it

Thanks for these precisions, I have opened a dedicated issue for this.
