### ISSUE TITLE
Modulefile command to hide a given module from avail/search results

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#202]
Following [this discussion](https://sourceforge.net/p/modules/mailman/message/36439586/) it would be nice to get a modulefile command to order that a given module should not be mentioned from avail/search/whatis results. Modulefiles could already be hidden by prefixing their name by a dot character (.), but a command would help to hide dynamically depending on the situation.

This should be a rc file command (ie. used from `.modulerc` files) as true modulefile are not evaluated during `avail` command.

We may even extend this "hidding" concept to a "hide if criteria met" concept, for instance:
* hide modulefile if not part of group
* hide modulefile if some expiry date is over

**Comment by fthommen** [comment]
A hiding mechanism - especially the "hiding if criteria met" - would solve lots of issues also on our side.  Our use case: We have a common software stack for multiple distributions but not all packages are provided for all distros.  Currently we have to provide a different $MODULESPATH for each distribution which leads to lots of redundancies (all the common packages).  A hiding mechanism would be an elegant solution for this situation.

**Comment by xdelaruelle** [comment]
> Please also consider modules that are to be phased out/deleted.
They should not appear in module avail already but be addable with a warning :>

Exactly, this is what I meant with *hide modulefile if some expiry date is over*
