### ISSUE TITLE
Enhancement: add support of clear / clear yes

### ISSUE THREAD

**Issue by wenzler** [cea-hpc/modules#203]
As advised .. Thanks already! :)

Btw did you add stubs wherever you were unable to support it?
I just saw things like "unsupported [...] commands are ignored"

**Comment by wenzler** [comment]
Has this been removed from 4.2.5? 
I do not see any support for module clear in there.

**Comment by xdelaruelle** [comment]
This new feature is not part of the `4.2` serie, so it is not there in `4.2.5`. It will be part of `4.3` that will be out (`4.3.0`) in a few weeks.
