### ISSUE TITLE
Suppress verbose summary messages

### ISSUE THREAD

**Issue by zerothi** [cea-hpc/modules#204]
The recent 4.2.0 version introduces verbose printing of modules loaded in module files.

This is explained here:
https://modules.readthedocs.io/en/stable/MIGRATING.html#improved-module-message-report

I would like to disable these outputs, i.e. the full summary.
How to do that?
ENV? In the TCL script? Or?

**Comment by wenzler** [comment]
````
--- modulecmd.tcl~      2018-10-18 15:02:39.927522000 +0200
+++ modulecmd.tcl       2018-10-18 15:03:40.885767000 +0200
@@ -28,6 +28,7 @@
 set g_return_false 0 ;# False value is rendered if == 1
 set g_autoInit 0
 set g_inhibit_interp 0 ;# Modulefile interpretation disabled if == 1
+set g_inhibit_inforeport 0 ;# Non-critical info reporting disabled if == 1
 set g_inhibit_errreport 0 ;# Non-critical error reporting disabled if == 1
 set CSH_LIMIT 4000 ;# Workaround for commandline limits in csh
 set flag_default_dir 1 ;# Report default directories
@@ -365,7 +366,9 @@

 proc reportInfo {message {title INFO}} {
    # use reportError for conveniance but there is no error here
-   reportError $message $title 0
+   if {!$::g_inhibit_inforeport} {
+      reportError $message $title 0
+   }
 }

 # render messages related to current record id under an header block
````

**Comment by xdelaruelle** [comment]
I have created a `siteconfig.tcl` file that implements the change proposed by @wenzler. You can find it [in this repository](https://github.com/cea-hpc/modules/blob/master/contrib/cookbook/inhibit-report-info/siteconfig.tcl).

Put this file in the `etc` directory of your Modules installation. Refer to the [Modulecmd startup](https://modules.readthedocs.io/en/latest/module.html#modulecmd-startup) section in the module(1) man page to get this location.

With that you can workaround your issue. Some command-line switches and an environment variable will be added later on to control the quietness.

**Comment by zerothi** [comment]
Thanks for the quick fix! :)

I'll let this be open so you can close when the control is added.

**Comment by zerothi** [comment]
For future reference, the link @xdelaruelle refers to is now in the documentation [here](https://modules.readthedocs.io/en/latest/cookbook/inhibit-report-info.html).

**Comment by xdelaruelle** [comment]
The control of the `module` command verbosity is introduced in the upcoming v4.3. Choosing the `concise` verbosity level will inhibit the informational messages.
