### ISSUE TITLE
init/$(SHELL) to stop if eval modulecmd.tcl fails

### ISSUE THREAD

**Issue by alef** [cea-hpc/modules#208]
Some shared computers may not have _/usr/bin/tclsh_. My shared home profile always sources _init/profile.sh_ when I log in there. The `init/$(SHELL)` fails to `eval` _modulecmd.tcl_ because of missing TCL, but sets anyway `ENV` and `BASH_ENV` (in my case) among other things, which lead to spurious message invoking scripts.

It would be nice if there is no need for checking in advance whether to source _init/profile.sh_ based on what computer.

**Comment by xdelaruelle** [comment]
What could be done is to quit `init/$(SHELL)` script if the `eval modulecmd.tcl` failed. This way if `module` cannot be initialized no environment variable, like `ENV`, etc, should be altered.

**Comment by xdelaruelle** [comment]
No quit in the end, but no environment alteration made if the `autoinit` command fails
