### ISSUE TITLE
Enhancement: flag to ignore default by .version

### ISSUE THREAD

**Issue by wenzler** [cea-hpc/modules#210]
module add –no-default git

**Comment by xdelaruelle** [comment]
When there is no explicit default defined the implicit default is the latest version, maybe if would be more natural to add a `--latest` option rather `--no-default` to say *I want the latest version* rather *I do not want the default version*

It would also relate to the already existing  `--latest` option on the `avail` command that only returns the latest version of available modulefiles.

**Comment by wenzler** [comment]
Sure, fine with me

**Comment by xdelaruelle** [comment]
Second thought on this, I would better go for a finer version selection specification like the one planned for modulefile commands like `prereq` and `conflict`

`prereq lib >= 1.2`

Same would go on the command line:

```sh
module load lib >= 1.2
module load app = latest
```

**Comment by xdelaruelle** [comment]
Will be done as an enhancement of the [advanced version specifiers](https://modules.readthedocs.io/en/stable/MIGRATING.html#advanced-module-version-specifiers):

    module load app@latest
