### ISSUE TITLE
Enhancement: allow different sorting for default determination

### ISSUE THREAD

**Issue by wenzler** [cea-hpc/modules#211]
A common problem with modules is that today's software versions aren't sort-able

e.g
git/2.9.2 is older than git/2.12.0

yet 2.9.2 is loaded on module add git

Grouped sorting is required

Similar to https://stackoverflow.com/questions/40201533/sort-version-dotted-number-strings-in-javascript

**Comment by xdelaruelle** [comment]
Should works correctly with Modules 4+:

```bash
$ module list
No Modulefiles Currently Loaded.
$ module avail foo
------------ /path/to/mp -------------
foo/2.9.2  foo/2.12.0  
$ module load foo
$ module list
Currently Loaded Modulefiles:
 1) foo/2.12.0
```

Thanks to the [dictionary sort of Tcl](https://www.tcl.tk/man/tcl/TclCmd/lsort.htm#M6).

Do you have a different experience with Modules 4+ ?

**Comment by wenzler** [comment]
Uhh! I simply didnt notice and expected the old 3 behaviour. Great!
