### ISSUE TITLE
Installation with compatibility may stall on /bin/csh test for long variables

### ISSUE THREAD

**Issue by zerothi** [cea-hpc/modules#214]
On some of our platforms I hit a problem with the `configure` test with

    $as_echo_n "checking if /bin/csh supports large environment variables... " >&6; }

The problem is that `csh` may start in interactive mode, regardless of script argument.

The easy fix would be to change in `configure.ac`/`configure`:

    cat <<'!' | /bin/csh 2> /dev/null | tail -1

to
    
    cat <<'!' | /bin/csh -f 2> /dev/null | tail -1

which works.
This probably needs some adaptation since I haven't tested this on all platforms... :(

PS. My OS is ScientificLinux 6.4 and 7.3.

**Comment by xdelaruelle** [comment]
Should not be a big deal to add this `-f` flag.

@zerothi Could you please provide the `csh` configuration that starts it interactive mode, regardless of script argument ? It would help to reproduce the issue and correctly fix it.

**Comment by zerothi** [comment]
By digging deeper, I have found that this was a maintenance issue and that it was my own fault.

Sorry for the blurp... and thanks for listening...
