### ISSUE TITLE
Conflict Unload: remove multiple loaded modules matching one conflict constraint

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#215]
Something weird we stumbled upon in 4.2.1 in this regard
module use ~/modules
module add python
module add python/3.6.0
module add mymodule
Loading mymodule
  ERROR: mymodule cannot be loaded due to a conflict.
    HINT: Might try "module unload python" first.

cat ~/modules/mymodule
#%Module1.0
module rm python

At the point mymodule is added, python/3.5.0 and python/3.6.0 are present.

_Originally posted by @wenzler in https://github.com/cea-hpc/modules/issues/198#issuecomment-452640010_

There is no conflict declaration in the `python` modulefiles. it simply prepend path stuff in there but as soon as there are several versions of the same software loaded `mymodule` breaks it

**Comment by wenzler** [comment]
I see that both modules have a 
setenv pythonPATH /app/python/version 
in them
Could this be the cause?

Other than that just prepend-path statements as said

**Comment by xdelaruelle** [comment]
Also, to get same behavior than on version 4.1, use `--force`` command line switch:

    module load --force mymodule

**Comment by xdelaruelle** [comment]
I get it, there is a need to simultaneously have multiple `python` modules loaded.

So the `module rm python` in `mymodule` cannot obtain a consistent situation as `module rm` only removes one loaded module at a time.

It was already the case with the previous version of Modules: in the example you describe after the load of `mymodule` there were still one `python` module loaded, which is not consistent with the requirement `mymodule` described.

One workaround way to go (but I do not like it, just to solve your issue with the current release) is to update the `module rm` statement with multiple `python` name:

    module rm python python

On the long run, I wonder the need of this `module rm python` statement in `mymodule` as you do not want a conflict between it and the `python` modules and this `rm` order is not satisfied when multiple python modules are loaded at the same time.

**Comment by wenzler** [comment]
They actually just wanted to remove just one python of the two
I wouldnt ever want such unprecise module rm statement ... but you know people

**Comment by xdelaruelle** [comment]
I have improved the situation a bit with the fix for #216. Now in case a conflict constraint toward a modulefile is set by an already loaded modulefile, loading the conflicting modulefile will lead to a load evaluation attempt in order for this modulefile to get the chance to solve the constraint violation. If at the end of the load evaluation, the conflict has not been solved, modulefile load will be discarded.

However `mymodule` will still get an issue at load time if there are multiple python modules loaded (1 will be automatically unloaded, but as there is 1 remaining a consistency error will raise). This error indicates to the user what he/she wants to do lead to an inconsistent environment (based on what modulefiles declare). He/she can by-pass that error with the `--force` command-line switch.

Auto handling mechanisms cannot do better at the moment as no conflict unload is performed. This upcoming _Conflict Unload_ mechanism should unload all the loaded modules matching a conflict definition to improve the situation here.
