### ISSUE TITLE
Order of unload modules is important

### ISSUE THREAD

**Issue by zerothi** [cea-hpc/modules#218]
Prior to 4.2 I had no issues unloading multiple modules with dependencies on a single line.

Consider this example:

- module file `init`
```bash
#%Module1.0
setenv MY_INIT 1
```
- module file `depend`
```bash
#%Module1.0
prereq init
setenv MY_DEPEND 1
```

Now I do:
```bash
$> module load init depend
$> module list
Currently Loaded Modulefiles:
 1) init   2) depend  
$> module unload init depend
Unloading init
  ERROR: init cannot be unloaded due to a prereq.
    HINT: Might try "module unload depend" first.
```
This shouldn't be a problem since `depend` is also unloaded. Obviously doing `module unload depend init` works.. ;)

This is a huge problem since it requires to do the opposite unload compared to load. It becomes difficult for automatic programs to do correct unloading due to rotated arguments.

**Comment by xdelaruelle** [comment]
Seems a good use case for the [automated module handling](https://modules.readthedocs.io/en/latest/MIGRATING.html#automated-module-handling-mode). If you add the `--auto` command-line switch on your `module unload init depend` command it will handle things automatically. Which means in your case when the unload of the `init` modulefile starts it sees `depend` depends on it thus it unload `depend` before unloading `init`.

Prior version 4.2, dependencies between modulefiles where not tracked once loaded, thus `init` modulefile may be unloaded at any time even if it broke `depend` module. Now these dependencies are tracked and the consistency is ensured. That is why you got an error you did not had with older versions.

**Comment by zerothi** [comment]
@xdelaruelle thanks! (sorry for the slow feedback!)
