### ISSUE TITLE
autocomplete writes to non writable file

### ISSUE THREAD

**Issue by yankee14aaaa** [cea-hpc/modules#219]
modulecmd 4.1.4 with cshell.

Hi, 

 init/tcsh_completion defines aliases for autocompletion. It seems that the _module_not_yet_loaded fails on our system:
alias _module_not_yet_loaded '\\
        mkfifo /tmp/modules_tcsh_completion.$$.p1 /tmp/modules_tcsh_completion.$$.p2 && \\
        ( _module_avail | sort > /tmp/modules_tcsh_completion.$$.p1 & ); \\
        ( _module_loaded | sort > /tmp/modules_tcsh_completion.$$.p2 & ); \\
        comm -23 /tmp/modules_tcsh_completion.$$.p1 /tmp/modules_tcsh_completion.$$.p2; \\
        rm /tmp/modules_tcsh_completion.$$.p1 /tmp/modules_tcsh_completion.$$.p2'

mkfifo tries to write to a file that already exists and is not writable.

Changing to
alias _module_not_yet_loaded '\\
        unset noclobber ; \\
	mkfifo --mode=u+rw /tmp/modules_tcsh_completion.$$.p1 /tmp/modules_tcsh_completion.$$.p2 && \\
        ( _module_avail | sort > /tmp/modules_tcsh_completion.$$.p1 & ); \\
        ( _module_loaded | sort > /tmp/modules_tcsh_completion.$$.p2 & ); \\
        comm -23 /tmp/modules_tcsh_completion.$$.p1 /tmp/modules_tcsh_completion.$$.p2; \\
        \rm /tmp/modules_tcsh_completion.$$.p1 /tmp/modules_tcsh_completion.$$.p2'

works for us.  Changes:
Add: unset noclobber  to allow redirect to overwrite
Add: --mode=u+rw to the mkfifo
Escape: \rm to use the native command which does not require approval

n.b. there may be more robust implementations.
Regards
Yves

**Comment by xdelaruelle** [comment]
I will use the `>!` IO redirection to ensure fifo files are written instead of unsetting the `noclobber` variable
