### ISSUE TITLE
C-string errors

### ISSUE THREAD

**Issue by hainest** [cea-hpc/modules#221]
[c-3.2//compat/cmdXResource.c:432](https://github.com/cea-hpc/modules/blob/c-3.2/cmdXResource.c#L432): Missing pointer declaration.

[c-3.2//compat/utility.c:3097](https://github.com/cea-hpc/modules/blob/c-3.2/utility.c#L3097): Pointer-integer comparison. I believe a non-null + non-empty check was being attempted. There is also a logic issue here. When the string is not converted to an integer, `g_retval` is undefined.

**Comment by xdelaruelle** [comment]
Fixed by PR #222
