### ISSUE TITLE
Init man configuration vanishes when a modulefile sets MANPATH

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#224]
Follow-up on [this mailing-list discussion](https://sourceforge.net/p/modules/mailman/message/36591655/).

At Modules initialization time, when `MANPATH` variable is not set, the `manpath` tool is able to find manpage directories that are neighbor of the directories set in `PATH`. That is why Modules man directory is automatically found after adding Modules bin directory to `PATH` variable.

In this situation Modules initialization script does not set `MANPATH` as Modules man directory is found by the man system configuration.

But as soon as a modulefile adds a directory to the `MANPATH` variable, this variable becomes set and man system configuration vanishes (so you loose default and Modules-specific man directories).

So it seems `MANPATH` should be always initialized in any case by the Modules initialization script to ensure nothing breaks when the `MANPATH` variable is set. Default value could be ":" to still rely on man configuration.

**Comment by xdelaruelle** [comment]
Following [this update on the issue reported against RH bugtracking system](https://bugzilla.redhat.com/show_bug.cgi?id=1687033#c11), issue is still there when using the zsh shell.

Found out that zsh was automatically initializing `MANPATH` variable to an empty value. So the default value `:` should be applied by Modules init scripts if `MANPATH` is undefined or empty.

**Comment by cdorbell2** [comment]
, just a note on this.
the setup of : to the MANPATH can generate a side effect into a nfs automount environment. 
by default the MANPATH is empty , and after the module setup the ":" appear at the end of the MANPATH. but this generate many fault in the automount ( .. key "man" not found in map source(s). ... ).
my workaround is to append a value into the etc/rc.

**Comment by xdelaruelle** [comment]
Could you elaborate on the link between the `MANPATH` variable set to `:` and the automount sub-system ? Errors are obtained when `man` command is used or in another situation ?

**Comment by cdorbell2** [comment]
yes with the man command , but the autoumount error generate a cascading effect on the mount of the other mounts  ( need 3sec for access) .

**Comment by xdelaruelle** [comment]
I assume `man` try to access the regular man paths to search for man pages. What is the situation, if `man` is called but `MANPATH` variable is purely unset ?

In both situations, `MANPATH` not set (1) or set to `:` (2), what is the result of the `manpath` command ?

**Comment by cdorbell2** [comment]
MANPATH not set : 
-bash-4.2$ echo $MANPATH

-bash-4.2$ manpath
/usr/local/man:/usr/local/share/man:/usr/share/man/overrides:/usr/share/man

MANPATH set 
-bash-4.2$ export MANPATH=:
-bash-4.2$ manpath
manpath: warning: $MANPATH set, prepending /etc/man_db.conf
/usr/local/man:/usr/local/share/man:/usr/share/man/overrides:/usr/share/man:

and if i source the module manually  with a MANPATH not set.
-bash-4.2$ source /tools/modules/4.5.0/Modules/init/bash
-bash-4.2$ echo $MANPATH
:
-bash-4.2$ manpath
manpath: warning: $MANPATH set, prepending /etc/man_db.conf
/tools/modules/4.5.0/Modules/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man/overrides:/usr/share/man:

now my workaround is to include "append-path MANPATH /usr/share/man" into my "/tools/modules/4.5.0/Modules/etc/rc"
-bash-4.2$ source /tools/modules/4.5.0/Modules/init/bash
-bash-4.2$ echo $MANPATH
/tools/modules/4.5.0/Modules/share/man:/usr/share/man
-bash-4.2$ manpath
manpath: warning: $MANPATH set, ignoring /etc/man_db.conf
/tools/modules/4.5.0/Modules/share/man:/usr/share/man

 it's not clean , i prefer keep a MANPATH empty without a ":". it's reason of my point .
and the issue in the automount is bonus effect.
