### ISSUE TITLE
Emacs settings for contributions

### ISSUE THREAD

**Issue by nanobowers** [cea-hpc/modules#233]
I have put together emacs settings that comply with the Tcl coding conventions: indentation-level=3, spaces and not tabs, highlighting if 78 characters / line is exceeded.

If you are interested in the contribution, is the CONTRIBUTING.rst the appropriate place to add these settings?

**Comment by xdelaruelle** [comment]
Thanks for that.

Maybe some of the parameters could also be added at the end of the `modulecmd.tcl` script ? Like done for `vim` with the `# vim:set tabstop=3 shiftwidth=3 expandtab autoindent:` line

**Comment by xdelaruelle** [comment]
@nanobowers Feel free to reopen the issue if you want to pursue the work with Emacs-specific directives added at the end of `modulecmd.tcl` script.

**Comment by nanobowers** [comment]
I did end up finding out how to do what you suggested, and while it worked, the way Emacs handles it may be annoying for some users.

To be specific, if I add directives to the modulecmd.tcl file, then the first time a user opens it, it will "pop-up" a dialog with the question (see below).  If a user selects "!", then some data will be written to the user's ~/.emacs file.  If a user does not want these features and chooses either "y" or "n", then the settings will be applied, but the user will get this message **every time they open this file**.  Thus if a user does not want these customizations or does not wish to alter their .emacs startup file, then they will get an annoying message.  For now I will abandon plans to add it to the file, due to this inconvenience.

<pre>
<span style="background-color:#D3D7CF"><font color="#303030">-UUU:----F1  </font></span><span style="background-color:#D3D7CF"><font color="#303030"><b>*scratch*   </b></font></span><span style="background-color:#D3D7CF"><font color="#303030">   All L1     (Lisp Interaction ElDoc) ------------------------------------------------------------------------------</font></span>
The local variables list in modulecmd.tcl
contains values that may not be safe (*).

Do you want to apply it?  You can type
y  -- to apply the local variables list.
n  -- to ignore the local variables list.
!  -- to apply the local variables list, and permanently mark these
      values (*) as safe (in the future, they will be set automatically.)

  * eval : (setq indent-tabs-mode nil)
  * eval : (setq tcl-indent-level 3)
  * eval : (setq tcl-continued-indent-level 3)
  * eval : (font-lock-add-keywords nil (quote ((&quot;^[^\n]\\{79\\}\\(.*\\)$&quot; 1 font-lock-warning-face prepend))))
</pre>
