### ISSUE TITLE
issue when reloading dependent module should fail whole unload/load process

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#241]
During the unload of a module, if the reload of one of its dependent (by the dependent reload mechanism) fails at either the unload or load stage currently this module stays loaded and the dependent reload process continues with next dependent module to reload, then the whole unload or load process continues with main module unload and other automated mechanisms.

When the reload of a dependent module fails, the whole unload or load process should be aborted to guaranty that resulting environment is consistent. Exception made if the force mode is enabled. In this case failing module stays loaded (and is not reloaded) and Dependent Reload mechanism continues with next module to reload, then the whole unload or load process continues.

When the dependent reload mechanism is triggered during a switch command, force mode is applied to the load phase of the mechanism since we are trying to reload the dependent modules of switched-off module. Switch action does not guaranty to find all dependent modules still loaded at the end of the switch process (switched-on module may be incompatible with these modules dependent of switched-off module).

**Comment by JanisSharma** [comment]
if 'myModule' in sys.modules:
del sys.modules["myModule"]

Full Source At [Here](https://icetutor.com/question/how-do-i-unload-reload-a-module/)
