### ISSUE TITLE
module failing to unload are not reported during a module purge

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#267]
If a loaded module fails to unload during a `module purge` due to a `break` statement, this unload failure is not reported. It may confuse users as no module should be found loaded after a `module purge`.

**Comment by mgsternberg** [comment]
I think handling the *result* of a “break” statement still does not remove the element of surprise for a user.

The concept of surviving “purge” or “unload” looks rather like such modules being *sticky*. Such an attribute needs to be flagged in “module list” output, ideally including when “—terse” is active (for parsing). Come to think about it, I’d say such an attribute might be set-able by a declaration, not a code snippet.
