### ISSUE TITLE
set-alias bug on tcsh

### ISSUE THREAD

**Issue by tboydsto** [cea-hpc/modules#275]
The following no longer works on 4.3.0 for tcsh

`set-alias brokealias {firefox -new-window "http://an.example.web?&param=one"}`

but this does work (removes ?)

`set-alias worksalias {firefox -new-window "http://an.example.web&param=one"}`

Both the above worked in 4.1.0

**Comment by xdelaruelle** [comment]
Does not work since this change 95c97ef5 on csh/tcsh and zsh. bash and ksh seem fine. Affects version 4.1.3 and above (last version released is v4.2.4).
