### ISSUE TITLE
Documentation and how module load / prereq works

### ISSUE THREAD

**Issue by zerothi** [cea-hpc/modules#280]
I have a module `my-mod` looking like:
```bash
prereq a/1.0.0
...
```

In 3.2.10 the behaviour is this:
```bash
$> module load my-mod
my-mod(33):ERROR:151: Module 'my-mod' depends on one of the module(s) 'a/1.0.0'
my-mod(33):ERROR:102: Tcl command execution failed: prereq a/1.0.0
```

however, in 4.2.4 the behaviour is this:
```bash
$> module load my-mod
$> module list
a/1.0.0 mymod
```

In the documentation [here](https://modules.readthedocs.io/en/stable/modulefile.html) under `prereq/conflict` it reads:

> **prereq** and **conflict** control whether or not the *modulefile* will be loaded. The **prereq** command lists *modulefiles* which must have been previously loaded before the current *modulefile* will be loaded.

From the first sentence it seems that `prereq` modules are loaded, but from the second it seems that `prereq` modules *must* be loaded before issuing this load.

Also, [here](https://modules.readthedocs.io/en/stable/diff_v3_v4.html) this difference of `prereq` is not documented.

Is the current 4.2.4 behaviour intended for all future?

**Comment by xdelaruelle** [comment]
A default `4.2.x` installation follows the same principle than `3.2.10` : in case a requirement expressed with a `prereq` or `conflict` statement is not satisfied an error is returned.

In your situation, it seems the[ `auto_handling`](https://modules.readthedocs.io/en/latest/MIGRATING.html#automated-module-handling-mode) feature of Modules 4.2 is enabled by default. So Modules tries to solve automatically the requirement expressed. So in your example, it automatically loads the `a/1.0.0` requirement prior to load `my-mod`.

Normally, when such additional actions are done, a summary message is printed. In your situation nothing is printed on your `module load my-mod`, but maybe a specific setup is done on your site to silent those info messages (which normally help to understand what Modules does behind the stage).

`auto_handling` mechanism could be enabled or disabled with the `MODULES_AUTO_HANDLING` environment variable or the `--auto`/`--no-auto` command-line switches.

**Comment by zerothi** [comment]
Great! Thanks, that was indeed the case! :)
