### ISSUE TITLE
log module command

### ISSUE THREAD

**Issue by cdorbell2** [cea-hpc/modules#283]
Hello
do you known if it is possible to include a function of log each command used ?

the output can be send to a syslog or anything other system of log for permit to see the evolution of usage of each tool (tool and others)

it's a cad view :)

**Comment by xdelaruelle** [comment]
With a `siteconfig.tcl` script file installed in Modules etc directory that overrides the `module` procedure to call the `logger` utility prior performing the module command.

Here is some code snippet as example:

```tcl
# override 'module' procedure to log each call made by user                                              
rename ::module ::__module                                                                               
proc module {command args} {                                                                             
   if {[getEvalModuleStackDepth] == 0} {                                                                 
      exec logger -t module "[get-env USER]: $command [join $args]"                                      
   }                                                                                                     
   return [eval __module "{$command}" $args]                                                                 
}
```

I will let this issue open until I add an example recipe for this use case in the documentation cookbook.

**Comment by cdorbell2** [comment]
Thanks Xavier,
it's very simple to use but it's limited to the first module command.
module workspace : mywork/work1
into " mywork/work1" all information specific to the workspace "path", and all tools that i use .
  module load gnu/gcc
  module load gnu/nedit
when i start a module load mywork/work1 i seen only the module command not the others (nedit , gcc)

**Comment by xdelaruelle** [comment]
Yes the example only log the module command that are typed by user, not those within modulefiles. If you want to see everything, just remove the `if {[getEvalModuleStackDepth] == 0} {` statement to let the `exec logger` call operate in any cases
