### ISSUE TITLE
4.3.0 can't read "::command": no such variable

### ISSUE THREAD

**Issue by wenzler** [cea-hpc/modules#284]
Weird error on all 32bit OS (SLE10,11 RH5,6)- all using tcl 8.6.4
No problem with 4.2.4 or 4.2.5.

```
can't read "::command": no such variable
    while executing
"if {$::command eq {clear}} {
      set ::use_pager 0
   }"
    (procedure "initPager" line 50)
    invoked from within
"initPager"
    (procedure "initErrorReport" line 6)
    invoked from within
"initErrorReport"
    invoked from within
"if {[catch {
   # parse all command-line arguments before doing any action, no output is
   # made during argument parse to wait for potential paging ..."
    (file "/app/vbuild/tools/modulestcl/4.3.0/libexec/modulecmd.tcl" line 9624)

```

**Comment by wenzler** [comment]
[modulecmd.txt](https://github.com/cea-hpc/modules/files/3442272/modulecmd.txt)

**Comment by xdelaruelle** [comment]
I presume that this is the load of the new Tcl envmodules library which is failing here. Have you compiled it on a 64bit OS and then share this build with your 32bit OSes ? It may explain the issue you get. A specific error message should be output anyway in case this library load fail.

**Comment by xdelaruelle** [comment]
In case you share one Modules installation over a wide variety of OSes, I suggest to disable the build of this extra library with the `--disable-libtclenvmodules` option to pass to the `configure` script.

**Comment by wenzler** [comment]
Thanks that solves it! I just didnt get the connection towards this option...
