### ISSUE TITLE
Hooks in siteconfig.tcl to pass variables and procs to modulefile eval context

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#286]
Following [this mailing-list discussion thread](https://sourceforge.net/p/modules/mailman/message/36730249/), it would be nice to have simple hooks to define Tcl variables and procedures from the `siteconfig.tcl` file and make these variables and procedures available in the modulefile evaluation context.

**Comment by nanobowers** [comment]
Is this effectively a duplicate of #285 ?  If not, how does it differ?

**Comment by xdelaruelle** [comment]
Same goal but achieved differently potentially by different people:
* Throught `siteconfig.tcl` a site admin would enable those procs or variables in modulefile evaluation context
* With modulefile commands, a user could achieve same goal to manage his/her modulefiles
