### ISSUE TITLE
/usr/bin/tclsh: Permission denied when running 'less' command

### ISSUE THREAD

**Issue by blueglyph** [cea-hpc/modules#299]
This is a strange one.

**Environment**

- openSUSE Tumbleweed, Linux 5.3.8-1-default
- GNU bash, version 5.0.11(1)-release (x86_64-suse-linux-gnu)
- less 551 (POSIX regular expressions)
- tcl 8.6.9-3.2

**Summary**: after installing Modules, every time I use the 'less' command, I get this error:

`/usr/share/Modules/init/bash: line 37: /usr/bin/tclsh: Permission denied`

**Steps to reproduce**

I tested two ways:

1) Installed 4.1.2-1.7
- sudo zypper in Modules Modules-doc
- sudo ln -s /usr/share/init/profile.sh /etc/profile.d/modules.sh
- sudo restart -r now
- modules avail
=> OK
- less ~/.bashrc (for example)
=> error shown above

2) Downloaded & compiled 4.3.1
- wget https://github.com/cea-hpc/modules/releases/download/v4.3.1/modules-4.3.1.tar.gz
- tar xzf [...]
- cd [...]
- edited configure to have prefix=/usr/share/Modules
- ./configure 
=> OK
- make
- sudo make install
=> OK
- sudo ln -s /usr/share/init/profile.sh /etc/profile.d/modules.sh
- sudo restart -r now
- modules avail
=> OK
- less ~/.bashrc (for example)
=> error shown above

**Other info**

The offending line is that one:

> _mlcode=`${_mlre:-}/usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash autoinit`

If I execute less without a filename (alone, or to show the version), I get no error message.
If I output the user, effective user, path, ..., everything seems fine.
If I comment out this line and restart, the error disappears when executing 'less', although this obviously breaks the Modules configuration.
If I'm executing this bash script directly on the command-line, I get no error.
If I'm removing the file from /etc/profile.d, and sourcing bash from .bashrc, I get the same error whenever I'm using the 'less' command.

Therefore, there seems to be a negative interaction between the /usr/share/Modules/init/bash script and the bash shell initialization under some conditions.

**Comment by xdelaruelle** [comment]
Strange one, indeed. I am not able to reproduce on a tumbleweed container.

However from what you describe I think you hit the issue anytime a bash script is ran not only when running `less` (my guess is that error is obtained when the `lessopen.sh` script is ran by `less` binary.

Could you try to run a bash script and tell if you also get the error.
```
$ cat >test.sh <<EOF
#!/bin/bash
echo foo
EOF
$ chmod +x test.sh
$ ./test.sh
```

Could you also check if the error is obtained by directly running the `lessopen.sh` script:
 ```
$ lessopen.sh ~/.bashrc
```

When Modules is initialized during shell profile initialization, it sets ENV and BASH_ENV variables so anytime a bash shell script is run it sources `/usr/share/Modules/init/bash`.

Still need to understand why the `/usr/share/Modules/init/bash` script fails under these conditions but not when initializing shell session.

Do you have some bash-specific (or other shell-kind specific) setup (environment variables, commands in bashrc or bash_profile, etc)?

**Comment by blueglyph** [comment]
Hi Xavier,

Thanks for your reply!

I don't have this error with anything else than 'less', as far as I can
tell, running your example bash script went without any error. My .bashrc
only sets prompt variables, and my .profile only reads the /etc/profile.
There is no other specific start-up script.

Running lessopen.sh produces the same error as with running 'less'.

If I output ENV and BASH_ENV in the bash script (I can echo variables, but
it will refuse to execute any binary with the same 'Permission denied'
error), I get:

ENV=/usr/share/Modules/init/profile.sh
BASH_ENV=/usr/share/Modules/init/bash


I just installed a new openSUSE
(openSUSE-Tumbleweed-DVD-x86_64-Snapshot20191011-Media.iso) in VirtualBox,
and updated.

Then I did the following:


$ *sudo zypper in Modules*
[...]
Checking for file conflicts:
..........................................................................................................................................[done]
(1/2) Installing: Modules-doc-4.1.2-1.7.noarch
........................................................................................................................[done]
(2/2) Installing: Modules-4.1.2-1.7.x86_64
............................................................................................................................[done]

- added this line in my .bashrc, so it looks like this (except the comments
that I'm not copying here):

*source /usr/share/Modules/init/profile.sh*

test -s ~/.alias && . ~/.alias || true


- opened a new terminal and tested:

$ *module avail*
----------------------------------------------------------------------------
/usr/share/modules
-----------------------------------------------------------------------------
dot  module-git  module-info  modules  null  use.own
$* less ~/.bashrc*
/usr/share/Modules/init/bash: line 36: /usr/bin/tclsh: Permission denied


It's not the latest version of Modules, but the error is there too.

Not sure what I did wrong, but I had this on a real machine, installed
recently, on a VB installed right now, and on another one which I'm using
to test things before doing them on the real system. In all cases, I have
the same problem. I haven't tried on other distros.

**Comment by blueglyph** [comment]
Sorry for the poor formatting, but I first replied by email, and it doesn't seem recoverable, markdown is just ignored...

**Comment by xdelaruelle** [comment]
I am now able to reproduce this issue from a VM installation of Tumbleweed.

The error is generated by `AppArmor` which denies `lessopen.sh` to run `/usr/bin/tclsh8.6`. You can find evidence in `/var/log/audit/audit.log`:
```
$ sudo grep 'profile="/usr/bin/lessopen.sh"' /var/log/audit/audit.log
```

To solve this issue and make AppArmor happy the `set_shell_startup` option should be disabled. By disabling this option, `ENV` and `BASH_ENV` environment variables are not defined by Modules during its initialization to ensure it will stay defined in non-interactive subshell context.

`set_shell_startup` option can be disabled starting version 4.3 of Modules by setting `MODULES_SET_SHELL_STARTUP` variable to 0 prior Modules initialization. So I suggest you edit your `~/.bashrc` file the following way:

```
export MODULES_SET_SHELL_STARTUP=0
source /usr/share/Modules/init/profile.sh
test -s ~/.alias && . ~/.alias || true
```

**Comment by blueglyph** [comment]
Thanks a lot, that solved the problem!
