### ISSUE TITLE
module load overrides Tcl auto_path

### ISSUE THREAD

**Issue by sjalloq** [cea-hpc/modules#308]
Hi,

module version is 3.2.10

I'm trying to debug an issue with the auto_path variable being overwritten when 'module load'ing.  The module file in question has two setenv commands and a prepend-path.  Is there something going on behind this that sets up the Tcl auto_path variable?

What I'm seeing is that running tkdiff with a specific module loaded fails due to the auto_path missing the Tk8.5 libs.  I can run a Tcl script to print the variable before and after loading and it seems to be modified to library paths within the tool installation I'm loading.

The module file is:
```
setenv MGLS_LICENSE_FILE 1717@192.168.1.110
setenv CALIBRE_HOME /home/cad/mentor/installs/aoi_cal_2019.3_15.11/aoi_cal_2019.3_15.11
prepend-path PATH $env(CALIBRE_HOME)/bin
```

and the output of printing auto_path before and after follows:
```
/usr/share/tcl8.5 /usr/lib64/tcl8.5 /usr/lib64/tk8.5 /usr/share/tk8.5
```

```
home/cad/mentor/installs/aoi_cal_2019.3_15.11/aoi_cal_2019.3_15.11/pkgs/icv_comp/8.6/lib/tcl /home/cad/mentor/installs/aoi_cal_2019.3_15.11/aoi_cal_2019.3_15.11/pkgs/icv_comp/8.6/lib /home/cad/mentor/installs/aoi_cal_2019.3_15.11/aoi_cal_2019.3_15.11/pkgs/icv_comp/8.6/lib/tk /home/cad/mentor/installs/aoi_cal_2019.3_15.11/aoi_cal_2019.3_15.11/pkgs/icv_comp/8.6/lib/tk/ttk
```

**Comment by xdelaruelle** [comment]
Hi,

I wonder if there is some Tcl installation bundled within `/home/cad/mentor/installs/aoi_cal_2019.3_15.11/aoi_cal_2019.3_15.11`. Could you check if there is a `tclsh` binary in the directory added to path for instance.

Could you also check which `tclsh` is called when you run the Tc script to print the variable before and after loading.

**Comment by sjalloq** [comment]
Hi and thanks for the help.  Yes, there's a tclsh in the directory added to PATH for that modulefile.  And yes, as you suspected, different tclsh's are used before and after loading the module.

So does that just mean that these are mutually exclusive tools?

**Comment by xdelaruelle** [comment]
Yes. It means that once your modulefile is loaded another Tcl installation (v8.6) takes the lead over the default Tcl installation on your system (8.5). So tools strictly bound to this 8.5 version do not work anymore once the other Tcl installation (8.6) is activated.

**Comment by cdorbell2** [comment]
we have the same problem with other tool ( like synopsys virtualizer)  that source the LD_LIBRARY_PATH. and generate a problem with the local tclsh of the system. i agree that is specific to the EDA  but the default version of tcl on rh7 is 8.5 
do you think if it's possible to unset the LD_LIBRARY_PATH value during the module command ? 
or via the shebang ?

**Comment by xdelaruelle** [comment]
`module` can protect itself from such issue with the [quarantine mechanism](https://modules.readthedocs.io/en/latest/module.html#envvar-MODULES_RUN_QUARANTINE). So by setting `MODULES_RUN_QUARANTINE` variable to `LD_LIBRARY_PATH`, for instance:

    $ module config run_quarantine LD_LIBRARY_PATH
or

    $ export MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH

it could stick to the Tcl installation coming from the OS distribution.

**Comment by cdorbell2** [comment]
ok thanks,
