### ISSUE TITLE
createmodule.sh / createmodule.py don't work at all.

### ISSUE THREAD

**Issue by hongyi-zhao** [cea-hpc/modules#309]
Hi,

The following scripts shipped with the repo:

createmodule.sh / createmodule.py

They were written many years ago,  it seems there are some bugs in them.

See the following tests:

```
modules.git/script$ ./createmodule.py /opt/intel/vtune_profiler/amplxe-vars.sh intel64
WARNING: initscript sent the following to stderr:
/bin/sh: 3: /opt/intel/vtune_profiler/amplxe-vars.sh: Bad substitution

ERROR: Could not parse output line:
Copyright (C) 2009-2019 Intel Corporation. All rights reserved.
```

**Comment by nanobowers** [comment]
@hongyi-zhao AFAICT this script works by evaluating your shell script in a new shell and evaluating differences.  I found that 'echo' statements (or other print statements) in the shell script can cause the `ERROR: Could not parse output line:` output.  You might wish to comment them out as a workaround.

**Comment by hongyi-zhao** [comment]
I've solved this issue and do some enhancing/fixes on this script now.

There are some others similar scripts for the same purpose, say, the following ones:

https://github.com/dcblack/env2-code
https://lmod.readthedocs.io/en/latest/260_sh_to_modulefile.html

If I've completed the work on these scripts, I would like to put it on my git repo. 
BTW, the the shell version for this type of job is inefficient, all of the others similar script are written by some other script languages than shell/bash, say, tcl/lua/python.

It seems the latter ones are more appropriate for this type of job.

Regards

**Comment by xdelaruelle** [comment]
Job could be achieved also by shell version (`createmodule.sh`). Here the script suffers of an issue if there is a shell function defined in the environment. With this issue fixed, it could operate as well as implementation in more elaborated languages.

This put aside, the main issue described here is the inability of both `createmodule.sh` and `createmodule.py` to handle script outputting text on stdout. Inhibiting stdout for the evaluation of the script passed as argument will solve the issue.

**Comment by hongyi-zhao** [comment]
> Job could be achieved also by shell version (`createmodule.sh`). Here the script suffers of an issue if there is a shell function defined in the environment. With this issue fixed, it could operate as well as implementation in more elaborated languages.
> 
> This put aside, the main issue described here is the inability of both `createmodule.sh` and `createmodule.py` to handle script outputting text on stdout. Inhibiting stdout for the evaluation of the script passed as argument will solve the issue.

Then what's method should be used for finding the diff before and after of sourcing the script?

Regards

**Comment by xdelaruelle** [comment]
> Then what's method should be used for finding the diff before and after of sourcing the script?

Checking `env` before script source, putting that result in an array, then source script and after that check `env` again and put that in another array. Diff the two arrays to get the environment diff. This is what `createmodule.sh` and `createmodule.py` do.

Regards

**Comment by hongyi-zhao** [comment]
Yes, this is just the things already done the scripts, but this don't deal with the  shell function issue discussed here.

I use the following revised function to filt out the shell functions:

```
#Will print out array assignment list
printenvarray () {

  env | while read x
  do
    key=${x%%=*}

    # Filter out functions, they cannot be manipulated at present:
    # https://www.networkworld.com/article/2693361/unix-tip-using-bash-s-regular-expressions.html
    if [[ "$key" =~ ^BASH_FUNC_ ]]; then continue; fi
    
    value=`printenv "$key"`
    if [ $? -eq 0 ]
    then
      echo [$key]="'$value'"
    fi
  done
}
```

Regards

**Comment by xdelaruelle** [comment]
In 1ef61d6e7729920e37422f5c2bf7769faf954209, I have applied the methodology used in `createmodule.py` to `createmodule.sh`.

**Comment by hongyi-zhao** [comment]
This is similar the trick I used, but yours seems more good to do that, but it can be simplified into the following just as I've posted:
    
```
   if [[ "$x" =~ '() {' ]]; then
      continue
    fi
```

Another notes, it seems this don't mergered into the master?

**Comment by xdelaruelle** [comment]
1ef61d6 is merged into master.

A skip flag is mandatory to exclude the full function definition, not only its header line, as the while loop treats output from `env` command line by line.

**Comment by hongyi-zhao** [comment]
See my comments here:
https://github.com/cea-hpc/modules/commit/985aa885907c53495bec0f76d4d66ca135681d4f

**Comment by xdelaruelle** [comment]
Feel free to send a pull request for your code change proposal. Here are also some generic guidelines:
* an improvement to the `createmodule` ability should be provided for both `createmodule.sh` and `createmodule.py`
* these scripts should not rely on additional external tools, not to introduce additional external dependencies
* users should know an error occurred on the evaluated script to understand something failed somewhere (not to thing everything worked as expected)

**Comment by hongyi-zhao** [comment]
The touch ups I posted don't meet these requirements.

**Comment by hongyi-zhao** [comment]
> Feel free to send a pull request for your code change proposal. Here are also some generic guidelines:
> 
>     * an improvement to the `createmodule` ability should be provided for both `createmodule.sh` and `createmodule.py`

Some ideas maybe easily done in python, while it may be difficult or impossible for the same idea implemented in shell. 


> 
>     * these scripts should not rely on additional external tools, not to introduce additional external dependencies

What do you mean by saying ``additional external tools''?  The original shell script relies on sort, is this in the range of  ``additional external tools'' mentioned by you?

If not, I think that all of the standard *nix tools, say sed/awk, shouldn't be considered as ``additional external tools'' too.



> 
>     * users should know an error occurred on the evaluated script to understand something failed somewhere (not to thing everything worked as expected)

**Comment by xdelaruelle** [comment]
> What do you mean by saying`` ``additional external tools'' ``? The original shell script relies on sort, is this in the range of ``additional external tools'' mentioned by you?
> 
> If not, I think that all of the standard *nix tools, say sed/awk, shouldn't be considered as`` ``additional external tools'' `` too.

I meant that if the script does not currently relies on `awk` it should not rely on that tool in the future, so as it already relies on `sed`, using `sed` should be preferred. Also such scripts should rely as much as possible on the features provided by their internal shell interpreter rather relying on external tool.

On a general note, Modules is used on Unix systems other than Linux (OS X, FreeBSD, Solaris) and such tools that may be considered basic on Linux like `grep`, `sed` and `awk` have different flavors on these other Unix systems (they support a different set of options and have different behaviors by default). Using less external tools reduces overall complexity.

**Comment by hongyi-zhao** [comment]
> > What do you mean by saying` `additional external tools'' `? The original shell script relies on sort, is this in the range of `additional external tools'' mentioned by you?
> > If not, I think that all of the standard *nix tools, say sed/awk, shouldn't be considered as` `additional external tools'' `` too.
> 
> I meant that if the script does not currently relies on `awk` it should not rely on that tool in the future, so as it already relies on `sed`, using `sed` should be preferred. Also such scripts should rely as much as possible on the features provided by their internal shell interpreter rather relying on external tool.
> 
> On a general note, Modules is used on Unix systems other than Linux (OS X, FreeBSD, Solaris) and such tools that may be considered basic on Linux like `grep`, `sed` and `awk` have different flavors on these other Unix systems (they support a different set of options and have different behaviors by default). Using less external tools reduces overall complexity.

Modules-like tools are mainly used on hpc-based supercomputers.  Nowadays, the Linux is dominate in the hpc domain.  You can see this from the os'es list suported by intel's parallel studio cluster edition.

 On the other hand, both linux and unix are conform to the posix standard.  Most tools used under linux can also easily obtained under unix and vice versa.

Further more, just as I've mentioned before, use shell script to do this type of job is not a good idea. 

Just my point of view.

Regards

**Comment by xdelaruelle** [comment]
Thanks for sharing your points of view. Indeed Modules usage is not limited to the HPC use case.

Regards
