### ISSUE TITLE
Support for NO_COLOR

### ISSUE THREAD

**Issue by cmarqu** [cea-hpc/modules#310]
There is a "competing" initiative to the ``CLICOLOR*`` variables implemented in #279:
https://no-color.org/, suggesting the variable ``NO_COLOR``. Maybe modules should honor it too.

**Comment by xdelaruelle** [comment]
It reminds me of [how standards proliferate](https://imgs.xkcd.com/comics/standards.png). Joke aside, there is no problem to also honor this `NO_COLOR` variable.

Would you try a pull request for that? Work should be quite straightforward, based on code done for `CLICOLOR` (+manpage update, + few tests cases in `testsuite/modules.00-init/140-color.exp`)
