### ISSUE TITLE
module version using "default" as the name

### ISSUE THREAD

**Issue by hpcpony** [cea-hpc/modules#313]
not sure if this is a bug or just expected (yet awkward) behavior but:

>[hpcpony]$ module avail play
>------------ /home/hpcpony/local/modulefiles -------------
>play/default   play/default_x
>[hpcpony]$ module list
>No Modulefiles Currently Loaded.
>[hpcpony]$ module load play/default
>[hpcpony]$ module list
>Currently Loaded Modulefiles:
>  1) play/default_x

Note that asking for "default" resulted in "default_x" being loaded. Using something other that "default" is fine.

We're stuck with old version 3.2.10 but I thought I'd mention this anyway.

**Comment by xdelaruelle** [comment]
I can reproduce the behavior you get on old version 3.2 and it seems to be a bug.

You should consider upgrading to Modules 4, which behaves more appropriately:

```
$ module -V
Modules Release 4.4.1 (2020-01-03)
$ module av play
---------- /path/to/modulefiles ----------
play/default  play/default_x  
$ module load play/default
$ module list
Currently Loaded Modulefiles:
 1) play/default
```

**Comment by hpcpony** [comment]
Thanks.  I'm kinda stuck with 3.2.10 and it's beyond my control (unless I want to change jobs ;^)) but it's good to document.  My work around will just be to avoid naming things "default".  Just for completeness I later noticed it's a little broader then I had realized:

>[hpcpony]$ module avail play
>---------- /home/hpcpony/local/modulefiles -----------------------------------------------------------
>play/default   play/default_x play/test
>[hpcpony]$ module load default
>[hpcpony]$ module list
>Currently Loaded Modulefiles:
>  1) ./play/test

**Comment by xdelaruelle** [comment]
Thanks for these information. Avoiding naming things *default*, seems a good workaround, as *default* value is not correctly handled as you demonstrated.
