### ISSUE TITLE
Python API for environment-modules

### ISSUE THREAD

**Issue by shahzebsiddiqui** [cea-hpc/modules#324]
@xdelaruelle

I recently created a Python API for Lmod called **lmodule** see https://github.com/HPC-buildtest/lmodule or docs: https://lmodule.readthedocs.io/en/latest/index.html

If this would be of interest, it could be easy to have support for environment-modules. My thought are it would be a separate project since **lmodule** has three classes, two of them won't apply since Lmod uses Spider.

I didn't want to create an issue but rather email since i couldn't find any detail this is the only way to get hold of you.

**Comment by xdelaruelle** [comment]
Thanks for this information and proposal.

I wonder how does this compare to existing Python interfaces like:

* the basic one shipped in the project
```
import os
exec(open('/usr/share/Modules/init/python.py').read())
module('load', 'modulefile', 'modulefile', '...')
```
* or more elaborate interface like https://github.com/ben-albrecht/environmentmodules

**Comment by shahzebsiddiqui** [comment]
So i briefly looked at https://github.com/ben-albrecht/environmentmodules, so first off I was not aware of a python interface for Lmod and found out there was one, seems like same for environment-modules. There were specific things I was trying to solve related to buildtest. A few of them are the following 

- Provide a YAML schema to specify modules that can **correctly load modules** with buildtest when generating shell-scripts. 
- Feature to support single test with all versions of a module. See few examples not yet implemented https://github.com/HPC-buildtest/buildtest-framework/wiki/Yaml-Schema-Draft. The idea is a user can have a test for lets say ``GCCcore/6.4.0`` so they should be able to test it for all module versions in ``GCCcore``.  
- Avoid hard-coding site-specific modules in YAML file because that breaks portability. 
- Ultimately there is no tool to automate ``module load`` for entire software stack. The``ModuleLoadTest``class can perform and verify all modules by one or more tree. This by far was the motivation in quickly testing an entire SW stack, this is meant to run with CI tool so whenever new modules are installed we can trigger a test all modules.  
- The ``Spider`` class works well for SysAdmin or end-users to query all modules, or modules by fname. Note that Spider is able to get updated fname modules especially in the case of spack modules with hash. If System Admin or user decide to change spack module configuration with different hash length it will break existing scripts. 


I have to add in docs a section about how ``lmodule`` differs from python interface and what it's trying to solve. Also add few practical use-case examples.

All the module features were part of buildtest see https://buildtest.readthedocs.io/en/latest/module_operation.html but we refactored the code and realized that all the module features could be in separate project. Also we wanted to leverage the API to get the module command (``get_command``) or collection (``get_collection``) because we wanted users to have ability to build tests with modules and user collections.

**Comment by xdelaruelle** [comment]
Thanks for these informations.

If you also want to add support for *Modules* in *lmodule*, please be aware that the Python interface of Modules produces a `module` function that returns values that you can directly use in the calling Python script (boolean or string):

```python
>>> import os
>>> exec(open('/usr/share/Modules/init/python.py').read())
>>> module('is-avail', 'foo')
True
>>> module('is-avail', 'unknown')
False
>>> module('load', 'foo')
True
>>> module('info-loaded', 'foo')
'foo/2'
>>> 
```

By the way, this applies to all languages supported (Tcl, Perl, Python, Ruby, CMake and R).

I am closing this issue, as I do not see what can be done from the Modules side. I wish you good luck for your starting project. You could find my email address on [the github project main page](https://github.com/cea-hpc/modules#authors) if you need to contact me directly.
