### ISSUE TITLE
fish 3.1.0, module init error

### ISSUE THREAD

**Issue by ksmith0** [cea-hpc/modules#325]
When sourcing environment modules 4.3.0 on fish 3.1.0 the following error is given:
```
- (line 18): Expected a string, but instead found a '&'
   _module_raw $argv ^&1
                      ^
from sourcing file -
        called on line 21 of file /usr/share/Modules/init/fish
from sourcing file /usr/share/Modules/init/fish
        called on line 1 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
        called during startup
source: Error while reading file “<stdin>”
```

This worked without issue on fish 3.0.2, it seems that something has changed.

**Comment by ksmith0** [comment]
It seems `^` has been deprecated and `2>` should be used instead:
https://github.com/fish-shell/fish-shell/issues/110#issuecomment-481226665

**Comment by xdelaruelle** [comment]
Thanks for this issue report.

`2>` seems supported since a lot time so it seems safe to replace `^` by `2>` even for old fish versions.
