### ISSUE TITLE
weird bug between help and first time .modulerc use?

### ISSUE THREAD

**Issue by hpcpony** [cea-hpc/modules#335]
This is mostly just annoying, but I'd be curious if there is a work around.  I'm stuck with 3.2.10.

The weirdness is that if I do a 'help' before I load any module, I get a "setenv MODULEPATH ...." line in the help output (I'm assuming this is occurring because of the .modulerc 'use'.

```
[hpcpony ~]$ module --version
VERSION=3.2.10
DATE=2012-12-21
...
TCL_VERSION="8.5"
TCL_PATCH_LEVEL="8.5.13"
...

[hpcpony ~]$ cat .modulerc
#%Module
module use /home/hpcpony/local/modulefiles

[hpcpony ~]$ cat local/modulefiles/bug/help
#%Modules

proc ModulesHelp {} {
  puts stderr "help message"
}

[hpcpony ~]$ module help bug/help

----------- Module Specific Help for 'bug/help' -------------------

help message
setenv MODULEPATH /home/hpcpony/local/modulefiles:/usr/public/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles ;[hpcpony ~]$ 

[hpcpony ~]$ /usr/bin/modulecmd tcsh help bug/help

----------- Module Specific Help for 'bug/help' -------------------

help message
setenv MODULEPATH /home/hpcpony/local/modulefiles:/usr/public/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles ;[hpcpony ~]$ 

[hpcpony ~]$ module load bug/help

[hpcpony ~]$ module help bug/help

----------- Module Specific Help for 'bug/help' -------------------

help message
```
Thoughts?

**Comment by xdelaruelle** [comment]
For the record, this issue does not exist on newer versions of Modules (v4+). Now let see what workaround can be found on Modules version 3.2.

`~/.modulerc` file is evaluated every time a `module` command is issued. The main goal of this file is to define symbolic versions or module aliases.

You should preferably set the modulepath once when your shell session initializes (in one of the rc file of your shell, like ~/.bashrc for Bash shell or ~/.tcshrc for Tcsh).

**Comment by hpcpony** [comment]
Thanks.  We use .modulerc to script a bunch of stuff that sets up the right module paths based on the system/host and user identity.  It's been nice to localize it (generically) to .modulerc (rather than adding a lot of code to user's .rc files) but we could embed them in those I suppose.  (Remember I'm limited and can't do anything system-wide; everything I do is per-user so it's a bit awkward).
