### ISSUE TITLE
save the envrionment variables via ssh

### ISSUE THREAD

**Issue by Mon-ius** [cea-hpc/modules#336]
I currently working on the HPC cluster with GPU.

I must load many modules on my sbatch file(slurm). But while I ssh to the requested nodes, I found the module I loaded on my script was lost. So I wonder what's actually module load do?

Add env variables to the current session? How could I keep this? How could I load modules while using remote server-based editors like pycharm or vs-code without a dirty method? How to avoid to load module again while I ssh it again? (I tried added it to .bashrc, .profile, .bash_login, none of them works)

If there is an existed feature? or not?

**Comment by xdelaruelle** [comment]
Wide topic, but I would say that as of today this is mostly a matter of configuration of the HPC cluster you are working on.

The shell commands you put in your batch file have an impact on the shell session the batch scheduler starts for your job on the master node of your compute node allocation. When you connect with SSH to nodes allocated to your job, you end up in a different session.

The `module` command updates the current shell session. To make these changes persist, `module` commands have to be set in the initialization rc files of your shell. So every time a shell is started these commands are run to ensure the environment is at the desired state.

There is a mechanism called [collection](https://modules.readthedocs.io/en/latest/module.html#collections) that gives the ability to save a set of loaded modules and enabled modulepaths as a file and later on restore the environment the collection describes (in a different shell session for instance).

```console
$ module load foo
$ module list
Currently Loaded Modulefiles:
 1) foo/2  
$ module save
$ module saveshow
-------------------------------------------------------------------
/home/user/.module/default:

module use --append /path/to/modulefiles
module load foo

-------------------------------------------------------------------
$ module purge
$ module list
No Modulefiles Currently Loaded.
$ module restore
Loading foo/2
$ module list
Currently Loaded Modulefiles:
 1) foo/2
```

With this mechanism can just put a `module restore` command in your shell initialization script to get your *default* environment back.

Administrator of your HPC cluster could also set this `module restore` command in the initialization script of Modules (global file named `initrc` or `modulerc`, depending on the version of Modules you have) so the collection will be restored when the `module` command initializes by default for everybody (no need for each user to set a `module restore` command in their shell configuration).

But to apply the above suggestions, you should first ensure the `module` command is available (along with the modulefiles) whatever the node you are connecting to and whatever the way you connect (interactive ssh, batch ssh, batch slurm, interactive slurm, ...). Running `module -V` command on all situation will help to clear this off (you should not get a `command not found` error)

**Comment by Mon-ius** [comment]
Hey, I have checked the version is "`3.2.10`". In fact, I would like to know what `module load` really do? If it just simply add some path into the current session?

For example, in my current workflow, I need to call 4 different `module load `command before I started to work. If there is a way to combine them together without the admin permission? I know what you just said the `module restore` command, but there are many useless stuff during the `module load`, I would like to know the real things the command do and pick up things I need.

**Comment by xdelaruelle** [comment]
`module load` evaluates modulefiles designated as argument and render the environment changes described by the modulefiles as shell code applied to the current shell session.

You can combine the 4 `module load` command into a single command, as it accepts multiple modulefiles on the same command:

```consolde
$ module load a b c d
```

`module` is a shell function which calls the `modulecmd` binary and evaluates its output in the current shell session. By running directly this command you could see the environment changes code resulting from modulefile load:

```console
$ /usr/bin/modulecmd bash load a b c d
```
Use `type module` in your shell to know where `modulecmd` lies if not in `/usr/bin`.
