### ISSUE TITLE
when i installed modules slurm can not use moudle cmd

### ISSUE THREAD

**Issue by XueCangQiuYe** [cea-hpc/modules#339]
I use the following cmd to install module
```shell
$ yum install dejagnu libtool gettext gettext-devel tcl-devel -y
$ cd usr/local/
$ git clone https://github.com/cea-hpc/modules.git
$ cd modules
$ ./configure --with-tcl=/usr/lib64  #--modulefilesdir=/etc/modulefiles修改路径
$ make
$ make install
$ cd /usr/local/Modules/init
$ ln -s /usr/local/Modules/init/profile.sh  /etc/profile.d/module.sh
$ ln -s /usr/local/Modules/init/profile.csh  /etc/profile.d/module.csh
$ source /usr/local/Modules/init/bash
```
and create a modulefile
```shell
#%Module1.0#####################################################################
## modules modulefile
module-whatis   "Python 3.8.2"
prepend-path    PATH /allinone/python-3.8.2/bin/
```
and it wroks well

```shell
ml load python/3.8.2
ml list
ml unload python/3.8.2
```

but, when I load modules on my sbatch file(slurm), like:

```shell
#!/bin/sh
#SBATCH -J test

ml load python/3.8.2
python -V
```

got error:`/var/spool/slurmd/job00156/slurm_script: line 4: ml: command not found`

use `srun` got same error:

```shell
[root@cm-wsb-c4m8d200-3 slurm_test]# srun ml ava
slurmstepd: error: execve(): ml: No such file or directory
srun: error: cm-wsb-c8m16d200-1: task 0: Exited with exit code 2
```

How do I use module in Slurm?

**Comment by xdelaruelle** [comment]
The module initialization has not been done in your environment Slurm, so when the sbatch script or the command passed to srun is run `module` or `ml` command has not been defined.

There are different strategies to get things properly initialized, mostly depending on the way shell environment are initialized at your site. Most common solution is to source Modules initialization file in your `~/.bashrc`:

    source /usr/local/Modules/init/bash

**Comment by XueCangQiuYe** [comment]
@xdelaruelle , thanks for your reply.
As you say, I add `source /usr/local/Modules/init/bash` to `~/.bashrc`, but got same error.

**Comment by XueCangQiuYe** [comment]
I have small cluster 1 manager node , 1 compute node , the compute node installed module.
In manager node, i use `srun echo $PATH` and `echo $PATH` get same output.
In my opinion,  `srun echo $PATH` output should be the same as use `echo $PATH` in compute node output.
Even stranger, my compute node installed module and i reboot it, this node status turn idle to down.
