### ISSUE TITLE
How to use module with slurm?

### ISSUE THREAD

**Issue by XueCangQiuYe** [cea-hpc/modules#341]
my slurm version is 20.02.1, I use the following cmd to install module:
```
$ yum install dejagnu libtool gettext gettext-devel tcl-devel -y
$ cd usr/local/
$ git clone https://github.com/cea-hpc/modules.git
$ cd modules
$ ./configure --with-tcl=/usr/lib64  #--modulefilesdir=/etc/modulefiles修改路径
$ make
$ make install
$ cd /usr/local/Modules/init
$ ln -s /usr/local/Modules/init/profile.sh  /etc/profile.d/module.sh
$ ln -s /usr/local/Modules/init/profile.csh  /etc/profile.d/module.csh
$ source /usr/local/Modules/init/bash
```

```console
$ cat path/to/modulepath/module/version
[root@cm-wsb-c4m8d200-4 modules]# cat version.inc
# Release definitions shared across the Makefiles of this project
# run make to generate version.inc

MODULES_RELEASE := 4.5.0
MODULES_BUILD_HASH := $Format:%h$
MODULES_BUILD_REFS := $Format:%D$
MODULES_BUILD_FDATE := $Format:%ci$
MODULES_BUILD :=
MODULES_BUILD_DATE := 2020-04-07
```

I have small cluster, 1 manager node , 1 compute node , the compute node installed module.
it wroks well in compute node
```
ml load python/3.8.2
ml list
ml unload python/3.8.2
```
In manager node, i use `srun ml ava`, got error
```
[root@cm-wsb-c4m8d200-1 local]# srun ml ava
slurmstepd: error: execve(): ml: No such file or directory
srun: error: cm-wsb-c4m8d200-4: task 0: Exited with exit code 2
```
Seam error in sbatch. my batch file is :
```
#!/bin/bash
 
#SBATCH -J test
#SBATCH -o slurm.sh.out

module ava
```
error
```
/var/spool/slurmd/job00078/slurm_script: line 9: module: command not found
```
How do I set environment variables to make the module effective?
This problem has been bothering me for few days, any suggestions would be helpful.
THANKS!!!

**Comment by xdelaruelle** [comment]
At the sbatch script level, Modules initialization script could be sourced at the beginning to declare and initialize the `module` and `ml` command for the rest of the script:

```bash
#!/bin/bash
 
#SBATCH -J test
#SBATCH -o slurm.sh.out
. /usr/local/Modules/init/bash

module ava
```

For a solution that applies to every sbatch script or srun environment, you should look at [SLURM's options to propagate user environment](https://slurm.schedmd.com/faq.html#user_env).

The way you install Modules, when it is initialized on the shell session where you call `srun` or `sbatch`, the `BASH_ENV` variable should be defined and point to the Modules initialization script for bash shell (`/usr/local/Modules/init/bash`). It implies that Modules is installed on the compute node, but also on the node where to call `srun` or `sbatch` to submit jobs. SLURM catches the user environment at the time of job submission and propagate it to the compute nodes to start there the job. `BASH_ENV` will make your bash script shell source the initialization script designated by this variable at bash startup.

[Please use the modules-interest mailing list for questions](https://modules.readthedocs.io/en/stable/CONTRIBUTING.html#support-questions), you will reach a wider audience that could help you with this kind of setup issue.

**Comment by XueCangQiuYe** [comment]
@xdelaruelle THANK YOU A LOT!
sbatch script with `/usr/local/Modules/init/bash` took effect!
But srun still have same error, I will continue to pay attention to this issue.
