### ISSUE TITLE
Set exitcode to 1 on module not found with avail

### ISSUE THREAD

**Issue by L0ric0** [cea-hpc/modules#343]
### Is your feature request related to a problem? Please describe.
when trying to check if a module is available with a script one has to parse the output of the command, which is prone to errors if said output changes in further versions.

### Describe the solution you'd like
set the exit code of `module avail` and the like to 1 if no fitting module was found.

### Describe alternatives you've considered
parsing the output of the command

**Comment by xdelaruelle** [comment]
The [`is-avail`](https://modules.readthedocs.io/en/latest/module.html#subcmd-is-avail) sub-command exist for such scripting purpose.

Here is a small example:

```console
$ module av
----------- /path/to/modulefiles -----------
bar/2.3  foo/1.1.1(default)  foo/1.2.1  foo/1.10  
bar/3.4  foo/1.1.10          foo/1.2.3  
$ module is-avail bar/2.3
$ echo $?
0
$ module is-avail foobar
$ echo $?
1
```

**Comment by L0ric0** [comment]
thanks haden't found this
