### ISSUE TITLE
installation in specified prefix doesn't work, tries to create '/usr/local/Modules'

### ISSUE THREAD

**Issue by boegel** [cea-hpc/modules#348]
### Describe the bug

Installing in a specified prefix fails, because "`make install`" tries to create `/usr/local/Modules`:

```
$ ./configure --prefix /tmp/example
$ make install
...
mkdir -p /usr/local/Modules/libexec
mkdir: cannot create directory ‘/usr/local/Modules’: Permission denied
make: *** [install] Error 1
```

This triggers are `Permission denied` because I'm using a non-admin user account.

### To Reproduce

```console
$ tar xfvz modules-4.5.1.tar.gz
$ cd modules-4.5.1
$ ./configure --prefix /tmp/example
$ make install
...
```

### Expected behavior

Installation to specified prefix works.

### Error and debugging information

```console
$ make install
mkdir -p /usr/local/Modules/libexec
mkdir: cannot create directory ‘/usr/local/Modules’: Permission denied
make: *** [install] Error 1
...
```

### Modules version and configuration

Modules 4.5.1, 4.5.0, 4.4.1

### Additional context

*(none)*

**Comment by boegel** [comment]
I've danced around this issue by replacing all occurences of `/usr/local/Modules` with my preferred prefix in `Makefile.inc` after running `configure`.

**Comment by xdelaruelle** [comment]
Thanks for your detailed report @boegel.

`--prefix` value should be given in the `--arg=value` form. So here there are 2 issues:
* an error should be raised if an unknown argument is used, `./configure` cannot silently ignore it
* `--arg value` form seems commonly used so it should also be supported
