### ISSUE TITLE
Wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by ars-vita** [cea-hpc/modules#357]
Hello,

I have the following error on a linux pc:

```
$ . /eda/Modules/modules-4.5.1/init/bash
ERROR: couldn't load file "/eda/Modules/modules-4.5.1/lib/libtclenvmodules.so": /eda/Modules/modules-4.5.1/lib/libtclenvmodules.so: wrong ELF class: ELFCLASS64
      while executing
  "load [file normalize [getConf tcl_ext_lib]] Envmodules"
  Please report this issue at https://github.com/cea-hpc/modules/issues
```

Could you pleas help me?

Best regards,
Arseniy.

**Comment by xdelaruelle** [comment]
It seems that Modules was built for a 64bit system and you are trying to use this installed version with a 32bit `tclsh`.

You should either install the 64bit version of Tcl on your system or rebuild Modules to make it match your 32bit installation.

Best regards,
Xavier

**Comment by ars-vita** [comment]
That could be the case.
Thank you.

Best regards,
Arseniy.

**Comment by xdelaruelle** [comment]
I would like to add that if you are in a hurry and you cannot perform the required software re-installation. Just removing the lib file (`/eda/Modules/modules-4.5.1/lib/libtclenvmodules.so` in you case) will solve your issue. This library provides optimized functions, but if it is not there fallback functions are directly included in `modulecmd.tcl` script.

**Comment by ars-vita** [comment]
Thank you, Xavier. This is a good hack to know.

Best regards,
Arseniy.
