### ISSUE TITLE
Control module output width

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#359]
The `module` command automatically detects current terminal width and formats its output to completely fill this available space, like for instance when outputting in a column format the list of all available modules.

It may be desirable to limit the terminal width used by this output to a given size and make `module` automatically adapts to fill space up to this limit only.

**Comment by xdelaruelle** [comment]
Implementing this feature leads to introduce:
* module command-line option `-w NUM`/`--width=NUM`
* module configuration option `term_width`
* environment variable `MODULES_TERM_WIDTH`

By default, module configuration option `term_width` will equal to `0` which means that output width will be the full terminal width, currently stored in `term_columns` by `initStateTermColumns` procedure.

When `term_width` configuration will be set to an integer value different than 0, this number will be used as the terminal column number, thus it will became the value set to the `term_columns` state in `initStateTermColumns` procedure.

`term_width` configuration and its default value are defined in `g_config_defs` global array.

Default value can be overridden by the value set in `MODULES_TERM_WIDTH` environment variable. Which in turn can be overridden by the value set via `-w`/`--width` command-line option.

`term_width` configuration and `-w`/`--width` command-line option only accept an integer value:
* a non-integer value set to `-w`/`--width` command-line option will raise a warning and be ignored
* a non-integer value set to `term_width` via `module config` sub-command will raise an error
* a non-integer value set to `term_width` via environment variable `MODULES_TERM_WIDTH` will be silently ignored

Once implemented, the testsuite must be updated to check every aspect:
* of `term_width` configuration set (default, environment variable set, command-line option set)
* definition of environment variable through `module config` sub-command
* bad value injection
* expected effect of different `term_width` values on module command output:
    * avail
    * load with dependency resolution messages
    * display/help

Documentation has to be updated:
* option/environment/config description on module(1) man
* new option/environment in diff doc
* describe new feature in NEWS

**Comment by Anais-G** [comment]
Hi Xavier,
I am interested in implementing this feature and I'm working on it.
