### ISSUE TITLE
Working in msys2/mingw64

### ISSUE THREAD

**Issue by gsal** [cea-hpc/modules#360]
Say, I downloaded the "Windows" / tcl version of modulecmd; and I am interested in using it from within msys2/mingw64 bash shell.

But, there is a problem, even though paths are coming in Linux-style, they turn up DOS-style after executing the module command.  

Here is how `MODULEPATH` changes right after the `module use` command:

```
salazag@md2ysbtc /c/Users/salazag
env | grep MODULE
LOADEDMODULES=
MODULEPATH=/mingw64/share/Modules/modulefiles:/etc/modulefiles
MODULESHOME=/mingw64/share/Modules
salazag@md2ysbtc /c/Users/salazag
module use /c/Programs/gtcodes/modfiles/all
salazag@md2ysbtc /c/Users/salazag
env | grep MODULE
LOADEDMODULES=
MODULEPATH=C:/Programs/gtcodes/modfiles/all;C:\Programs\msys64\mingw64\share\Modules\modulefiles;C:\Programs\msys64\etc\modulefiles
MODULEPATH_modshare=C:/Programs/gtcodes/modfiles/all;1;C:\Programs\msys64\mingw64\share\Modules\modulefiles;1;C:\Programs\msys64\etc\modulefiles;1
MODULESHOME=/mingw64/share/Modules
salazag@md2ysbtc /c/Users/salazag
```

The above does not seem so terrible and hardly detectable.  But, after using the `module add` command, `PATH` is also totally DOS-style to the point that it breaks the bash session and command can no longer be found.

Sample `PATH` coming in:  
&nbsp;&nbsp;&nbsp;&nbsp;`/c/Programs/VSCode/bin:/mingw64/bin:/usr/local/bin:/usr/bin`  
Sample `PATH` after executing `module add`:  
&nbsp;&nbsp;&nbsp;&nbsp;`c:\Programs\VSCode\bin;C:\Programs\msys64\mingw64\bin;C:\Programs\msys64\usr\local\bin:C:\Programs\msys64\usr\bin`  
Needless to say, this breaks the terminal as bash commands can no longer be found. 

This is the case even though I am setting the shell argument to `bash` in the module function (./init/bash file)  
&nbsp;&nbsp;&nbsp;&nbsp;```module() {  eval `/mingw64/bin/modulecmd bash $*\`;  }```

Would support for Linux-style path on the Windows platform be something that can be implemented fairly easily?  
I mean, the entire code seems to be self-contained.

Thanks.

**Comment by xdelaruelle** [comment]
I wonder if in your use case it would not be preferable to install the regular "Unix" version of modules, like it is done on our MSYS2 non-regression test environment:

https://ci.appveyor.com/project/xdelaruelle/modules-a6nha/branch/master/job/hj85nglalas1kb36

The Windows version is made for a usage through the `cmd` shell.

**Comment by gsal** [comment]
O.k., let me try that...

As soon as I try to ./configure, it complains that gmake is not available; but, gmake does not seem to exist for msys, in the first place.  And, the log from the link above seems to indicate the use of cmake, not gmake...how come? how to make that happen?

**Comment by gsal** [comment]
```
salazag@md2ysbtc [[(cdb338b4...)]] /c/Users/salazag/lin2win/modules
./configure --prefix=/c/Programs/gttools/Modules --modulefilesdir=/c/Programs/gttools/Modules/modulefiles
checking for uname... /usr/bin/uname
checking for gmake... not found
ERROR: gmake could not be found
```

**Comment by gsal** [comment]
Never mind...got passed that by changing MSYS to MINGW inside ./configure; now it looks for `make`

**Comment by gsal** [comment]
Another "never mind"; I went ahead and switched to MSYS shell.

Things are not quite working out, though.

This is my `./configure` command:
```
./configure --prefix=/c/Programs/gttools/Modules --modulefilesdir=/c/Programs/gttools/Modules/modulefiles --with-tclsh=/mingw64/bin/tclsh --with-tcl=/mingw64/lib
```

After that, the `make` command complains about not finding `pwd.h`.  Not knowing any better and finding that such file exists under `/usr/include`, I manually add that path to the `CFLAGS` in `./lib/Makefile`.

After that, the `make` command complains about re-definition of `struct flock`...finding it in two places:  
Here:  `/usr/include/machine/types.h`  
And here: `/usr/include/sys/_default_fcntl.h`

Any idea what to try next?

**Comment by xdelaruelle** [comment]
It seems there are some requirement missing to build the elements that need to be compiled. But the build of these elements can be skipped as they are optional. To skip these compilations, add the following options when calling `./configure`:

    --disable-compat-version --disable-libtclenvmodules

**Comment by xdelaruelle** [comment]
> Never mind...got passed that by changing MSYS to MINGW inside ./configure; now it looks for `make`

For the record, this point has been fixed with e325ce43

**Comment by gsal** [comment]
Thanks. 

---

**Modules 4.5.2**

Options:
```
--disable-compat-version --disable-libtclenvmodules
```
helped.  `./configure` worked to completion and even `make` and `make install`.   

But, it does not seem to work for me, or, I am not activating it correctly? 
All I am doing is sourcing ..../Module/init/bash

```
source /c/Programs/spgtools/Modules/init/bash
ERROR: no such variable
      (read trace on "::env(MODULEPATH)")
      invoked from within
  "if {$::env(MODULEPATH) eq {} && $::env(LOADEDMODULES) eq {}} {
        set initrc [expr {[file exists /c/Programs/spgtools/Modules/etc/initrc] ? {/c/Pro..."
      (procedure "cmdModuleAutoinit" line 43)
      invoked from within
  "cmdModuleAutoinit"
      (procedure "module" line 325)
      invoked from within
  "module autoinit"
      ("eval" body line 1)
      invoked from within
  "eval $execcmdlist"
  Please report this issue at https://github.com/cea-hpc/modules/issues
```

Is that all that is required? 

It seems that
`./init/bash` is calling `./libexec/modulecmd.tcl`
In the absence of `MODULEPATH`, file `./libexec/modulecmd.tcl` attempts to call `./etc/modulespath` or `./init/.modulespath`....neither of which exists in the directory where modules was installed.
With `MODULEPATH` still non-existent, the expression `$::env(MODULEPATH) eq {}` fails.


---

**Modules 4.5.3**  does not ./configure

```
./configure .....
    .
    .
    .
--- preparing extension library sources ----------
./configure: line 863: pushd: lib: No such file or directory
autoreconf: 'configure.ac' or 'configure.in' is required`
```

---

e325ce4... ?  
I guess you have not created a formal release in about 9 days.  
Latest release/tag found is 4.5.3

**Comment by xdelaruelle** [comment]
e325ce4 will be included in next release (v4.6.0) that will be soon out.

To investiguate on the error you get with 4.5.2, could you provide me the output of:
* the installation sequence (./configure, make, make install)
* and the debug output of the `source /c/Programs/spgtools/Modules/init/bash` command

Please run the following commands prior calling `source` to enable debug verbosity:

```console
$ set -x
$ export MODULES_VERBOSITY=debug
```

**Comment by gsal** [comment]
Got passed the problem with 4.5.3; I now get the same exact thing with 4.5.3.   Here it is the requested output. 

---

```
$ ./configure --prefix=/c/Programs/spgtools/mods453 --modulefilesdir=/c/Programs/spgtools/mods453/modulefiles --with-tclsh=/mingw64/bin/tclsh --with-tcl=/mingw64/lib --disable-compat-version --disable-libtclenvmodules
checking for uname... /usr/bin/uname
checking for make... /usr/bin/make
checking for sed... /usr/bin/sed
checking for runtest... not found
WARNING: Install `dejagnu' if you want to run the testsuite
checking for manpath... /usr/bin/manpath
checking for /mingw64/bin/tclsh... /mingw64/bin/tclsh
checking for python... /usr/bin/python
checking for ps... /usr/bin/ps
checking for basename... /usr/bin/basename
checking for less... /usr/bin/less
TCLSH = /mingw64/bin/tclsh
PYTHON = /usr/bin/python
SPHINXBUILD = sphinx-build
PS = /usr/bin/ps
BASENAME = /usr/bin/basename
RMDIR_IGN_NON_EMPTY = rmdir
SED_ERE = sed -E
VERSION = 4.5.3
baseprefix = /c/Programs/spgtools/mods453
prefix = /c/Programs/spgtools/mods453
bindir = /c/Programs/spgtools/mods453/bin
libdir = /c/Programs/spgtools/mods453/lib
libexecdir = /c/Programs/spgtools/mods453/libexec
etcdir = /c/Programs/spgtools/mods453/etc
initdir = /c/Programs/spgtools/mods453/init
datarootdir = /c/Programs/spgtools/mods453/share
mandir = /c/Programs/spgtools/mods453/share/man
docdir = /c/Programs/spgtools/mods453/share/doc
vimdatadir = /c/Programs/spgtools/mods453/share/vim/vimfiles
modulefilesdir = /c/Programs/spgtools/mods453/modulefiles
setmanpath = y
appendmanpath = n
setbinpath = y
appendbinpath = n
setdotmodulespath = n
docinstall = y
vimaddons = y
examplemodulefiles = y
builddoc = p
gitworktree = y
usemanpath = y
compatversion = n
EXEEXT =
libtclenvmodules = n
SHLIB_SUFFIX = .dll
versioning = n
silentshdbgsupport = y
setshellstartup = y
quarantinesupport = y
autohandling = n
availindepth = y
implicitdefault = y
extendeddefault = n
moduleshome = /c/Programs/spgtools/mods453
initconfin = initdir
pager = /usr/bin/less
pageropts = -eFKRX
verbosity = normal
color = n
darkbgcolors = hi=1:db=2:se=2:er=91:wa=93:me=95:in=94:mp=1;94:di=94:al=96:sy=95:de=4:cm=92
lightbgcolors = hi=1:db=2:se=2:er=31:wa=33:me=35:in=34:mp=1;34:di=34:al=36:sy=35:de=4:cm=32
termbg = dark
lockedconfigs =
icase = never
unloadmatchorder = returnlast
searchmatch = starts_with
modulepath = /c/Programs/spgtools/mods453/modulefiles
loadedmodules =
quarantinevars =
wa277 = n
advversspec = n
ml = y
windowssupport = n
creating ./Makefile.inc
creating ./site.exp
```

--- 

```
$ make
sed....
.
.
.
make -C init all
.
.
.
mv modulerc modulerc.tmp
sed -e 's|\\$||' modulerc.tmp > modulerc
rm -f modulerc.tmp
.
.
.make[1]: Leaving directory '/c/Users/salazag/lin2win/modules-4.5.3/init'
.
.
.
make -C doc man txt
make[1]: Entering directory '/c/Users/salazag/lin2win/modules-4.5.3/doc'
sed -e 's|@prefix@|/c/Programs/spgtools/mods453|g' -e 's|@libexecdir@|/c/Programs/spgtools/mods453/libexec|g' -e 's|@etcdir@|/c/Programs/spgtools/mods453/etc|g' -e 's|@initdir@|/c/Programs/spgtools/mods453/init|g' -e 's|@modulefilesdir@|/c/Programs/spgtools/mods453/modulefiles|g' -e 's|@MODULES_RELEASE@|4.5.3|g' -e 's|@MODULES_BUILD@||g' -e 's|@MODULES_BUILD_DATE@|2020-08-31|g' build/module.1.in > build/module.1
make[1]: Nothing to be done for 'txt'.
make[1]: Leaving directory '/c/Users/salazag/lin2win/modules-4.5.3/doc'
```

---

```
$ make install
mkdir -p /c/Programs/spgtools/mods453/libexec
mkdir -p /c/Programs/spgtools/mods453/bin
mkdir -p /c/Programs/spgtools/mods453/etc
cp modulecmd.tcl /c/Programs/spgtools/mods453/libexec/
chmod +x /c/Programs/spgtools/mods453/libexec/modulecmd.tcl
cp script/envml /c/Programs/spgtools/mods453/bin/
chmod +x /c/Programs/spgtools/mods453/bin/envml
cp script/add.modules /c/Programs/spgtools/mods453/bin/
chmod +x /c/Programs/spgtools/mods453/bin/add.modules
cp script/createmodule.py /c/Programs/spgtools/mods453/bin/
chmod +x /c/Programs/spgtools/mods453/bin/createmodule.py
cp script/modulecmd /c/Programs/spgtools/mods453/bin/
chmod +x /c/Programs/spgtools/mods453/bin/modulecmd
cp script/mkroot /c/Programs/spgtools/mods453/bin/
chmod +x /c/Programs/spgtools/mods453/bin/mkroot
cp siteconfig.tcl /c/Programs/spgtools/mods453/etc/siteconfig.tcl
mkdir -p /c/Programs/spgtools/mods453/share/doc
cp COPYING.GPLv2 /c/Programs/spgtools/mods453/share/doc/
cp ChangeLog /c/Programs/spgtools/mods453/share/doc/
cp README /c/Programs/spgtools/mods453/share/doc/
mkdir -p /c/Programs/spgtools/mods453/share/vim/vimfiles/ftdetect
mkdir -p /c/Programs/spgtools/mods453/share/vim/vimfiles/ftplugin
mkdir -p /c/Programs/spgtools/mods453/share/vim/vimfiles/syntax
cp  contrib/vim/ftdetect/modulefile.vim  /c/Programs/spgtools/mods453/share/vim/vimfiles/ftdetect
cp  contrib/vim/ftplugin/modulefile.vim  /c/Programs/spgtools/mods453/share/vim/vimfiles/ftplugin
cp  contrib/vim/syntax/modulefile.vim    /c/Programs/spgtools/mods453/share/vim/vimfiles/syntax
make -C init install DESTDIR=
make[1]: Entering directory '/c/Users/salazag/lin2win/modules-4.5.3/init'
mkdir -p /c/Programs/spgtools/mods453/init
mkdir -p /c/Programs/spgtools/mods453/init/ksh-functions
mkdir -p /c/Programs/spgtools/mods453/init/zsh-functions
mkdir -p /c/Programs/spgtools/mods453/modulefiles
cp sh ksh bash zsh profile.sh bash_completion csh tcsh tcsh_completion profile.csh perl.pm python.py ruby.rb lisp tcl fish cmake r.R /c/Programs/spgtools/mods453/init/
cp fish_completion /c/Programs/spgtools/mods453/init/
cp zsh-functions/_module /c/Programs/spgtools/mods453/init/zsh-functions/
cp ksh /c/Programs/spgtools/mods453/init/ksh-functions/module
cp ksh /c/Programs/spgtools/mods453/init/ksh-functions/ml
rm -f /c/Programs/spgtools/mods453/init/ksh-functions/switchml
rm -f /c/Programs/spgtools/mods453/init/.modulespath /c/Programs/spgtools/mods453/init/modulerc
cp -R -P modulerc /c/Programs/spgtools/mods453/init/modulerc
cp ../contrib/modulefiles/dot ../contrib/modulefiles/module-git ../contrib/modulefiles/module-info ../contrib/modulefiles/modules ../contrib/modulefiles/null ../contrib/modulefiles/use.own /c/Programs/spgtools/mods453/modulefiles/
make[1]: Leaving directory '/c/Users/salazag/lin2win/modules-4.5.3/init'
make -C doc install DESTDIR=
make[1]: Entering directory '/c/Users/salazag/lin2win/modules-4.5.3/doc'
mkdir -p /c/Programs/spgtools/mods453/share/man/man1 /c/Programs/spgtools/mods453/share/man/man4
mkdir -p /c/Programs/spgtools/mods453/share/doc
cp build/diff_v3_v4.txt /c/Programs/spgtools/mods453/share/doc/
cp build/MIGRATING.txt /c/Programs/spgtools/mods453/share/doc/
cp build/INSTALL.txt /c/Programs/spgtools/mods453/share/doc/
cp build/INSTALL-win.txt /c/Programs/spgtools/mods453/share/doc/
cp build/NEWS.txt /c/Programs/spgtools/mods453/share/doc/
cp build/CONTRIBUTING.txt /c/Programs/spgtools/mods453/share/doc/
cp example.txt /c/Programs/spgtools/mods453/share/doc/
cp build/module.1 /c/Programs/spgtools/mods453/share/man/man1/
cp build/ml.1 /c/Programs/spgtools/mods453/share/man/man1/
cp build/modulefile.4 /c/Programs/spgtools/mods453/share/man/man4/
make[1]: Leaving directory '/c/Users/salazag/lin2win/modules-4.5.3/doc'

NOTICE: Modules installation is complete.
        Please read the 'Configuration' section in INSTALL guide to learn
        how to adapt your installation and make it fit your needs.
```

---

```
$ set -x
$ export MODULES_VERBOSITY=debug
$ source /c/Programs/spgtools/mods453/init/bash
+ source /c/Programs/spgtools/mods453/init/bash
++ unset _mlshdbg
++ '[' 0 = 1 ']'
++ unset _mlre _mlIFS
++ '[' -n x ']'
++ _mlIFS='
'
++ IFS=' '
++ '[' -n '' ']'
+++ /mingw64/bin/tclsh /c/Programs/spgtools/mods453/libexec/modulecmd.tcl bash autoinit
DEBUG CALLING C:/Programs/spgtools/mods453/libexec/modulecmd.tcl bash autoinit
DEBUG setConf: siteconfig set to '/c/Programs/spgtools/mods453/etc/siteconfig.tcl'
DEBUG setConf: locked_configs set to ''
DEBUG setConf: pager set to '/usr/bin/less -eFKRX'
DEBUG initPager: no pager start (is_tty=0, mod_cmd='autoinit', use_pager=1, asked_use_pager=-, cmd='/usr/bin/less -eFKRX')
DEBUG setConf: verbosity set to 'debug'
DEBUG setConf: term_background set to 'dark'
DEBUG setConf: colors set to 'hi=1:db=2:se=2:er=91:wa=93:me=95:in=94:mp=1;94:di=94:al=96:sy=95:de=4:cm=92'
DEBUG setConf: color set to '0'
DEBUG module: cmd='autoinit', args=''
DEBUG setConf: avail_indepth set to '1'
DEBUG setConf: search_match set to 'starts_with'
DEBUG parseModuleCommandArgs: (show_oneperline=0, show_mtime=0, show_filter=, search_filter=, search_match=starts_with, dump_state=0, otherargs=)
DEBUG runModulerc: running...
DEBUG cmdModuleAutoinit: called.
DEBUG setenv: var='MODULES_CMD', val='C:/Programs/spgtools/mods453/libexec/modulecmd.tcl'
DEBUG unset-env: MODULES_CMD_modshare (internal=1, val=)
DEBUG set-env: MODULES_CMD=C:/Programs/spgtools/mods453/libexec/modulecmd.tcl
DEBUG setenv: var='MODULEPATH', val=''
DEBUG unset-env: MODULEPATH_modshare (internal=1, val=)
DEBUG set-env: MODULEPATH=
DEBUG setenv: var='LOADEDMODULES', val=''
DEBUG unset-env: LOADEDMODULES_modshare (internal=1, val=)
DEBUG set-env: LOADEDMODULES=
DEBUG renderFalse: called.
ERROR: no such variable
      (read trace on "::env(MODULEPATH)")
      invoked from within
  "if {$::env(MODULEPATH) eq {} && $::env(LOADEDMODULES) eq {}} {
        set initrc [expr {[file exists /c/Programs/spgtools/mods453/etc/initrc] ? {/c/Pro..."
      (procedure "cmdModuleAutoinit" line 43)
      invoked from within
  "cmdModuleAutoinit"
      (procedure "module" line 325)
      invoked from within
  "module autoinit"
      ("eval" body line 1)
      invoked from within
  "eval $execcmdlist"
  Please report this issue at https://github.com/cea-hpc/modules/issues
++ _mlcode='test 0 = 1;'
++ _mlret=1
++ '[' -n x ']'
++ IFS='
'
++ unset _mlIFS
++ unset _mlre _mlv _mlrv
++ '[' 1 -eq 0 ']'
++ unset _mlcode _mlret
++ '[' -n '' ']'
++ pwd
```

**Comment by xdelaruelle** [comment]
Thanks for these logs. Now I understand what is going on: environment variable is not defined so `modulecmd.tcl` defines it to an empty string. But on Windows, setting an environment variable to a blank value unset it.

I will work on a fix for 4.6.0.

For the time being, I suggest you add the following lines at the beginning of the `/c/Programs/spgtools/mods453/init/bash` script:

    export LOADEDMODULES=:
    export MODULEPATH=:

**Comment by gsal** [comment]
Went ahead and added those two lines.  Here is a session following that: 

![image](https://user-images.githubusercontent.com/10213896/92604895-0d87e680-f27f-11ea-9b89-c867284c5d2a.png)

**Comment by gsal** [comment]
Hhhmmmm....so much for that. It does not look like all this has gotten me anywhere. 

Given the error reported in the previous post, I went ahead and also included `export _LMFILES_=:` into `./init/bash`.  It helped, I guess.

Starting from the 2nd post, up above, where you recommended the "unix" version of Modules, built in MSYS, etc., I thought I will end up at a point where PATH will be left in POSIX-style; but, apparently, that is not the case and the use of this version of Modules also corrupts the environment by changing PATH around and setting it to DOS-style paths!

```
$ source /c/Programs/spgtools/mods453/init/bash
bash: export: _module_raw: not a function
$ echo $PATH
/c/Programs/spgtools/mods453/bin:/c/Users/salazag/.local/python38/Scripts:/c/Programs/VSCode/bin:/c/Programs/NPP:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Program Files/...
$ module use /c/Programs/spgcodes/modfiles/all
$ echo $PATH
/c/Programs/spgtools/mods453/bin:/c/Users/salazag/.local/python38/Scripts:/c/Programs/VSCode/bin:/c/Programs/NPP:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Program Files/... 
$ module avail
--------------------------------------- C:/Programs/spgcodes/modfiles/all ---------------------------------------
myprog/0.5.0
$ echo $PATH
/c/Programs/spgtools/mods453/bin:/c/Users/salazag/.local/python38/Scripts:/c/Programs/VSCode/bin:/c/Programs/NPP:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Program Files/...
$ module load myprog/0.5.0
$ echo $PATH
C:/Programs/spgcodes/myprog/0.5.0/win10/bin;C:/Programs/spgcodes/myprog/0.5.0/win10;C:\Programs\spgtools\mods453\bin;C:\Users\salazag\.local\python38\Scripts;C:\Programs\VSCode\bin;C:\Programs\NPP;C:\Programs\msys64\mingw64\bin;C:\Programs\msys64\usr\local\bin;C:\Programs\msys64\usr\bin;C:\Programs\msys64\usr\bin;C:\Program Files\...
```
With PATH no longer in POSIX-style, nothing works anymore from the MINGW64/MSYS prompt. 

What gives?

**Comment by xdelaruelle** [comment]
Ok so it seems we are on the wrong track. `module` in itself does not rewrite variable values.

Could you provide details on the way you installed mingw64, msys, bash and tcl. So it will enable me to reproduce your setup in order to reproduce the issue you get.

**Comment by gsal** [comment]
1.- Well, I think you are kind of wrong; I mean, of course module writes variables...that's the whole point of Environment Modules, to modify the environment!

2.- On the flip side, you are also kind of right; some of the changes in the environment would be done via our own modulefiles. So, thanks for the reminder...these changes in `PATH` are my own doing.

Point 1.  
- Of course "module" writes variables. 
- First, initializing modules by sourcing Modules/init/bash creates the following variables: `MODULESHOME`, `LOADEDMODULES`, `MODULEPATH`
- After the command `module use ...`:
    - variable MODULEPATH_modshare is created
    - variable MODULEPATH is extended
- After the command `module load ...`:
    - variable LOADEDMODULES_modshare is created
    - variable LOADEDMODULES is extended

Point 2.
Other variables, certainly `PATH`, would be created/modified via own modulefile, precisely, to be able to use the corresponding program.

My point is, as a user, I would expect paths to remain "platform"-compatible. 
- If I am using module from mingw with POSIX-style paths, I would expect PATH to stay POSIX-style
- If I am using module from DOS with non-POSIX-styel paths, I would expect PATH to stay that way
This, even if it is my own doing via modulefile...after all, changes are being made in a supposedly "platform"-compatible manner via tcl command (module own prepend-path).

After all this investigation, it seems it may come down to the version of tcl being used: 
- mingw-tcl, being a Windows executable, puts out Windows-style paths even if the incoming ones are POSIX-style.
- msys-tcl, on the other side, seems to preserve POSIX-style paths.
Though, I have not actually tested if switching module to use msys-tcl makes it preserve POSIX-style paths.

Anyway, for my own project, I need to figure out how I want to work; but I would like to be able to work in the same manner either in MINGW or DOS...whether I can do this with a single Modules installation or one for each "platform", that's another matter.

**Comment by xdelaruelle** [comment]
> Thanks for these logs. Now I understand what is going on: environment variable is not defined so `modulecmd.tcl` defines it to an empty string. But on Windows, setting an environment variable to a blank value unset it.
> 
> I will work on a fix for 4.6.0.
> 
> For the time being, I suggest you add the following lines at the beginning of the `/c/Programs/spgtools/mods453/init/bash` script:
> 
> ```
> export LOADEDMODULES=:
> export MODULEPATH=:
> ```

ef95c7fb and e7fe066b fix that point and will be included in next release

**Comment by xdelaruelle** [comment]
> 1.- Well, I think you are kind of wrong; I mean, of course module writes variables...that's the whole point of Environment Modules, to modify the environment!

I was not clear in my previous comment. What I meant is that `module` is not made to rewrite existing elements of a path-like variable when adding new path element to it.

I was able to reproduce the issue you describe on MinGW: it seems that when Tcl is installed on MinGW it operates like if running directly on Windows. Fetching PATH environment variable value with `$env(PATH)` returns the Windows-style value of PATH. So `module` cannot operate with such Tcl installation, as the PATH variable will be transformed in Windows style value when a modulefile adds a new element to it.

So I would such that either on MinGW or MSYS, you use the Tcl installation of MSYS to make it operate in a Unix fashion.

If you want to also you `module` in a DOS environment, I would recommend to have a second installation of Modules, based on the Windows dist release.

**Comment by gsal** [comment]
Yeah, that is the trick, to have both Tcl's installed one for MinGW (MSYS/tcl) and one for DOS (MinGW/tcl)...which I do; thus, I am able to support Modules in both MinGW/bash and Windows/cmd with "single" Modules install.

Because to work with MinGW, `PATH` has the following paths and in the order shown:
`PATH=.../msys64/mingw64/bin ; .../msys64/usr/local/bin ; .../msys64/usr/bin ; .../msys64/bin ; $PATH`

A single `modulecmd` tcl script is able to support both shells because:
 - In bash, the file is executed as a command given the shebang line; which I have hard coded with full path to MSYS/tcl; and, 
 - In cmd, the file is passed to the tcl runtime as an argument (ignoring the shebang) and, thus, finding MinGW/tcl first. 

![image](https://user-images.githubusercontent.com/10213896/93164298-2f51f500-f6e7-11ea-93e5-d6208aaf76d1.png)

Now, the questions are:
Does Modules support PowerShell? Or,
Is there already something in PowerShell that I can use instead of Modules?

The reason being that I am not liking `cmd.exe` much. On the one hand, it seems slower than PowerShell; on the other, it does not fully support symbolic links and they behave differently than in Linux, MinGW and PowerShell.

**Comment by xdelaruelle** [comment]
PowerShell is not supported at the moment. #326 covers this feature request. I have given some hints in the ticket to guide anyone willing to work on this development.

**Comment by gsal** [comment]
Anyway, I think this thread has come to an end, since the answer to the initial question was found as indicated 2 posts above.
