### ISSUE TITLE
remove-path does not seem to work

### ISSUE THREAD

**Issue by mfouesneau** [cea-hpc/modules#363]
### Describe the bug
I made a modulefile in which I set PATH with 
```
if { [ module-info mode load ] } {
         prepend-path  PATH             $ANACONDA/bin
}
```
and set the remove with 
```
if { [ module-info mode remove ] } {
         remove-path  PATH             $ANACONDA/bin
}
```

The loading works fine, but unloading does not remove the path as requested.

### To Reproduce

```console
$ module  load anaconda
$ module unload anaconda
```

Is there something wrong with the way I request the remove-path?

**Comment by xdelaruelle** [comment]
modulefile commands like `prepend-path` or `remove-path` have a different behavior whether they are evaluated in a load or an unload mode. `remove-path` has no effect on `unload` mode.

What you want to achieve need to be done only with the following code:

    prepend-path  PATH             $ANACONDA/bin

When loading the corresponding modulefile, the new path will be added. And when unloading this modulefile, the added path will automatically be removed.

**Comment by mfouesneau** [comment]
But the path is not removed when unloading.

**Comment by mfouesneau** [comment]
Ok it seems that it only works if there is no  ```if { [ module-info mode load ] } ``` statement

**Comment by xdelaruelle** [comment]
Yes, if you keep the conditional statement, nothing is done when unloading, as the `prepend-path` command is not processed due to it inclusion in the load statement.

To keep it short : there is no need for conditional statement, the `prepend-path` does the right thing when loading and when unloading.

**Comment by mfouesneau** [comment]
Got it. Thanks.
