### ISSUE TITLE
Backtick is not working in Modules Release Tcl 1.578

### ISSUE THREAD

**Issue by balaramr** [cea-hpc/modules#365]
### Modules version and configuration -- Modules Release Tcl 1.578

```console
$ > module --version
Modules Release Tcl 1.578
$ >
```

### To Reproduce Error and debugging information

```console
$ > vi opensource 
Copyright (C) 2009-2018. All rights reserved.
#%Module

prepend-path	PATH	/opt/opensource/bin
prepend-path	LD_LIBRARY_PATH	/opt/opensource/lib64:
setenv		CURRENT_DIR	`pwd`
```

```console
$ > module load opensource
$ > echo $CURRENT_DIR
`pwd`
$ > 
```

### In direct shell
If we try this directly in shell backtick is working fine. 
```console
$ > setenv  CURRENT_DIR  `pwd`
$ > echo $CURRENT_DIR
/home/john
$ > 
```

### Working -- Modules Release Tcl 3.1.6
Same thing is working in other module version 

```console
$ > module --version
Modules Release Tcl 3.1.6
$ >
```
Working in Module 3.1.6 version

```console
$ > module load opensource
$ > echo $CURRENT_DIR
/home/john
$ > 
```

**Comment by xdelaruelle** [comment]
Backticks are now escaped to be used in environment variable values or in shell alias or shell function definition. This applies to Modules-Tcl but also to newer version of Modules, starting version 4.0.

To achieve the backtick shell mechanism when defining an environment variables, the `exec` Tcl command has to be used:

    setenv		CURRENT_DIR	[exec pwd]

I will clarify this change in the [diff v3 v4](https://modules.readthedocs.io/en/stable/diff_v3_v4.html) document.
