### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by mirkov** [cea-hpc/modules#373]
This is on `https://github.com/cea-hpc/modules/commit/2f40ade03ea5fdf4aa904e91f8b2f37156543713`

The last sentence in section **Transition from v3.2** reads:

`Slights differences may however be noticed in a few use-cases and the migration guide provides details about them.`

The first word `Slights` should be `Slight`.

**Comment by xdelaruelle** [comment]
Thanks for your contribution.
