### ISSUE TITLE
chsh /bin/fish is broken when modules is installed?

### ISSUE THREAD

**Issue by vorburger** [cea-hpc/modules#374]
see https://github.com/fish-shell/fish-shell/issues/7560

Please note that I've absolutely no idea what "Environment Modules" (`cea-hpc/modules`) is - I just seem to have it on Fedora 32, not sure if I got it as a dependency of something.. I've certainly never installed it, but it seem to somehow make it impossible for me to switch shells.

**Comment by vorburger** [comment]
```
❯ rpm -q --whatprovides /usr/share/Modules/init/fish
environment-modules-4.4.1-3.fc32.x86_64

❯ sudo dnf remove environment-modules
[sudo] password for vorburger:Dependencies resolved.
=======================================================================================================================================
 Package                           Architecture         Version                                           Repository              Size
=======================================================================================================================================
Removing:
 environment-modules               x86_64               4.4.1-3.fc32                                      @updates               1.6 MRemoving dependent packages:
 OpenImageIO                       x86_64               2.1.20.0-1.fc32                                   @updates                11 M nomacs                            x86_64               3.16-1.fc32                                       @updates               8.2 M scl-utils                         x86_64               1:2.0.2-13.fc32                                   @fedora                 62 k
Removing unused dependencies:
 coin-or-Cbc                       x86_64               2.10.5-2.fc32                                     @updates               2.4 M
 coin-or-Cgl                       x86_64               0.60.3-1.fc32                                     @fedora                1.1 M coin-or-Clp                       x86_64               1.17.5-1.fc32                                     @fedora                2.5 M
 mp                                x86_64               3.1.0-26.20200215git71c21a5.fc32                  @fedora                3.6 M opencv-contrib                    x86_64               4.2.0-7.fc32                                      @updates                16 M
 opencv-core                       x86_64               4.2.0-7.fc32                                      @updates                19 M

Transaction Summary
=======================================================================================================================================
Remove  10 Packages
Freed space: 65 M
```

OK I got this (long ago) through https://nomacs.org.. I'm happy to live without, if it helps me to change my login shell! 😄 

Case closed re. this for me, leaving it up to this project's maintainers if they would like to pursue this, or just close this issue - fine for/fair to me.

@faho FYI

**Comment by xdelaruelle** [comment]
Thanks a lot for your report.

I am currently not able to reproduce the issue described on fish-shell/fish-shell#7560. Could you please provide some details about your environment, like:

* the environment variable set prior running the `dnf` command
* the modules configuration set in `/etc/environment-modules/*`
* any specific configuration of you fish shell

It will help me to understand what makes bash evaluates `/usr/share/Modules/init/fish`

**Comment by vorburger** [comment]
> the environment variable set prior running the dnf command

which environment variable? I suspect it's actually totally unrelated to DNF.

> the modules configuration set in /etc/environment-modules/*

standard as on Fedora 32, unmodified; `ls /etc/environment-modules/` :

    initrc  modulespath  siteconfig.tcl

> any specific configuration of you fish shell

https://github.com/vorburger/vorburger-dotfiles-bin-etc/tree/master/dotfiles/fish

> It will help me to understand what makes bash evaluates /usr/share/Modules/init/fish

FYI I've just, very briefly, tried to see if I could easily reproduce it, by doing the following:

```
$ podman run -it --rm fedora:32
[root@4d392b46f0c9 /]# dnf install -y environment-modules fish util-linux-user passwd
[root@4d392b46f0c9 /]# passwd -d
[root@4d392b46f0c9 /]# chsh -s /bin/fish
[root@4d392b46f0c9 /]# login
4d392b46f0c9 login: root
Last login: Sat Dec 19 18:41:26 on pts/2
<W> fish: No TTY for interactive shell (tcgetpgrp failed)
setpgid: Inappropriate ioctl for device
[root@4d392b46f0c9 /]# echo $SHELL
/bin/bash
```

but that runs into other unrelated problems. Personally I don't think it's "worth" it to pursue investigating this. FYI it does seem to affect a few people here and there; other than my https://github.com/fish-shell/fish-shell/issues/7560 note also https://github.com/keybase/keybase-issues/issues/3847 and https://bugzilla.redhat.com/show_bug.cgi?id=1707909. I would close for it, for now; perhaps others hitting this find it again in the future, and can add more details.

**Comment by xdelaruelle** [comment]
I would be interested to know if prior running the `dnf` command where you get the errors the `ENV`, `BASH_ENV` and any environment variable starting by `MODULES_*` were defined and if yet what were their value.

Did you also change the default shell to /bin/fish for the `root` account ?

I am also sure that it is not related to `dnf`, but I need to find a setup in which I can reproduce the issue (I am running Fedora 32 currently, but I did not find a way yet to get the error you describe when fish is set as my default shell).

I am currently suspecting that something should be fixed in `/etc/profile.d/modules.sh`.

**Comment by xdelaruelle** [comment]
@vorburger From what I have tested using fish shell as login shell with its default configuration on Fedora works fine with Modules.

From the different issue report you mentioned, a bash or sh shell evaluates `/usr/share/Modules/init/fish`, which is a fish shell script. I think the source order comes from the `/etc/profile.d/modules.sh` which is normally run when the bash/sh shell initializes. But somehow the shell fails to detect what kind of shell it is and thinks it is the fish shell.

There may be something on the configuration that leads bash/sh to think they are the fish shell.

**Comment by vorburger** [comment]
FYI I now suspect that this could have somehow been related to me originally having had an "exec fish" at the end of .bashrc.. see https://github.com/vorburger/vorburger-dotfiles-bin-etc/blob/fac76f69bf0e706e103c02e762ede2c34cf1072a/dotfiles/bashrc#L40. That is likely a dumb idea, and I've meanwhile updated https://wiki.archlinux.org/index.php/Fish#Modify_.bashrc_to_drop_into_fish which recommended that which recommended that. FYI similar problem on https://bugzilla.redhat.com/show_bug.cgi?id=1910424#c1. 

@xdelaruelle personally I do not think it's "worth" it to pursue further investigating this for you. I closed the issue to "signal" a _WORKSFORME._
