### ISSUE TITLE
tcsh: Completion helper variables show up in output of "set" command

### ISSUE THREAD

**Issue by cmarqu** [cea-hpc/modules#382]
Since we introduced modules in our environment by default, our admins have gotten complaints from users that running `set` in `tcsh` now shows a number of variables for environment modules, some of their values being quite long.

These come from `Modules/init/tcsh_completion` and are helper variables used by the `complete` command.
One example is `module_config_opts` which has a value of `"--dump-state --reset advanced_version_spec auto_handling avail_indepth collection_pin_version collection_target color colors contact extended_default extra_siteconfig home icase implicit_default locked_configs pager rcfile run_quarantine search_match set_shell_startup silent_shell_debug term_background unload_match_order verbosity wa_277"`.

Short of patching the modules installation to not load the completion file, what could be done to "keep the environment clean" :)?

`tcsh_completion` itself is a generated file and is not meant to be user-editable, so if those variables were instead expanded strings directly in the `complete` command in that file, the functionality would still be there and the output of `set` clean. The completion file would be a bit harder to read but not very much so.

What do you think?

**Comment by xdelaruelle** [comment]
Maybe these variable could be evaluated right away when defining the module complete so these variables could be unset at the end of `tcsh_completion` script ? I am not so proficient in csh so I do not know the specific syntax to use to make such change. Do you ?

**Comment by cmarqu** [comment]
I'm not that good in csh myself but I'll ask around, thanks for the idea!

**Comment by xdelaruelle** [comment]
Great. If this idea cannot be implemented in csh we could fallback to expanding the content of these variables at the `make` step. To do so, the `init/Makefile` should be updated to include these definitions and perform there replacement. In addition to the tcsh completion it should also apply to the bash completion (fish and zsh use a different kind of definition for there completion rules so they cannot benefit from this change).

Note that if you would like to be included in next release that I will close v4.7 development cycle on February 12th.

**Comment by cmarqu** [comment]
Alright, thanks for the heads-up!

**Comment by cmarqu** [comment]
I went with your second suggestion since I was not able to make the first suggestion work and couldn't find someone who was able to help.
It's also the safer option in my opinion since no additional magic is used; the end result is there in plain text and you don't need to mentally play the role of the shell doing variable expansion etc.
I tested this by `source` ing the resulting `*_completion` files and they continue to work.

Note that for bash, I left the `$MODULES_USE_COMPAT_VERSION=1` branch untouched.

**Comment by xdelaruelle** [comment]
Great! It will even simplify my work when adding new options to the module command.

For the `MODULES_USE_COMPAT_VERSION` branch, this is the right decision to left it untouched.

I have just updated the variable name to prefix them by `comp_` rather `module_` to make it clear these variables are used by completion scripts.

Many thanks for this contribution.
