### ISSUE TITLE
error:interpreter uses an incompatible stubs mechanism

### ISSUE THREAD

**Issue by AnWD** [cea-hpc/modules#384]
when login, new console print error"error:interpreter uses an incompatible stubs mechanism",please help~

### To Reproduce

```console
$ module <command1> <arguments>
$ module <command2> <arguments>
...
```

Location and content of any modulerc or modulefile involved:

```console
$ cat path/to/modulepath/module/version
$ cat path/to/modulepath/module/.modulerc
$ cat path/to/modulepath/.modulerc
...
```

### Error and debugging information

```console
$ module --debug <command1> <arguments>
$ module --debug <command2> <arguments>
...
```

### Modules version and configuration

```console
$ module --version
$ module config --dump-state
```

**Comment by xdelaruelle** [comment]
I need more information to help here. Please provide the result of the following commands:

$ module --version
$ module config --dump-state


What OS and distribution do you use ?

How is module initialized on your system when you login ?

How was Modules and Tcl installed on your system ?

**Comment by AnWD** [comment]
hi ,thanks for your reply.
here is my info:
vmplayer 16,0
OS: redhat6.9
module src version: modules-4.6.1.tar.gz
gcc -v: 4.4.7

when I just decompressed modules-4.6.1.tar.gz, and run ./configure,
errors: 
checking for runtest...  not found (after installed perl-libintl-1.20.rpm perl-Text-Unidecode-0.04.rpm, texinfo-5.1.5.rpm,dejagnu-1017198,   solved)
checking for manpath... not found (after installed perl-libintl-1.20.rpm perl-Text-Unidecode-0.04.rpm, texinfo-5.1.5.rpm,dejagnu-1017198,   solved)
checking for tclsh...  not found
checking for tclsh8.6... not found
checking for tclsh8.5...  not found
checking for tclsh8.4... not found
ERROR:tclsh could not be found.

now when I'm in tcl8.7a3/unix, run  make, it reports an error:

"
/home/admin/tcl8.7a3/generic/tclZipfs.c
In file included from /home/admin/tcl8.7a3/generic/tclZipfs.c:32:
/home/admin/tcl8.7a3/compat/zlib/contrib/minizip/crypt.h:33: error: redefinition of typedef ‘z_crc_t’
/home/admin/tcl8.7a3/compat/zlib/zconf.h:429: note: previous declaration of ‘z_crc_t’ was here
/home/admin/tcl8.7a3/generic/tclZipfs.c:296: error: redefinition of typedef ‘z_crc_t’
/home/admin/tcl8.7a3/compat/zlib/contrib/minizip/crypt.h:33: note: previous declaration of ‘z_crc_t’ was here
make: *** [tclZipfs.o] Error 1
"

I doubt it's gcc version causing this problem above, could you give me a hand or supply me a serise of matched environment versions so that I could install module smoothly.

thanks~

**Comment by cdorbell2** [comment]
Do you have installed the rpm tcl-devel ?

**Comment by xdelaruelle** [comment]
On Redhat 6 you can install Tcl with following command as super user :

$ yum install tcl tcl-devel

If you need to install Tcl by hand, please use stable version 8.6 (version 8.7 is currently alpha)

**Comment by cdorbell2** [comment]
for testing your build you can use docker (rh5 and rh6 have some problem with the kernel version) 
it's not working with sphinx , you must install the version sphinx10


docker run --rm -it  centos:centos6 /bin/sh

yum update -y 
yum install -y tcl tcl-devel gcc git autoconf dejagnu.noarch man  python-sphinx10-doc.noarch  python-sphinx10.noarch

cd /root
git clone https://github.com/cea-hpc/modules.git
cd modules
git checkout v4.6.1
./configure --prefix=/tools/modules/4.6.1/Modules  --with-modulepath=/tools/modules/4.6.1/modulefiles --disable-versioning --modulefilesdir=/tools/modules/4.6.1/modulefiles --enable-example-modulefiles
make 
make install

**Comment by AnWD** [comment]
excellent! thanks a lot!

**Comment by AnWD** [comment]
solved~
