### ISSUE TITLE
Confusing module-hide behavior

### ISSUE THREAD

**Issue by KBGrammer** [cea-hpc/modules#386]
### Describe the bug
module-hide commands in the system modulerc file are loaded (typographical errors produce output at login), but hidden packages are still visible to module avail. On testing, placing the module-hide line in a local modulerc file at (~/.modulerc) does hide the module. I would prefer a system-wide setting to hide some under-the-hood modules that users don't need to load themselves but that are loaded by other modules.
### To Reproduce
Add to $MODULEDIR/init/modulerc:
```console
module-hide foo/bar
module-hide foo/bar/1.0
```
Run module avail on a new login terminal.
```console
$ module avail
--------------------------------- /$MODULEPATH/modulefiles ---------------------------------
foo/bar/1.0
```

Location and content of any modulerc or modulefile involved:

```console#
%Module1.0
# This file defines the initial module command configuration, the default
# modulefiles search path and modulefiles you want to load by default for all
# users. It should contains lines of module command like 'module config conf
# val', 'module use path' and 'module load mod'
module use --append {/$MODULEPATH/modulefiles}
module-hide foo/bar
module-hide foo/bar/1.0
```

The module file is located in:
```console
/$MODULEPATH/modulefiles/foo/bar/1.0
```

### Expected behavior
foo/bar should be hidden via the commands in $MODULEDIR/init/modulerc.

### Modules version and configuration

```console
$ module --version
Modules Release 4.6.1 (2020-11-14)
```

**Comment by xdelaruelle** [comment]
The rc file mentioned in your description is the *init rc file*. This rc file is only played when module is initialized, typically when the user logs in. Only the commands that produce an environment change are useful here (like *module use*, *module load* or *module config*).

What you are looking for is the *global rc file* which is evaluated each time a module command is executed. This *global rc file* is expected at `$MODULEDIR/etc/rc` or at the location pointed by the `MODULERCFILE` environment variable.

**Comment by KBGrammer** [comment]
Thank you for the quick response. Placing the commands in $MODULEDIR/etc/rc work as expected.
