### ISSUE TITLE
docs: add link to download site under "Installing modules on ..."

### ISSUE THREAD

**Issue by zerothi** [cea-hpc/modules#387]
It is always a little difficult to find the tar.gz for download.
It would be nice if the documentation clearly had links to where to download.

In the top it would be nice with a link to the release pages, for instance.

**Comment by cdorbell2** [comment]
Hi,
why you don't use the release area under github : https://github.com/cea-hpc/modules/releases

**Comment by zerothi** [comment]
I do, but for readers of the documentation it makes more sense to have a link to the actual release page.
When I am reading in the docs about "Installation" it would be natural to have a link where to download said files.

**Comment by xdelaruelle** [comment]
Thanks a lot for this input. Indeed a proper link to a dist archive in the installation documentations is missing (for both Unix and Windows).

**Comment by xdelaruelle** [comment]
Fixed by 77cc5394
