### ISSUE TITLE
License is unclear

### ISSUE THREAD

**Issue by imphil** [cea-hpc/modules#389]
I found a problem with the license of this project.

* The README.md says "Modules is distributed under the GNU General Public License version 2 (GPL v2). Read the file COPYING.GPLv2 for details.", indicating GPLv2 (this specific version, not any later version).
* In the source tree there are both GPLv2+ ("GPLv2 or any later version", e.g. `script/createmodule.sh`) and GPLv3+ files (e.g. `script/envml.cmd`).
* The spec file `contrib/rpm/environment-modules.spec.in` suggests GPLv2+.

Given the current state of affairs in the source tree, the resulting work must be considered GPLv3+. Is that what you intended? In that case, could you please update the README and the COPYING file? If that wasn't intended, could you relicense all source files under GPLv2 or GPLv2+?

**Comment by xdelaruelle** [comment]
Thanks for pointing this out. I can confirm the intent for the core of the project is GPLv2+. I will update README and documentation index to clarify that as you suggest.

More recent additional utilities or test codes are done under under the GPLv3+. Is this problematic to have these newer parts of the project using a different license ?

**Comment by imphil** [comment]
Thanks for your answer @xdelaruelle. 

What matters for most people (including me) is the license of whatever is distributed to the end user, e.g. packed into the RPM. As soon as a single GPLv3+ file is included there, the whole distribution is GPLv3+.

Helper and test scripts that you only use within this repository, e.g. to facilitate tests and builds, can be of any license, as long as they are not distributed to the end user. However, it's fragile/dangerous to split the codebase like that: as soon as a GPLv3+ file "creeps" (e.g. gets renamed or refactored) into the distributed GPLv2+ code base, the whole thing is now GPLv3+.

I had a quick look through the code and currently it's rather clear that the resulting output (e.g. the RPM) must be GPLv3+: envmodules.c/h are GPLv3+, which is included as shared library in the distributed package.

I'd recommend sticking to a single (copyleft) license within this repository; everything else gets confusing rather quickly for contributors and packagers.

**Comment by xdelaruelle** [comment]
Thanks a lot for these details. I will try to re-license every files currently under GPLv3+ to GPLv2+. There are not a lot of copyright owner, so it hope it will be easy to get their consent to change the license.

**Comment by xdelaruelle** [comment]
Excluding myself, copyright owners for GPLv3+ files are:
* @rkowen: configure (line 23)
* @xdch47: configure (lines 431-432,588)
* @jraphanel: configure (lines 124,287-288,623-624), script/envml.cmd (lines 1-47,52-179) and script/envml (lines 43-48)

I have sent them an email to collect their consent to re-license these files from GPLv3+ to GPLv2+

**Comment by imphil** [comment]
@xdelaruelle Thanks a lot for going through this exercise. I know it's an annoying request, and I very much appreciate your work on it.

**Comment by xdelaruelle** [comment]
Consents have been obtained or contribution has been removed (will be reintegrated if consent if obtained later on). Every files in repository have been updated. Public website has also been updated to clarify the GPLv2+ license of Modules. So everything should be clear now.

**Comment by imphil** [comment]
Thank you, that's much clearer now :partying_face: I'd appreciate if you could do a new release with the clarified license in not too distant future to be able to update the metadata in distribution packages (not super urgent, though).

**Comment by xdelaruelle** [comment]
I will try to release a 4.7.1 version during the first half of April.
