### ISSUE TITLE
module-version is ignored

### ISSUE THREAD

**Issue by masics** [cea-hpc/modules#390]
In my module file "mymodule" I have a line:
> module-version mytool/1.1.0 default

If I do `module load mymodule` and then `module load mytool`, the version of the mytool is not 1.0.0 but another one (latest).
What is wrong?

**Comment by xdelaruelle** [comment]
`module-version` does not change the user environment, so once `mymodule` is loaded nothing is recorded in loaded environment to change the default version of `mytool`.

`module-version` command should be placed in `.modulerc` files (usually in the directory of the modulefile in question). So in your case there should be a `mytool/.modulerc` file containing:

```
module-version mytool/1.1.0 default
```

All the `.modulerc` files are evaluated when searching/resolving modules, so each time a `module load` or `module avail` is performed these files are evaluated and the `module-version` defines the symbolic versions like `default`. More details on how modulefiles are located are available here: https://modules.readthedocs.io/en/latest/modulefile.html#locating-modulefiles

**Comment by masics** [comment]
Oh, I did not understand the concept.
Is there a way to achieve my goal without adding modules folders (I don't have write permissions there).

**Comment by xdelaruelle** [comment]
Ok, from what I understand you use modulefiles that have been provided to you but you cannot modify this modulefile tree. In this tree, there is no explicit default defined for `mytool` so when you `module load mytool`, the latest version of mytool is loaded. What you want to achieve is to define a default version for `mytool` not to load the latest version by default. Am I right?

You can define your own module symbols over any modulefiles with the *user .modulerc file* located at `$HOME/.modulerc`. Create this file with:
```
#%Module
module-version mytool/1.1.0 default
```
Then when you load `mytool` afterward the 1.1.0 version is selected.

Note that you can only defined symbols if they have not been yet defined in the modulefile tree. So if a default version for `mytool` is already defined you cannot supersede it.

**Comment by masics** [comment]
There are two module trees - one for tools and the second for configurations.
I can't modify the tools but I can the configuration. Users load the configuration module which has env parameters set, paths, etc. In the same module, I wanted to define default versions of the tools.
I don't want every user has their own definition - it is very hard to maintain.

**Comment by xdelaruelle** [comment]
There is also the *global .modulerc file* which is located in the etcdir of the Modules installation (for instance `/etc/environment-modules/rc`). See the *Modulecmd startup* section in the module(1) man on your system to get this location.

Now if there is a link between a tool modulefile and a configuration modulefile, there may be some requirement declared in these modulefiles to express the dependency. For instance if `mymodule` configuration modulefile requires `mytool/1.1.0` to be effective, you may load this requirement by adding into `mymodule` modulefile:

    module load mytool/1.1.0

This way you also get the correct module version loaded.

It may also be set in the opposite manner : if a tool requires a configuration to be effective, the tool modulefile may also load the corresponding configuration modulefile.

**Comment by masics** [comment]
I can't change the global file either. The only writable file for me is a config module I manage. 
My goal is to help my users to write `module load tool` instead of `module load tool/1.1.1`.
For the specific environment, we have a different setup that has specific versions.

**Comment by xdelaruelle** [comment]
So in your situation, what you can is providing *meta-modules" that automatically load other modules, like I described in my previous command.

An alternative would be to provide a specific *global modulerc* to your users by defining the `MODULERCFILE` environment variable. See https://modules.readthedocs.io/en/latest/module.html#modulecmd-startup.

**Comment by xdelaruelle** [comment]
I think all the relevant information have been provided, so I am closing this issue.
