### ISSUE TITLE
unable to build environment-modules in ubuntu:18.04 container

### ISSUE THREAD

**Issue by anthonyLieures** [cea-hpc/modules#391]
Hello everyone,

### Describe the bug
I tried to install environment-modules in ubuntu: 18.04 container (docker pull ubuntu:18.04). I followed instructions from [this documentation](https://modules.readthedocs.io/en/latest/INSTALL.html). At `make` step an error occured as shown below

### To Reproduce

In ubuntu:18.04 container

``` bash
$ apt-get install -y bash make sed dejagnu grep gcc tcl-dev autoconf automake autopoint python python-sphinx curl less
$ curl -LJO https://github.com/cea-hpc/modules/releases/download/v4.7.0/modules-4.7.0.tar.gz
$ tar xfz modules-4.7.0.tar.gz
$ cd  modules-4.7.0
$ ./configure
$ make 
```

```console

root@26eb852d7717:~/modules-4.7.0# make
  GEN version.inc
  GEN init/sh
  GEN init/ksh
  GEN init/bash
  GEN init/zsh
  GEN init/profile.sh
  GEN init/bash_completion
  GEN init/csh
  GEN init/tcsh
  GEN init/tcsh_completion
  GEN init/profile.csh
  GEN init/perl.pm
  GEN init/python.py
  GEN init/ruby.rb
  GEN init/lisp
  GEN init/tcl
  GEN init/fish
  GEN init/cmake
  GEN init/r.R
  GEN init/modulerc
  GEN init/zsh-functions/_module
  GEN init/../contrib/modulefiles/modules
  GEN modulecmd.tcl
  GEN README
  GEN script/add.modules
  GEN script/createmodule.py
  GEN script/modulecmd
  CC  lib/libtclenvmodules.so
  GEN doc/build/module.1
make[1]: Nothing to be done for 'txt'.
```

### Expected behavior

environment-modules properly installed

### Additional context

It should be notice I'm a beginner with linux compilation and I would appreciate any help.

I tried to install environment-modules in a Docker container because it's a test environment for the ansible playbook I'm developping.

**Comment by xdelaruelle** [comment]
It seems the `make` step has run ok. Did you get any specific error message ?

After the `make` step, `make install` should be performed. After that environment-modules will be installed.

**Comment by anthonyLieures** [comment]
It's ok I'm sorry. The `make install` works without error message, I finished the installation.

So, this output in the `make` step is normal ?

``` console
root@d7ff7522b764:~/modules-4.7.0# make
make[1]: Nothing to be done for 'all'.
make[1]: Nothing to be done for 'man'.
make[1]: Nothing to be done for 'txt'.

```

**Comment by xdelaruelle** [comment]
Yes the output is normal. When make consider nothing has to be built it prints messages like `Nothing to be done for '<target>'`. When building environment modules from the dist tarball, the documentation is pre-built to avoid a dependency on the documentation subsystem. That is why it says `Nothing to be done for 'txt'.`

**Comment by anthonyLieures** [comment]
Ok I understand. Thank you for your explanations !
