### ISSUE TITLE
errors on irene in pack et all

### ISSUE THREAD

**Issue by ClaireLevyFR** [cea-hpc/modules#393]
### Describe the bug
I dont know if it is a bug, or a problem to access disks.
All errors visible here https://hermes.ipsl.upmc.fr/static/simulation.detail.html?uid=0084f988-9d0a-4413-a9b9-1e5f8b96432f
and also here /ccc/scratch/cont003/gen0826/clevy/IGCM_OUT/NEMO/PROD/clim/O2SIPI-V4.0.6-CLIM-CORE-01/Out

where i find a number of errors in jobs outputs

### To Reproduce
The submit directory is here: /ccc/cont003/home/locean/clevy/NEWRC_ORCA2_ICE_PISCES_VALID_2021/modipsl/config/NEMO_v7/O2SIPI-Vtrunk-CLIM-CORE-01
and at this stage I dont know what I could do: relaunch only de packs?

```console
$ module <command1> <arguments>
$ module <command2> <arguments>
...
```

Location and content of any modulerc or modulefile involved:

```console
$ cat path/to/modulepath/module/version
$ cat path/to/modulepath/module/.modulerc
$ cat path/to/modulepath/.modulerc
...
```

### Error and debugging information

```console
$ module --debug <command1> <arguments>
$ module --debug <command2> <arguments>
...
```

### Modules version and configuration

```console
$ module --version
$ module config --dump-state
```

**Comment by xdelaruelle** [comment]
Hello,

Please send a mail to the computing center support for a direct assistance on your issue (hotline.tgcc <at> cea.fr). The TGCC team will then file a bug here if there is an issue with `module`.

Regards,
Xavier

**Comment by xdelaruelle** [comment]
Computing center team has got back to you to work on your job issue. I am closing this ticket here.
