### ISSUE TITLE
Can't build when this repository is a git submodule

### ISSUE THREAD

**Issue by alef** [cea-hpc/modules#398]
### Describe the bug

Your `Makefile` variable `GIT_REFRESH_PREREQ` relies on `.git/index` if path `.git` exists.
This doesn't apply to submodules because `.git` is a file here, instead of being a directory.
The error you get in such case:
`make[1]: *** No rule to make target '.git/index', needed by 'version.inc'. Stop.`

### To Reproduce
Steps to reproduce the behavior (**untested**):

Kind of ...
```console
$ mkdir /tmp/parent 
$ cd /tmp/parent
$ git init 
$ git submodule add https://github.com/cea-hpc/modules.git
$ cd modules
$ ./configure
$ make
...
```
### Expected behavior
It should build even when you are a submodule of another _git_ repository.

### Additional context
Workaround: remove "`.git/index`".

**Comment by xdelaruelle** [comment]
Many thanks for this bug report. I have adapted tests of `.git` as it could be either a file or a directory. The `git rev-parse --git-dir` command is also now used to determine git directory location rather assuming it is `.git`.
