### ISSUE TITLE
Module alias not found in GitHub Workflow

### ISSUE THREAD

**Issue by vsoch** [cea-hpc/modules#400]
Hi modules team! I hope it's okay I'm posting here, I'd like to be able to link to a GitHub issue here and have it tracked in the PR. Basically, I have a PR: https://github.com/singularityhub/singularity-hpc/pull/373 that adds a test suite that installs and loads a module, and then uses one of the aliases. For some reason, I am always getting [command not found](https://github.com/singularityhub/singularity-hpc/pull/373/checks?check_run_id=2751238754). When I test the same series of commands in an actual cluster environment it works as expected, so I'm thinking that I'm perhaps forgetting to set some environment variable or similar so that the aliases are found? Note that I have two jobs that are failing in this manner - one that installs a singularity container module, and the other that installs a podman container module. I tried changing the syntax of the set-alias commands between the two just for testing, e.g.,

```
# podman
set-alias "{|module_name|}-shell" "${shellCmd}"

# vs singularity
set-alias {|module_name|}-shell {${shellCmd} $*}
```
but it doesn't seem to make a difference. I'm not sure if one is more correct than the other, but I'd be happy to follow your advice.
But importantly, if you have any insight as to why the commands are not found in GitHub actions it would be greatly appreciated! This is the last test I wanted to get working to consider merge. Thank you!

**Comment by xdelaruelle** [comment]
Hi Vanessa! Your welcome to post here.

I have made several tests of the *Run python module tests* script from the test workflow of singulary-hpc (`add/podman` branch).

Alias seems correctly defined, but as you do not run an interactive shells, [these aliases are not expanded in the session](https://github.com/xdelaruelle/singularity-hpc/runs/2751853326?check_suite_focus=true#step:10:41).

So you need to enable the `expand_aliases` shopt!

    shopt -s expand_aliases

After adding the above line, the test succeed:

https://github.com/xdelaruelle/singularity-hpc/actions/runs/908689776

**Comment by xdelaruelle** [comment]
@vsoch Looking at the modulefile template, I would suggest to also define a shell function when using Environment Modules as you do for Lmod. See the [`set-function`](https://modules.readthedocs.io/en/latest/modulefile.html#mfcmd-set-function) modulefile command. You will have this way the same shell behavior whether the module implementation used.

If you want to stick with shell aliases, the ` $*` at the end of the alias definition should be removed: shell aliases are expanded in place then strings after the alias names are automatically taken as argument. This is a bit different with shell function where you need to refer to the argument specified to insert them in the resulting command (but you can this way insert them the way you want where you want)

**Comment by vsoch** [comment]
@xdelaruelle I am so grateful for your help - this is probably the highest quality and quickest support I've ever received on a GitHub issue. Adding shopt (and also a note in the docs) worked beautifully - all [tests are passing](https://github.com/singularityhub/singularity-hpc/pull/373/checks?check_run_id=2754034113)! I tested functions to compare to aliases, and wound up sticking with aliases for the time being because I think I would want to test a little further. Pinging @marcodelapierre so we can discuss using functions instead of aliases at some point (I'd be interested in the advantages, and if aliases have support for older versions?)

But anyway - thank you again! We can safely close this issue. Looking forward to using/learning more about environment modules as we develop shpc!

**Comment by xdelaruelle** [comment]
@vsoch Many thanks for you kind message.

**Comment by marcodelapierre** [comment]
@vsoch let me share what I think I have learnt on these shell features (such a huge topic!! :-) )

My understanding is that aliases were born as a utility for interactive shell usage (literally, shortcuts for repeated operations), and thus they come with more limitations compared to shell functions.

In particular, although the `shopt` setting above can be used to make alias work in non-interactive shells, too (including batch scripts), my experience tells me that aliases can never be passed to child shells. (happy to be proven wrong though!)

Therefore, for the purposes of defining custom application executions, as in the case of SHPC, I think shell functions are more powerful and should be preferred.

With Tcl modules, I would happily move to shell functions, following extensive testing.
There's one caveat that I anticipate here: shell functions are supported in modulefiles written in Tcl only by Environment Modules; LMOD can use both Lua and Tcl, but in the latter case some more recent features are not supported.
Therefore, if using shell functions in Tcl modules, these would only work with Env Modules and not LMOD.
It might not be a big deal, as in LMOD deployments SHPC can generate Lua modulefiles anyway, however I think it's one to be aware of.
For instance, in this case it would be advisable to rename the `tcl` option for modulefiles to `envmod` or `env` or similar, to clearly express the (in)compatibilities in place.
