### ISSUE TITLE
specific setenv variable setting with a 'puts' in the same modulefile

### ISSUE THREAD

**Issue by jaysullivan** [cea-hpc/modules#404]
Version: 3.2.10-10

Hi All,

Running into a weird situation such that a particular ENV Variable being created is somehow clobbered by a 'puts'.

Here are the contents of my module file:
```
#%Module1.0
##
## modules test
##
##

set prefix /foobar

setenv BINDIR ${prefix}/bin
setenv SCRIPTBINDIR ${prefix}/bin
setenv SCRIPTBIN ${prefix}/bin

prepend-path PATH ${prefix}/bin

# Requires a stack size of unlimited
puts "ulimit -s unlimited"
```

After you load the module, note that "BINDIR" isn't set. 

Now comment out the "puts....". Load module. BINDIR is now set.

Here is where it gets even weirder. Re-enable the puts change just the BINDIR variable name to include a single lowercase character in the front, IE: jBINDIR. Load the module. At this point you should see the ENV variable in the shell

If you do the same thing with any number of capitalized characters at the beginning or end, except the word "SCRIPT", IE JBINDIR or BINDIRJ, that variable will not show up.

To check the existence, I've been doing 'env|grep BIN'

Any ideas what's going on? Or ideas where things are wrong and what I can do to fix?

Thank you kindly in advance,
-Jay

**Comment by xdelaruelle** [comment]
Hi Jay,

The issue comes from the sequence generated by `modulecmd` (the binary called by the `module` shell function to generate shell code):

```sh
$ /usr/share/Modules/libexec/modulecmd-compat bash load ./test
ulimit -s unlimited
BINDIR=/foobar/bin ;export BINDIR;LOADEDMODULES=test ;export LOADEDMODULES;PATH=/foobar/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin ;export PATH;SCRIPTBIN=/foobar/bin ;export SCRIPTBIN;SCRIPTBINDIR=/foobar/bin ;export SCRIPTBINDIR;_LMFILES_=./test ;export _LMFILES_;
```
The above shell code is then evaluated in current shell. But a `;` character is missing at the end of the `ulimit` line so the `BINDIR=/foobar/bin` directive is ignored.

If you add a semicolon at the end of the `puts` string, you will obtain the expected behavior:

```tcl
puts "ulimit -s unlimited;"
```

Regards,
Xavier

**Comment by jaysullivan** [comment]
Many thanks. I'll try this out Monday

Jay

**Comment by jaysullivan** [comment]
the ; worked. Thank you so much.

-Jay
