### ISSUE TITLE
Support for MacOS Catalina?

### ISSUE THREAD

**Issue by pvelesko** [cea-hpc/modules#409]
Any plans for supporting MacOS? 

Please use preferably the Modules mailing-list to post question:

> https://sourceforge.net/projects/modules/lists/modules-interest

**Comment by xdelaruelle** [comment]
MacOS is already supported. You could either install it like described in the [Installing Modules on Unix](https://modules.readthedocs.io/en/stable/INSTALL.html) guide or install it through [Homebrew](https://formulae.brew.sh/formula/modules).

**Comment by pvelesko** [comment]
@xdelaruelle ah homebrew worked like a charm - I was trying to compile from source and ran into issues I thought there might be compatibility issues with Catalina or M1. Thanks.

**Comment by xdelaruelle** [comment]
@pvelesko For continuous integration purpose Modules is manually built on OSX (Catalina) with the following command sequence:

```
$ ./configure --with-tcl=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tcl.framework/Versions/8.5
$ make
$ make install
```

It requires Xcode to be installed.

If you get a specific error message when trying to build it manually, I would be interested to get the list of command typed and the error obtained, to check if there is no specific issue on your platform.

**Comment by pvelesko** [comment]
@xdelaruelle I think the issue was that I was building Tcl myself - I didn't realise that it comes installed with MacOS xcode sdk
