### ISSUE TITLE
5.0.0: regression: rst bullet lists in design docs (https://github.com/cea-hpc/modules/issues/306)?

### ISSUE THREAD

**Issue by balducci** [cea-hpc/modules#413]
hi

build of 5.0.0 fails for me with:

```
  GEN doc/build/*.txt
/usr/bin/sphinx-build -q -b text "source" "build"

Exception occurred:
  File "/usr/python3/site_python3/lib64/Sphinx.egg/sphinx/writers/text.py", line 853, in visit_definition_list_item
    self._classifier_count_in_li = len(node.traverse(nodes.classifier))
TypeError: object of type 'generator' has no len()
The full traceback has been saved in /tmp/sphinx-err-z6x5h6on.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make[2]: *** [Makefile:93: build/CONTRIBUTING.txt] Error 2
make[1]: *** [Makefile:94: pkgdoc] Error 2
make[1]: Leaving directory '/home/balducci/tmp/install-us-d/modules-5.0.0.d/modules-5.0.0'

```
Turns out that this is due to ```doc/source/design/variants.rst``` being broken in the same way as described in https://github.com/cea-hpc/modules/issues/306

Applying the same fix as then allows the build to complete successfully.

Using Sphinx-4.2.0

Thanks a lot for your work

ciao
-gabriele

**Comment by xdelaruelle** [comment]
Hi @balducci

Do you have any specific Sphinx configuration to obtain such error? I would like to reproduce the error you get on my side to be sure that I correctly fix the rst files.

Ciao,
Xavier

**Comment by xdelaruelle** [comment]
I have just fixed the one list entry with missing space line before and after in `variant.rst` (see 508ec274 commit). I have only found this one issue.

I would be glad to get a setup on my side to reproduce the issue you face. Even after trying different version of Sphinx (3.4.2, 4.1.2, 4.2.0) and different verbosity configuration, I am not able to spot such issues.
