### ISSUE TITLE
add completion on tcsh shell for `ml` command

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#416]
When Modules is initialized on *tcsh* shell both `module` and `ml` commands are defined. Shell completion is provided for `module` command but it is currently missing for the `ml` command.

To add *tcsh* shell completion for `ml` command, the [`init/tcsh_completion.in`](https://github.com/cea-hpc/modules/blob/master/init/tcsh_completion.in) file has to be updated.

Shell completion for the `ml` command is available for *bash* shell. So looking at [`init/bash_completion.in`](https://github.com/cea-hpc/modules/blob/master/init/bash_completion.in) file may provide some hints on the completion code to achieve.

**Comment by Laurent-Besson** [comment]
As discussed on the ML, I'll propose a first version of completion for "ml" command.

**Comment by Laurent-Besson** [comment]
Hello Xavier,

Sorry to come back only now. I have downloaded from GitHub the "main" branch and created locally a branch to implement some simple completion on "ml" command. But I can't push on GitHub. Here is the message I get:

>>> git push --set-upstream origin issue_416
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/cea-hpc/modules.git/'

Could you help me on this ? What is the standard procedure to push my local branch on Githib ?
Thanks

**Comment by Laurent-Besson** [comment]
More news: I hage generated my own Personal Access Token and now I get this message:

remote: Permission to cea-hpc/modules.git denied to Laurent-Besson.
fatal: unable to access 'https://github.com/cea-hpc/modules.git/': The requested URL returned error: 403

Do you have any clue on what is going on ?

**Comment by xdelaruelle** [comment]
Hello Laurent,

You cannot push directly to the cea-hpc/modules repository. Instead you need to:

1. fork this repository into your personal GitHub user space
2. create a specific branch to elaborate the change within
3. push this branch to your personal fork on GitHub
4. create a pull request based on this branch

GitHub has some tutorials to help you performing these steps:
* https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo
* https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
