### ISSUE TITLE
add Cirrus CI test case to verify build on ARM architecture

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#420]
Cirrus CI now has the ability to run tests over an ARM container:

https://cirrus-ci.org/guide/linux/#linux-containers

[`.cirrus.yml`](https://github.com/cea-hpc/modules/blob/master/.cirrus.yml) could be updated to add a test case that run on such container to verify Modules correctly build and run on such CPU architecture.

**Comment by StealthBadger747** [comment]
Looking for something to contribute. Never used cirrus-ci before. On the surface it looks like I would just need to make templates for each OS and then change the container type for x86_64 or ARM. Or is there something more involved here?

**Comment by xdelaruelle** [comment]
@StealthBadger747 Yes this one is quite straighforward: copy an existing block, then adapt x86_64 intro arm and test to see if it is working or some specific OS setup should be done
