### ISSUE TITLE
Unload module issue with --duplicates flag

### ISSUE THREAD

**Issue by mzborovsky** [cea-hpc/modules#421]
I'm using module version 4.7.0,  in the module file, I have added --duplicates flag to solve an issue we had.
--duplicates flag  works great but when unloading the module this output is printed on the screen:
**Unloading tools/test
  WARNING: --duplicates option has no effect on unload-path**
I have managed to disable those messages with -silent flag when doing module unload / module switch, but I need it to be fixed inside the module file itself, so users won't need to add anything and this output won't be printed.
Is there any flag I could add to the prepend-path command or to the something in the module file ?

**Comment by xdelaruelle** [comment]
Seems like a bug that also affects newer versions.

I will fix it on newer version but the following workaround could be used in existing modulefiles to avoid this warning message on older versions:

```tcl
#%Module
if {[module-info mode unload]} {
    prepend-path FOO /path/to/dir
} else {
    prepend-path --duplicates FOO /path/to/dir
}
```
