### ISSUE TITLE
filter-out Modules internal variables on sh-to-mod/source-sh

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#427]
If script currently evaluated by `sh-to-mod` sub-command or `source-sh` modulefile command relies itself on module to load some modulefiles, the environment variables intended for Modules internal use are reported.

Such environment variables (`LOADEDMODULES`, `_LMFILES_` and `__MODULES_*`) should be filtered-out to get a consistent result not reporting/setting these internal variables.

**Comment by mgsternberg** [comment]
Xavier, thank you for taking up the suggestion.

It occurred to me that multiple (chained) invocations of sh-to-mod should produce the same modules code, _i.e._, be idempotent up to sorting, and therefore that should be a good unit test even if more internals are added in the future. I haven’t thought through yet if it’s dispositive, though.


Michael
