### ISSUE TITLE
protect environment variables from being modified by modulefiles

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#429]
[As discussed on the mailing-list](https://sourceforge.net/p/modules/mailman/modules-interest/thread/35cc47cb-3afa-4bb8-9d06-b0a125223d27%40email.android.com/#msg37368775), it appears interesting to be able to protect some environment variables from being changed when loading or unloading modulefiles.

This could be implemented by adding a `protected_envvars`, a colon-separated list holding the environment variables that cannot be modified by modulefiles. This configuration is linked to the `MODULES_PROTECTED_ENVVARS` environment variable.

A warning message should be emitted when a modulefile attempts to modify a protected environment variable. This warning does not end the ongoing modulefile evaluation.

Modulefile commands affected by this warning message are:
* append-path
* prepend-path
* remove-path
* setenv
* unsetenv

**Comment by adrien-cotte** [comment]
Hi @xdelaruelle 

This is my first try.

```
diff --git a/tcl/envmngt.tcl.in b/tcl/envmngt.tcl.in
index 36021556..a31d59ef 100644
--- a/tcl/envmngt.tcl.in
+++ b/tcl/envmngt.tcl.in
@@ -1154,11 +1154,20 @@ proc get-env {var {valifunset {}}} {
 proc set-env {var val} {
    set mode [currentState mode]
    reportDebug "$var=$val"
-
+    
+   # leave function if $var is protected by protected_envvars config
+   set isprotected false
+   foreach protectedvar [split [getConf protected_envvars]] {
+      if {$var eq $protectedvar} {
+         reportDebug "$var not set (protected_envvars config)"
+         set isprotected true
+      }
+   }
+        
    # an empty string value means unsetting variable on Windows platform, so
    # call unset-env to ensure variable will not be seen defined yet raising
    # an error when trying to access it
-   if {[getState is_win] && $val eq {}} {
+   if {[getState is_win] && $val eq {} && !$isprotected} {
       unset-env $var
    } else {
       interp-sync-env set $var $val
diff --git a/tcl/init.tcl.in b/tcl/init.tcl.in
index b21dc69b..46b9e93c 100644
--- a/tcl/init.tcl.in
+++ b/tcl/init.tcl.in
@@ -95,6 +95,7 @@ array set g_config_defs [list\
    pager {MODULES_PAGER {@pagercmd@} 0}\
    rcfile {MODULERCFILE <undef> 0}\
    redirect_output {MODULES_REDIRECT_OUTPUT 1 0 {0 1}}\
+   protected_envvars {MODULES_PROTECTED_ENVVARS <undef> 0}\
    quarantine_support {MODULES_QUARANTINE_SUPPORT @quarantinesupport@ 0 {0\
       1}}\
    run_quarantine {MODULES_RUN_QUARANTINE <undef> 0}\
```

What do you think?
Should I protect variables from `unset-env` too?
My handmade tests make me feel this patch is enough.

I still have to write configure, documentation, completion and testsuite for this new feature.

**Comment by xdelaruelle** [comment]
Good start!

Some suggestion:
* Should also protect from `unset-env`.
* Warning message should be emitted if variable is protected.
* Could rewrite the foreach if sequence in:
  ```tcl
  if {$var in [split [getConf protected_envvars] :]} {
  ```

**Comment by xdelaruelle** [comment]
@adrien-cotte Any news from your side on this pull request ?
