### ISSUE TITLE
Is there a way to add .jar or .py files to PATH?

### ISSUE THREAD

**Issue by wtulle** [cea-hpc/modules#430]
I'm trying to add a path where .jar or .py files are located, so I don't need to write the full path in my script when I call them. 

Example:

module file:
```
#%Module1.0########################
prepend-path PATH /apps/Trimmomatic-0.39
```

script file:
```
#!/bin/bash
module load Trimmomatic-0.39
java -jar Trimmomatic-0.39.jar PE -phred33 ..........
```

But I keep getting error: "Error: Unable to access jarfile Trimmomatic-0.39.jar"
I am doing it wrong? Is this feature supported?

Thanks

**Comment by netrc** [comment]
'PATH' is used by the shell to find executables - that's how /bin/bash finds the 'java' executable
'CLASSPATH' is used by java to find jar-files.
I think the modulefile should be 'prepend-path CLASSPATH /apps/Trimmomatic-0.39
