### ISSUE TITLE
module reload changes path ordering

### ISSUE THREAD

**Issue by ben-bowers** [cea-hpc/modules#431]
### Describe the bug

Path ordering is different before and after a `module reload`, which was unexpected.

### To Reproduce

```console
$ echo $MYPATH

$ module load FOOFOO
Loading FOOFOO
  Loading requirement: BARBAR
$ echo $MYPATH
/home/BAR:/home/FOO
$ module reload
$ echo $MYPATH
/home/FOO:/home/BAR
```

Location and content of any modulerc or modulefile involved:

```console
$ cat FOOFOO
#%Module1.0 # -*- tcl -*-
prepend-path MYPATH /home/FOO
module load BARBAR

$ cat BARBAR
#%Module1.0 # -*- tcl -*-
prepend-path MYPATH /home/BAR
```

### Expected behavior

`$MYPATH` path variable consistent before and after reload

### Error and debugging information

```console
$ module --debug <command1> <arguments>
$ module --debug <command2> <arguments>
...
```

### Modules version and configuration

```console
$ module --version
Modules Release 5.0.0 (2021-09-12)
# The same behavior exists in 4.3.x, 4.5.x and 4.6.x as well.
```

### Additional context

It is worth noting that if all `prepend-path`s above are changed to `append-path` then the same ordering issue occurs.

**Comment by xdelaruelle** [comment]
The order of commands in `FOOFOO` modulefile is not consistent with the resulting load order: `BARBAR` is loaded before `FOOFOO` but MYPATH prepend is achieved in FOOFOO prior this requirement load.

When reloading, environment changes are made consistent to the loading order (unload FOOFOO, unload BARBAR, load BARBAR, load FOOFOO), so the environment variable changes triggered by FOOFOO are applied last. Same behavior is observed if BARBAR modulefile is already loaded prior attempting to load FOOFOO modulefile.

To achieve consistency, the load of requirements should be done prior any environment changes. So in this example, `module load BARBAR` should be done prior the `prepend-path MYPATH` command.

**Comment by ben-bowers** [comment]
> To achieve consistency, the load of requirements should be done prior any environment changes.

Your explanation makes sense in context of how the reload currently works.  I had mistakenly thought that a reload would work similarly to what would happen if using a `module purge ; module load FOOFOO`, as `BARBAR` is loaded from inside `FOOFOO`.

I don't think I previously understood that `prepend/append-path` must come before any `module load` commands in a modulefile - is this documented somewhere?

In any event, I think this particular case is an attempt to arrange elements in `$PATH` in a specific order (the FOOFOO/BARBAR sample is a reduced testcase using `$MYPATH` to be more obvious), so I will need to re-think how I am sequencing things in light of loading multiple modulefiles.

**Comment by xdelaruelle** [comment]
> I don't think I previously understood that prepend/append-path must come before any module load commands in a modulefile - is this documented somewhere?

Should come *after* requirement specification (module load/prereq). I will improve the documentation on that point, I am quite sure this is not well documented currently.

**Comment by ben-bowers** [comment]
Oops I said that incorrectly.  My understanding is now that the sequence of `module load / prereq` (1st) and `prepend-path / append-path` (2nd) directives in the modulefile is important *if reloading is ever going to be done*
