### ISSUE TITLE
uncomplete → incomplete

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [cea-hpc/modules#438]
### Describe the bug
Is it worth/possible fixing this typo without breaking compatibility?

### To Reproduce

```console
$ grep -R uncomplete | wc -l
44
$ 
```

### Expected behavior
Use **i**ncomplete instead of **u**ncomplete.

**Comment by xdelaruelle** [comment]
Thanks Dimitri for this suggestion.

Here the word "uncomplete" is used to say "undo complete", to unset the shell completion. It is derivated from the name of the "uncomplete" command in tcsh as we also use the name "unsetenv" to say "undo-setenv".
