### ISSUE TITLE
Module ERROR: couldn't create error file for command: no space left on device

### ISSUE THREAD

**Issue by wenzler** [cea-hpc/modules#450]
Hey,

this is using modules 4.5.2

 Module ERROR: couldn't create error file for command: no space left on device
        while executing
    "exec lsb_release -irs"

Could it be that modules tries to write to the installation directory of modules if an exec fails?
Is there a variable/setting to alter?

Thanks!

**Comment by wenzler** [comment]
Looks to be /tmp full triggers this.

**Comment by xdelaruelle** [comment]
After a first quick search, it seems it come from the exec command of Tcl itself:
https://github.com/tcltk/tcl/blob/main/generic/tclPipe.c#L790-L806

**Comment by wenzler** [comment]
Yeah suspected that. Something for our user FAQ then...
Thanks!
