### ISSUE TITLE
5.0.1 in no color mode goes bonkers on module tagging

### ISSUE THREAD

**Issue by wenzler** [cea-hpc/modules#452]
According to changelog the aL tagging was introduced

Changed in version 4.7: Output items for module tags auto-loaded (aL), forbidden (F), hidden and hidden-loaded (H), loaded (L), nearly-forbidden (nF), sticky (S) and super-sticky (sS) added

Yet, with 5.0.1 we see that there is a repeated tagging for modules
export TERM=xterm
export MODULES_COLOR=never
module list
Currently Loaded Modulefiles:
 1) krb5/krb5 <aL:aL:aL:aL>  2) vb/init
....

I suppose this isnt as intended, or?

Thanks!

**Comment by xdelaruelle** [comment]
Seems an issue. Once in this state, could you please send the result of the following command:

```
module config --dump-state
```

Send it to me directly by email if you do not want these information to be publicly available on this ticket.

**Comment by wenzler** [comment]
Modules Release 5.0.1 (2021-10-16)

- Config. name ---------.- Value (set by if default overridden) ---------------
advanced_version_spec     1
auto_handling             0
avail_indepth             1
avail_output              modulepath:alias:dirwsym:sym:tag:key
avail_terse_output        modulepath:alias:dirwsym:sym:tag
collection_pin_version    0
collection_target         <undef>
color                     never
colors                    hi=1:db=2:tr=2:se=2:er=91:wa=93:me=95:in=94:mp=1;94:di=94:al=96:va=93:sy=95:de=4:cm=92:aL=100:L=90;47:H=2:F=41:nF=43:S=46:sS=44
contact                   xxxxxxxxx@xxxxxxx
csh_limit                 4000
editor                    /xxxxx/joe/4.6/bin/joe
extended_default          1
extra_siteconfig          <undef>
home                      /xxxxx/modulestcl/5.0.1
icase                     search
ignored_dirs              CVS RCS SCCS .svn .git .SYNC .sos
implicit_default          1
implicit_requirement      0
list_output               header:idx:variant:sym:tag:key
list_terse_output         header
locked_configs            
mcookie_version_check     1
ml                        1
nearly_forbidden_days     14
pager                     /usr/bin/less -eFKRX
quarantine_support        0
rcfile                    <undef>
run_quarantine            <undef>
search_match              starts_with
set_shell_startup         0
shells_with_ksh_fpath     
silent_shell_debug        0
siteconfig                /xxxxx/modulestcl/5.0.1/etc/siteconfig.tcl
tag_abbrev                auto-loaded=aL:loaded=L:hidden=H:hidden-loaded=H:forbidden=F:nearly-forbidden=nF:sticky=S:super-sticky=sS
tag_color_name            
tcl_ext_lib               /xxxxx/modulestcl/5.0.1/lib/libtclenvmodules.so
term_background           dark
term_width                0
unload_match_order        returnlast
variant_shortcut          
verbosity                 concise
wa_277                    0

- State name -----------.- Value ----------------------------------------------
always_read_full_file     1
autoinit                  0
clock_seconds             1650440997
cmdline                   /xxxxx/modulestcl/5.0.1/libexec/modulecmd.tcl bash config --dump-state
commandname               config
domainname                xxxxxxxxxxxxxxxx
error_count               0
extra_siteconfig_loaded   0
false_rendered            0
force                     0
hiding_threshold          0
inhibit_errreport         0
inhibit_interp            0
init_error_report         1
is_stderr_tty             0
is_win                    0
kernelversion             #xxx-Ubuntu SMP Wed xxx xx xx:xx:xx:xx UTC 20xx
lm_info_cached            0
machine                   x86_64
modulefile                {}
nodename                  xxxxxxxxxx0
os                        Linux
osversion                 4.xx.x-xxx-generic
paginate                  0
path_separator            :
report_format             regular
reportfd                  stderr
return_false              0
shell                     bash
shelltype                 sh
siteconfig_loaded         1
sub1_separator            &
sub2_separator            |
subcmd                    config
subcmd_args               --dump-state
tcl_ext_lib_loaded        0
tcl_version               8.6.4
term_columns              77
try_modulefile            0
usergroups                xxxxxx xxxxxx
username                  xxxxxxxxx

- Env. variable --------.- Value ----------------------------------------------
LOADEDMODULES             krb5/krb5:krb5/afsadm:vbuild/init:joe/4.6
MODULEPATH                /xxxxx/modules/0/modulefiles:/xxxxx/site/modules:/xxxxx/common/modules
_LMFILES_                 /xxxxx/common/modules/krb5/krb5:/xxxxx/common/modules/krb5/afsadm:/xxxxx/common/modules/vbuild/init:/xxxxx/common/modules/joe/4.6
__MODULES_LMALTNAME       vbuild/init&as|vbuild/default&as|vbuild/latest:joe/4.6&joe/default&joe&as|joe/latest:vbuild/init&as|vbuild/default&as|vbuild/latest:joe/4.6&joe/default&joe&as|joe/latest:vbuild/init&as|vbuild/default&as|vbuild/latest:joe/4.6&joe/default&joe&as|joe/latest
__MODULES_LMTAG           krb5/krb5&auto-loaded:krb5/afsadm&auto-loaded:krb5/krb5&auto-loaded:krb5/afsadm&auto-loaded:krb5/krb5&auto-loaded&auto-loaded:krb5/afsadm&auto-loaded&auto-loaded
__MODULES_SHARE_MANPATH   /xxxxx/xxxxxxxxxx/xxx/man:3:/xxxxx/joe/4.6/share/man:3
__MODULES_SHARE_PATH      /xxxxx/joe/4.6/bin:3:/xxxxx/xxxxxxxxx/xxx/bin:3:/xxxxx/vbuild/bin:3:/xxxxx/afsadm/bin:4



We do not use your init/bash to set up the modules but have an ~/.bashrc file that basically does 
 module () 
{ 
    { 
        eval `/xxxxx/modules/0/bin/modulecmd bash "$@"`
    } 2>&1
}
export MODULEPATH="/xxxxx/modules/0/modulefiles"
MODULEPATH="${MODULEPATH}:/xxxxx/common/modules"

and a module clear equivalent:
_LMFILES_=''; LOADEDMODULES=''; export _LMFILES_ LOADEDMODULES

Without this it doesnt seem mark things as aL at all, allthough there are module adds within the vbuild module
I guess it depends on the SHLVL how many aL are getting added but the repeation should be prevented.

**Comment by wenzler** [comment]
Nevermind - we are missing to emulate module clear properly

**Comment by xdelaruelle** [comment]
The content of the `__MODULES_LMTAG` variable in the output is inconsistent. If by any chance you could describe how the krb5/krb5 module is loaded to end up in this state, it could be interesting.

`module clear` is available and should also clear the `__MODULES_*` variables.
