### ISSUE TITLE
module('purge') seems to clobber os.environ

### ISSUE THREAD

**Issue by shareefj** [cea-hpc/modules#454]
### Describe the bug
I've just started to play with the Python interface a bit more and have found that purging all modules results in os.environ being clobbered.

### To Reproduce

```python
import os
exec(open('/apps/hosted/modules-v5.0.1/init/python.py').read())

pre = set(os.environ.keys())
module('purge')
post = set(os.environ.keys())

cr = '\n'
print(f"module('purge') clobbered the following environment variables: { cr.join(pre-post) }")
```

and the output I get is:

```console
   Unoading module gcc/gnu/latest
Unloading module common/v1.0
   Unloading module chip
   Unoading module fsdb/P-2019.06-SP1
   Unoading module gcc/arm-none-eabi/8-2019-q2-update
   Unoading module powerartist/2021R1.3p6
   Unoading module verilator/v4.214
   Unoading module gtkwave/v3.4.0
   Unoading module ncdu/v1.16
   Unoading module digital/v1.3
module('purge') clobbered the following environment variables: 
FSDBTOOLS_ROOT
LOADEDMODULES
VERILATOR_MODULE
__MODULES_LMALTNAME
PYTHONPATH
ARM_GCC_MODULE
ARM_TOOLCHAIN_BASE
VMANAGER_MODULE
__MODULES_LMPREREQ
POWERARTIST_MODULE
CDS_LIC_FILE
GTKWAVE_MODULE
DIGITAL_MODULE
GNU_GCC_MODULE
LM_LICENSE_FILE
POWERARTIST_ROOT
LICENSE_MODULE
PKG_CONFIG_PATH
LD_LIBRARY_PATH
__MODULES_LMCONFLICT
VITIS_MODULE
_LMFILES_
XCELIUM_MODULE
https_proxy
__MODULES_LMTAG
FSDB_MODULE

```

### Expected behavior
I'd expect only the Environment Modules related variables to be modified but as you can see, a much wider number of them are deleted.

### Modules version and configuration

```console
$ module --version
Modules Release 5.0.1 (2021-10-16)
```

**Comment by xdelaruelle** [comment]
Hello @shareefj 

Could you please display the environment variables defined by the modules that are unloaded by the purge command (with `module display` command). Purge should only unset the variables set by these modules.

**Comment by shareefj** [comment]
Ah!  You've hit the nail on the head there.  I thought a lot of those variables were defined outside of a modulefile but in fact we have a project wide modulefile that now sets them.  My confusion sorry...
