### ISSUE TITLE
Incorrect module modification time

### ISSUE THREAD

**Issue by baruchgu** [cea-hpc/modules#458]
### Describe the bug

The Last modification data of the "module avail -l" command is reported incorrectly when the modulefile is a symbolic link.

### To Reproduce
- build a directory when modulefiles are linked to another file
- modulefiles should have another modification date
- module use this directory
- module avail --long

Bug: The modification time belongs to the .stratus file.

```console
~/projects [260]> ls -ltA modules/stratus/
-rw-r--r--   1 xx 775 Apr  5 11:03 .stratus
lrwxrwxrwx 1 xx   8 Mar  9 17:21 21.23.100 -> .stratus
lrwxrwxrwx 1 xx   8 Dec 27 18:39 21.20.100 -> .stratus
lrwxrwxrwx 1 xx   8 Sep 30  2021 21.13.100 -> .stratus

$ module use modules/stratus/
$ module avail -C stratus -l
- Package/Alias -----------------------.- Versions --------.- Last mod. -------
modules:
stratus/21.13.100                                           2022/04/05 11:03:34
stratus/21.20.100                                           2022/04/05 11:03:34
stratus/21.23.100                                           2022/04/05 11:03:34
```

### Expected behavior

I expect to see the last mod. time of modulefile itself
```concole
$ module avail -C stratus -l
- Package/Alias -----------------------.- Versions --------.- Last mod. -------
modules:
stratus/21.13.100                                           2021/09/30 20:26:55
stratus/21.20.100                                           2021/12/27 18:39:19
stratus/21.23.100                                           2022/03/09 17:21:45
```

### Modules version and configuration

```console
$ module --version
Modules Release 5.1.0 (2022-04-30)
$ module config --dump-state
```

### Additional context

I fixed the bug in my local copy of modulecmd.tcl file, line 9156
5.1.0 variant:
```console
set mtime [file mtime $fpath]
```
My variant: 
```console
set mtime [file lstat $fpath larr; set larr(mtime)]
```
The fix was tested this way:
```console
tcl/modulecmd.tcl tcsh avail -C stratus --long
```

**Comment by xdelaruelle** [comment]
The modification time reported is the one of the file behind the symbolic link as it is the content of this file which is evaluated.

If the `.stratus` file is updated after the symbolic link creation, it is important to show users the modification time of the `.stratus` file. Otherwise users will only see the creation time of the symbolic link which does not reflect that the content of the modulefile has changed.

**Comment by xdelaruelle** [comment]
I am closing this issue as the current behavior of Modules appears to be consistent regarding symbolic link and modification time report.

Many thanks for your report.

**Comment by baruchgu** [comment]
Dear.
I see your concept.
But from my point of view the expected behavior is as was described in the
ticket. My users and I want to see the date of the new version of stratus
But now we see all versions with the same date, when I have five or more
stratus versions since 2015, all are seen with the same old date.
Is there an option to modify the date behavior format by a flag/variable?
I personally changed the TCL code in my installation.

-- תודה מראש, ברוך

**Comment by xdelaruelle** [comment]
You can use the [`siteconfig.tcl` configuration file](https://modules.readthedocs.io/en/latest/INSTALL.html#configuration), to supersede the upstream version of the `getFileMtime` procedure with your own flavor.

You can set the following code in `siteconfig.tcl`:

```tcl
rename ::getFileMtime {}
# get file modification time, cache it at first query, use cache afterward
proc getFileMtime {fpath} {
   if {[info exists ::g_fileMtime($fpath)]} {
      return $::g_fileMtime($fpath)
   } else {
      # protect 'file mtime' call in case we do not know what we are checking
      # when mcookie is not checked
      if {[catch {
         set mtime [file lstat $fpath larr; set larr(mtime)]
      } errMsg ]} {
         reportError [parseAccessIssue $fpath]
         set mtime {}
      }
      return [set ::g_fileMtime($fpath) $mtime]
   }
}
```
