### ISSUE TITLE
Family

### ISSUE THREAD

**Issue by zzxtty** [cea-hpc/modules#465]
### Describe the bug

Using a dash in a module name causes an error when using family in the module file.

### To Reproduce

Add the following to the module file:

```
family bids-validator
```
This results in:

```
% module load bids-validator
Loading bids-validator/1.9.5
  Module ERROR: Invalid family name 'bids-validator'
        while executing
    "family bids-validator"
        (file "/software/system/modules/NaN/el8/bids-v'alidator/1.9.5" line 7)
    Please contact <root@localhost>
%
```

Changing "family" in the module file to "conflict" resolves the issue, as does removing the dash.

### Modules version and configuration

```
Modules Release 5.1.1 (2022-05-31)
```

**Comment by xdelaruelle** [comment]
As indicated in [family](https://modules.readthedocs.io/en/latest/modulefile.html#mfcmd-family) documentation:

> name should be a non-empty string only containing characters that could be part of an environment variable name (i.e., [a-zA-Z0-9_]).


`family` creates an environment variable named `MODULES_FAMILY_<NAME>`. So *name* should not contain a dash character as it is not accepted in env var name on most shells.

```console
$ export FOO-BAR=test
bash: export: `FOO-BAR=test': not a valid identifier
```

**Comment by zzxtty** [comment]
Oops, I managed to completely blanked that last line in the documentation. I guess that will teach me not to rush out bug reports a few minutes before a 3 hour meeting.

Thanks for the quick response.
