### ISSUE TITLE
`pushenv` does not reset envvar value on unload

### ISSUE THREAD

**Issue by mfontanaar** [cea-hpc/modules#467]
### Describe the bug
I'm new to Modules, and I'm trying to write a modulefile that loads a library into the environment. Consequently, I have to append to `CPPFLAGS` (for example) the new `include` path. I first tried it doing `prepend-path` with `" "` as delimiter, however `CPPFLAGS` wasn't reverting on module unload.

I then decided to try the `pushenv` function. However, once again, envvar isn't changed on unload.

### To Reproduce
1. Sample `modulefile` named `base-environment`

```
#%Module1.0#####################################################################
 ##
 ## Base environment modulefile
 ##
 proc ModulesHelp { } {
          puts stderr "\t Example"
  }
 
 module-whatis   "Loads zlib"
 
 # zlib
 set __mypath__                      /home/mafontana/opt/zlib/1.2.12
 prepend-path    LD_LIBRARY_PATH     $__mypath__/lib
 pushenv         LDFLAGS             "[getenv LDFLAGS] -L$__mypath__/lib"
 pushenv         CPPFLAGS            "[getenv CPPFLAGS] -I$__mypath__/include"
 pushenv         CFLAGS              "[getenv CFLAGS] -I$__mypath__/include"
 prepend-path    MANPATH             $__mypath__/share/man
```

2. `echo $CPPFLAGS` (result: empty in my case, not important)
3. `module load base-environment` (loads without errors)
4. `echo $CPPFLAGS` (result: path was added)
5. `module unload base-environment` (unloads without errors)
6. `echo $CPPFLAGS` (result: path still present; expected: path removed)

Should also note that, for instance, `$PATH` is correctly reset. `$__MODULES_PUSHENV_CPPFLAGS` still exists and it is fully populated.

### Modules version and configuration
Modules 5.1.1 compiled from fresh tarball from `sourceforge.net`.
No `modulesrc` file.

**Comment by xdelaruelle** [comment]
Hello @mfontanaar,

The issue you get comes from the use of the environment variable value (with `getenv`) to update the environment variable value.

When unloading the modulefile, Modules unsets the value defined on the `pushenv` command. But since `CPPFLAGS` is set to ` -L$__mypath__/lib`, Modules tries to unset the value ` -L$__mypath__/lib  -L$__mypath__/lib`. It does not find this value set on `CPPFLAGS`, so nothing is unset.

I would suggest to use the `append-path` command to add content to these variables:

```tcl
append-path -d { } LDFLAGS -L$__mypath__/lib
```

It correctly unsets the value when module is unloaded:

```console
$ echo $LDFLAGS

$ module load ./test
$ echo $LDFLAGS
-L/home/mafontana/opt/zlib/1.2.12/lib
$ module unload ./test
$ echo $LDFLAGS

$
```

**Comment by mfontanaar** [comment]
Hello @xdelaruelle ,

Thanks a lot for the answer. It was very quick! I get the flaw in my logic. I tried appending like you suggest but had the same issue. Will try to do it exactly like you posted and report back. In the meantime, as `pushenv` seems to be working as expected, I'm marking closed and removing bug tag.

If you happen to want to change the title to something easier to find for someone doing the same mistake just let me know.

Kind regards,
Mauro
