### ISSUE TITLE
Architecture issues on M1 Mac

### ISSUE THREAD

**Issue by leibomg1** [cea-hpc/modules#474]
❯ source /usr/local/Modules/init/zsh
ERROR: dlopen(/usr/local/Modules/lib/libtclenvmodules.dylib, 0x000A): tried: '/usr/local/Modules/lib/libtclenvmodules.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
      while executing
  "load [file normalize [getConf tcl_ext_lib]] Envmodules"
  Please report this issue at https://github.com/cea-hpc/modules/issues

**Comment by xdelaruelle** [comment]
Seems the same issue as #468.

It seems that x86_64 version of libraries are installed instead of arm64 version.

Please see https://github.com/cea-hpc/modules/issues/468#issuecomment-1219383114
