### ISSUE TITLE
Update Modules from 5.1.1 to 5.2.0 ....

### ISSUE THREAD

**Issue by ZXRobotum** [cea-hpc/modules#478]
Hello all,
Today I have updated from 5.1.1 to 5.2.0 on 2 computers and on both computers I get the following error message when I log on to the computer again:

ERROR: missing close-bracket
      while executing
  "set ::["
      invoked from within
  "interp eval $itrp set ::$var "{$val}""
      (procedure "execute-modulefile" line 111)
      invoked from within
  "execute-modulefile $modfile $modname $modnamevr $mod 0 0"
      (procedure "cmdModuleSource" line 30)
      invoked from within
  "cmdModuleSource load {/usr/local/Modules/Module.Base/etc/initrc}"
      (procedure "cmdModuleAutoinit" line 62)
      invoked from within
  "cmdModuleAutoinit"
      (procedure "module" line 333)
      invoked from within
  "{*}$execcmdlist"

My "siteconfig.tcl" seems like this:
set modulefile_extra_vars {\
   OS [string map {{ } _} [exec lsb_release -s -i]]\
   OSRELEASE [string map {{ } _} [exec lsb_release -s -r]]\
   ARCH $::tcl_platform(machine)\
}

my "initrc" seems like this:
module use {/HumanBrain.Projects/xCloud/HumanBrain.Modules/$ARCH}
module use --append {/HumanBrain.Projects/xCloud/HumanBrain.Modules/Scientific/$ARCH}
module use --append {/HumanBrain.Projects/xCloud/HumanBrain.Modules/Scientific/$OS/$OSRELEASE/$ARCH}

Best regards from Berlin.....

Z. Matthias

**Comment by xdelaruelle** [comment]
Hello,

The way `modulefile_extra_vars` variable is set is not good:
* commands have to be executed, so list cannot be defined with `{}`
* backslash character has to be set at the end of each line to define list on multiple lines

So `modulefile_extra_vars` variable should be defined this way:
```tcl
set modulefile_extra_vars [list\
   OS [string map {{ } _} [exec lsb_release -s -i]]\
   OSRELEASE [string map {{ } _} [exec lsb_release -s -r]]\
   ARCH $::tcl_platform(machine)\
]
```

Also the `initrc` should be rewritten to resolve the $ARCH, $OS and $OSRELEASE variable: when enclosed in `{}` a $NAME is not resolved

```tcl
module use /HumanBrain.Projects/xCloud/HumanBrain.Modules/$ARCH
module use --append /HumanBrain.Projects/xCloud/HumanBrain.Modules/Scientific/$ARCH
module use --append /HumanBrain.Projects/xCloud/HumanBrain.Modules/Scientific/$OS/$OSRELEASE/$ARCH
```

Best regards,
Xavier
