### ISSUE TITLE
Cannot create directory: no space left on device

### ISSUE THREAD

**Issue by rzhangv** [cea-hpc/modules#482]
I am a new user of CCRT, and I cannot create directory: no space left on device.
Thank you in advance!
![CCRT](https://user-images.githubusercontent.com/122330509/211446082-50cd148d-660c-4523-849d-eb9896d1d062.JPG)

**Comment by xdelaruelle** [comment]
There is an issue on the underlying storage system. I have forwarded your issue to the TGCC-CCRT staff: they will take this issue into account and will contact you back.

Here I will make a fix for module to trap this error differently.
