### ISSUE TITLE
MODULEPATH aware module-tag use

### ISSUE THREAD

**Issue by wenzler** [cea-hpc/modules#485]
### Is your feature request related to a problem? Please describe.
No.
But module-tag requires not a file name but module name/alias as parameter.
Thus it is not aware of the same module name being available in a different MODULEPATH repos.

### Describe the solution you'd like
Allow definition of the actual filename (as in module display)
module-tag "Patched" /root/common/modules/git/1.0

Would also be good to have the tags displayed in the module display output ,btw :)

### Describe alternatives you've considered
Joining the space marines to seek out new life and new civilizations

### Additional context
Tested in 5.2.0

Thanks!

**Comment by wenzler** [comment]
The module-tag via etc/initrc has also high impact on the loading time of modules
With 1300 modules tagged, it increases from 40ms to 120ms

This should only affect module list and module avail commands.

**Comment by xdelaruelle** [comment]
Could you provide an exemple setup (with initrc) to test such high loading
time?

Regards,
Xavier

**Comment by xdelaruelle** [comment]
Comment about performance issue has been removed so I assume this issue has been solved on your side. If you still have an issue, please open a separate ticket to distinguish from this feature request.

`script/mb` utility from this git repository helps to know the performance one can expect from various sub-commands.

**Comment by wenzler** [comment]
Hey, sorry for late response
performance only suffers with thousands of different tags
Had added one module-tag line per module with identical tags first ;)

Would still be nice to have the module-tag accept MODULEPATH specific paths 

Cheers

**Comment by xdelaruelle** [comment]
Ability to specify modules with their full path file name on `module-tag`, `module-hide` and `module-forbid` has been developed. It will be part of the next feature release (5.4) that I plan to publish before the end of this year. Code will be integrated to main git branch once 5.3.1 bugfix release will be published.
