### ISSUE TITLE
support version built from latest repo source code

### ISSUE THREAD

**Issue by Passw** [cea-hpc/modules#486]
I compiled `modules` from the latest `main` branch source code.

When load the modulefiles, it pops out error:
```
Module ERROR: Modulefile requires at least Modules version 5.0
  In '/INSTALL/Modules/etc/initrc'
  Please contact <root@localhost>
```

```
module --version
Modules Release  (2023-02-27)
```

Could we add version flag like `latest` or `repo`  to meet the version checking, when using the latest repo source code `module` to load modulefiles ?

**Comment by xdelaruelle** [comment]
Could you describe how modules is retrieved, compiled then installed.

Version number seems empty on your setup, which causes the Module ERROR.

On such setup, version number should be equal to 5.2.0+xxxxx

**Comment by xdelaruelle** [comment]
Regarding `MODULES_BUILD_DATE`, *BUILD* is referring to the code modification in the repository, not the assembly process.

I will look at how to compute a `MODULES_BUILD` string even when only the last commit is checked out.
