### ISSUE TITLE
gitlog2changelog.py fails with non-default Git configuration

### ISSUE THREAD

**Issue by michaelkuhn** [cea-hpc/modules#487]
### Describe the bug

When trying to build the main branch, `gitlog2changelog.py` failed with:
```
Traceback (most recent call last):
  File "$SPACK_STAGE/spack-src/script/gitlog2changelog.py", line 55, in <module>
    date = dateList[1]
           ~~~~~~~~^^^
IndexError: list index out of range
```

This seems to be due to my `.gitconfig` containing:
```
[format]
  pretty = fuller
```

### To Reproduce

Requires: https://github.com/spack/spack/pull/36268

```console
$ spack install environment-modules@main target=x86_64
```

### Expected behavior

`gitlog2changelog.py` should also work with non-default configurations.

### Error and debugging information

n/a

### Modules version and configuration

n/a

### Additional context

n/a

**Comment by xdelaruelle** [comment]
Many thanks for this issue report.
