### ISSUE TITLE
application-specific initialization failed: Can't find a usable init.tcl in the following directories: 

### ISSUE THREAD

**Issue by margemc** [cea-hpc/modules#489]
Simnibs/4.0.0 not loading due to init.tcl failure. error output below. 

[mlm144@blade24 Preprocessing]$ module load simnibs/4.0.0
[mlm144@blade24 Preprocessing]$ module list
application-specific initialization failed: Can't find a usable init.tcl in the following directories: 
    simnibs_env/lib/tcl8.6 /usr/lib/tcl8.6 /lib/tcl8.6 /usr/library /library /tcl8.6.12/library /tcl8.6.12/library

This probably means that Tcl wasn't installed properly.

WARNING: terminal is not fully functional
Press RETURN to continue 
Currently Loaded Modulefiles:
ERROR: invalid command name "tcl::mathfunc::max"
      while executing
  "tcl::mathfunc::max [expr {int(($tty_cols -  $elt_prefix_len) / $max_len)}] 0"
      (procedure "displayElementList" line 58)
      invoked from within
  "displayElementList $header $hsgrkey $hstyle $one_per_line $show_idx $display_list $len_list $max_len"
      (procedure "reportModules" line 123)
      invoked from within
  "reportModules {} $header {} terse $show_mtime $show_idx $one_per_line $theader_cols loaded $loadedmodlist"
      (procedure "cmdModuleList" line 47)
      invoked from within
  "cmdModuleList $show_oneperline $show_mtime"
      (procedure "module" line 282)
      invoked from within
  "{*}$execcmdlist"
  Please report this issue at https://github.com/cea-hpc/modules/issues

**Comment by xdelaruelle** [comment]
Tcl should be properly installed to be able to use Modules.

How is Tcl installed on your system? Do you define specific `TCL_*` environment variable in your environment?

**Comment by xdelaruelle** [comment]
Without more information, I cannot help. From your initial message, what I understand is that there is an issue with the installation of Tcl.
