### ISSUE TITLE
Space added after modulename/ under bash completion

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#490]
On Modules 5.2, when available module name completion is triggered under bash shell, a space is added after completion of root module name. As word is completed with only the top module name, it is not possible to complete the fully qualified module name.

For instance, with `foo/1.2` and `foo/2.1` modules. When typing "module avail f<tab>", it completes into "module avail foo/ ".

The extra space needs to be removed to continue completion until full name completion.

**Comment by adrien-cotte** [comment]
Thank you Xavier!
