### ISSUE TITLE
no configure file under /environment-modules when using sudo apt-get install environment-modules

### ISSUE THREAD

**Issue by thomasmessi19** [cea-hpc/modules#493]
Please use preferably the Modules mailing-list to post question:

> https://sourceforge.net/projects/modules/lists/modules-interest

Hi,
I use apt-get to download environment-modules 5.0.1. But I see many files are missing under /environment-modules including configure file. Why is that? only files there are:

/etc/environment-modules$ ls
initrc  modules  modulespath  site.exp  siteconfig.tcl

I assume this is a rookie question, but please help :)

**Comment by xdelaruelle** [comment]
Hi,                                                                                                      

When using `apt-get install` you install the `environment-modules` package which has been pre-configured. You should find the following content in this package (it may vary depending on the Debian version you use):
                                                                                                         
https://packages.debian.org/bookworm/amd64/environment-modules/filelist                                  
                                                                                                         
When installed with `apt-get`, you will not find the installation files of environment-modules (`configure` or `Makefile`). These files are not needed once installed, that is why they are not shipped in the package (you do not need them to use environment-modules once installed).

The content you list in the configuration directory (`/etc/environment-modules`) seems correct.

To go further in the configuration of environment-modules, you can follow the [configuration guidelines](https://modules.readthedocs.io/en/latest/INSTALL.html#configuration), resuming at step 2 (step 1 has already been achieved when installing the package).
