### ISSUE TITLE
How to disable the info "module load XXX" at 5.X？

### ISSUE THREAD

**Issue by MIngPAPA** [cea-hpc/modules#501]
Hello,
I am an old friend of environment module 3.2. When I recently changed it to the 5.X version, it gave some info to tell me I was loading XXX module file.  
I don‘t want the loading info, how can I suppress it? 
What are the relevant keywords in configuration?

**Comment by xdelaruelle** [comment]
Hello,

I suggest that you look at the [verbosity](https://modules.readthedocs.io/en/latest/module.html#mconfig-verbosity) configuration option. A description of the different verbosity level is available [here](https://modules.readthedocs.io/en/latest/module.html#envvar-MODULES_VERBOSITY). The `concise` level disable the informational messages.

**Comment by MIngPAPA** [comment]
Thanks for your useful information! That works！
