### ISSUE TITLE
No error when purging sticky modules

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#502]
Currently an error is raised when doing a `module purge` if some sticky modules are loaded.

This is done as `purge` should result in an empty loaded module list.

But some users may find this error disturbing as sticky module cannot be unloaded, so purge has performed well.

A configuration option may be introduced to change error into warning (or even no message at all) when hitting a sticky module during a module purge.

**Comment by adrien-cotte** [comment]
I agree this option should have 3 options:
- error (message + code 1)
- warning (message + code 0)
- silent (no message + code 0)
