### ISSUE TITLE
Skip some environment definitions on source-sh

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#503]
When sourcing a script into a modulefile with `source-sh` command it may be useful to skip some kind of definitions (among environment variables, shell alias, shell function, shell completion and directory change)

**Comment by bkatkam123** [comment]
I think, it's better to export functions only when they are marked for export with 'export -f function_name'. All internal functions may not be useful.

**Comment by xdelaruelle** [comment]
> I think, it's better to export functions only when they are marked for export with 'export -f function_name'. All internal functions may not be useful.

The idea of `source-sh` is to get the current environment defined as if shell script was sourced in current shell session. If internal functions are ignored, resulting environment will be different than if script was just sourced. I fear that something will get broken if non-exported function are ignored by `source-sh`.
