### ISSUE TITLE
Very bad performance due to sourcing of all modules on module add

### ISSUE THREAD

**Issue by wenzler** [cea-hpc/modules#507]
### Describe the bug
A module add call has bad performance in a directory with large numbers of modules
strace shows openat/read calls for every module - not only the one added.

### To Reproduce
Have many modules in /modules/python

MODULEPATH=/modules sh -c 'time /usr/bin/tclsh /apps/modulestcl/5.3.1/libexec/modulecmd.tcl sh add python/3.11.4

```
pid 1056601] openat(AT_FDCWD, "/modules/python/anothermodulethatisnottheoneadded", O_RDONLY) = 5
[pid 1056601] fcntl(5, F_SETFD, FD_CLOEXEC) = 0
[pid 1056601] ioctl(5, TCGETS, 0x7fff89addc50) = -1 EINVAL (Invalid argument)
[pid 1056601] read(5, "#%Module1.0\n\nset               software                \"python\"\nset  
```
This repeats for all files present in the /modules/python dir
The module add time to directories with little number of files is significantly lower.

### Expected behavior
Just open the actual module file and parse it

### Modules version and configuration

```console
$ module config --dump-state

Modules Release 5.3.1 (2023-06-27)

- Config. name ---------.- Value (set by if default overridden) ---------------
advanced_version_spec     0 (env-var)
auto_handling             0
avail_indepth             1
avail_output              modulepath:alias:dirwsym:sym:tag:variantifspec:key
avail_terse_output        modulepath:alias:dirwsym:sym:tag:variantifspec
cache_buffer_bytes        32768
cache_expiry_secs         0
collection_pin_tag        0
collection_pin_version    0
collection_target         <undef>
color                     never
colors                    hi=1:db=2:tr=2:se=2:er=91:wa=93:me=95:in=94:mp=1;94:di=94:al=96:va=93:sy=95:de=4:cm=92:aL=100:L=90;47:H=2:F=41:nF=43:S=46:sS=44:kL=30;48;5;109
contact                   'foo@bar'
csh_limit                 4000
editor                    vi
extended_default          1
extra_siteconfig          <undef>
home                      /apps/modulestcl/5.3.1
icase                     search
ignore_cache              0
ignore_user_rc            0
ignored_dirs              CVS RCS SCCS .svn .git .SYNC .sos
implicit_default          1
implicit_requirement      0
list_output               header:idx:variant:sym:tag:key
list_terse_output         header
locked_configs            
mcookie_check             always
mcookie_version_check     1
ml                        1
nearly_forbidden_days     14
pager                     
protected_envvars         <undef>
quarantine_support        0
rcfile                    <undef>
redirect_output           1
reset_target_state        __init__
run_quarantine            <undef>
search_match              starts_with
set_shell_startup         0
shells_with_ksh_fpath     
silent_shell_debug        0
siteconfig                /apps/modulestcl/5.3.1/etc/siteconfig.tcl
tag_abbrev                auto-loaded=aL:loaded=L:hidden=H:hidden-loaded=H:forbidden=F:nearly-forbidden=nF:sticky=S:super-sticky=sS:keep-loaded=kL
tag_color_name            
tcl_ext_lib               /apps/modulestcl/5.3.1/lib/libtclenvmodules.so
tcl_linter                nagelfar.tcl
term_background           dark
term_width                0
unload_match_order        returnlast
variant_shortcut          
verbosity                 concise
wa_277                    0

- State name -----------.- Value ----------------------------------------------
always_read_full_file     1
autoinit                  0
clock_seconds             1693915006
cmdline                   /apps/modulestcl/5.3.1/libexec/modulecmd.tcl sh config --dump-state
commandname               config
domainname                domain
error_count               0
extra_siteconfig_loaded   0
false_rendered            0
force                     0
hiding_threshold          0
inhibit_errreport         0
inhibit_interp            0
init_error_report         1
is_stderr_tty             0
is_win                    0
kernelversion             #1 SMP 
lm_info_cached            0
machine                   x86_64
modulefile                {}
nodename                  hostname
os                        Linux
osversion                 4.18.0
paginate                  0
path_separator            :
report_format             regular
reportfd                  stderr
return_false              0
shell                     sh
shelltype                 sh
siteconfig_loaded         1
sub1_separator            &
sub2_separator            |
subcmd                    config
subcmd_args               --dump-state
supported_shells          sh bash ksh zsh csh tcsh fish cmd tcl perl python ruby lisp cmake r
tcl_ext_lib_loaded        0
tcl_version               8.6.8
term_columns              282
timer                     0
usergroups                users
username                  user

- Env. variable --------.- Value ----------------------------------------------
MODULEPATH                /modules
MODULES_ADVANCED_VERSION_SPEC 0
```

### Additional context
Also applicable to version 5.2.0

Please also note that lstat calls on AFS filesytems (where the modules reside) are veeeeery slow compared to stat calls.
Old modules versions did not have any bad performance on module add, even when caching did not kick in.  So please try to avoid lstat for performance as well, where not really needed.

**Comment by xdelaruelle** [comment]
Hi @wenzler 

It seems the Tcl extended library is not enabled on your setup:

```
tcl_ext_lib_loaded        0
```

Could you please redo your test with a Modules version where [Tcl extended library is enabled](https://modules.readthedocs.io/en/latest/INSTALL.html#instopt---enable-libtclenvmodules).

This lib supersedes the open and read functions of Tcl specifically to avoid the many lstat, fnctl and ioctl calls.

It would be interested to have in your case the number of io calls (given by strace -c) with and without the Tcl extended library.

**Comment by wenzler** [comment]
We kept it off for portability.
Will update you on that.

Lack of tclenvmodules doesn't really explain why it has to open all neighboring files on a properly match-able single module load, though.

**Comment by wenzler** [comment]
No real change in performance - module loads take extensively long in both configs
````
normal build:

% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
67.05    0.319764        3852        83        37 wait4
11.26    0.053696          10      4889         2 lstat
  3.05    0.014548          10      1324           readlink
  2.99    0.014261           9      1470           read
  2.48    0.011810          15       779       115 openat
  1.99    0.009513          12       765       102 stat
  1.71    0.008141           8       922        14 close


lib build:

82.24    0.378750        4563        83        37 wait4
  2.70    0.012430           8      1471           read
  2.21    0.010171          13       778       115 openat
  1.81    0.008335          11       756       102 stat
  1.74    0.008034           8       921        14 close

````
[modules531-local_build-state-add-python.strace.txt](https://github.com/cea-hpc/modules/files/12524990/modules531-local_build-state-add-python.strace.txt)
[modules531-local_build-libtclenvmodules-state-add-python.strace.txt](https://github.com/cea-hpc/modules/files/12524991/modules531-local_build-libtclenvmodules-state-add-python.strace.txt)

**Comment by wenzler** [comment]
Give me some more time to come back on this

**Comment by xdelaruelle** [comment]
@wenzler any news?

**Comment by wenzler** [comment]
I still have to find the time to anonymize the debug output.

But the opening of all module files in a folder takes 1ms each - which ofc accumulates for large folders.

Thus the basic complaint remains: 
why does modules have to open every appver file present in the folder
 for a distinct 'module add appname/appver' call

**Comment by xdelaruelle** [comment]
> Thus the basic complaint remains:
why does modules have to open every appver file present in the folder
for a distinct 'module add appname/appver' call

See my earlier comment in https://github.com/cea-hpc/modules/issues/507#issuecomment-1706695023: neighboring files are analyzed to determine the properties of the loading module. Especially to determine if the `@latest` symbol applies to it.

**Comment by xdelaruelle** [comment]
> Could you provide the output of the module add command in verbose2 mode (-DD). It could also be interesting to run this verbose2 command with --timer option.
> 
> There are ~700 files read. It will be interesting to see what files are read within the enabled modulepaths and what are the duration of these file reads.

@wenzler any news? debug output would be interesting to see what files are read.

Above strace's stats mention ~700 files for a module load. Cannot be sure without debugging output, but I think there are non-modulefiles stuff in modulepath directories. Moving the non-modulefiles stuff away from modulepath directory will help (or build module cache if Modules >= 5.3).

**Comment by dilipzt** [comment]
I will follow-up now onwards on this

**Comment by xdelaruelle** [comment]
I am closing this issue. With the element provided, module command seem to perform as expected. More modulefiles are read by newer version of Modules but it should not impact performances.

A large number of files is read here. I am lacking information but I would suggest to look at the files inside the modulepaths and remove non modulefiles.

If the filesystem where the modulefiles are located does not cope well with the load implied by module command I/O operations, suggestion is to enable the [module cache](https://modules.readthedocs.io/en/latest/MIGRATING.html#module-cache).
