### ISSUE TITLE
module load python error: "Tcl wasn't installed properly" 

### ISSUE THREAD

**Issue by niaberrian** [cea-hpc/modules#512]
### Describe the bug
After running "module load python" on my computer cluster, I received the error: ERROR: Can't find a usable init.tcl in the following directories:
      /software/fsl-6.0.6.2/lib/tcl8.6 /usr/lib/tcl8.6 /lib/tcl8.6 /usr/library /library /tcl8.6.12/library /tcl8.6.12/library

### To Reproduce

```console
$ module load fsl/6.062
$ module load python
...
```

Location and content of any modulerc or modulefile involved: /project2/abcd

```console
$ cat path/to/modulepath/module/version
$ cat path/to/modulepath/module/.modulerc
$ cat path/to/modulepath/.modulerc
...
```

### Expected behavior
I expected to be able to use python to run a script in a compute node. 

### Modules version and configuration

```console
$ module --version
$ module config --dump-state
```

**Comment by xdelaruelle** [comment]
It seems like a Tcl installation issue. Could you precise how Tcl has been installed on your system. 

Is there specific TCL_* environment variable defined in your environment?

Issue #489 was about the same thing, but it was not possible to clarify it due to the lack of information.

More information is also expected here to be able to help.

**Comment by xdelaruelle** [comment]
Hello,

I suggest you print the `module` shell function definition in your shell session:

```console
$ type module
```

Extract from the obtained output the location of the `tclsh` command configured to run the `modulecmd.tcl`.

Try to execute this `tclsh` command directly. You should obtain the same error as mentioned previously.

Then I suggest you report this error to the people in charge of your university cluster. They should fix the Tcl installation for Environment Modules to correctly operate.
