### ISSUE TITLE
How to cite "module"?

### ISSUE THREAD

**Issue by cmeesters** [cea-hpc/modules#529]
Hi,

Has this software ever been published? I wonder how to cite it in a paper? 

Cheers,
Christian

PS Sorry, I do not want to subscribe to yet another list. 

Please use preferably the Modules mailing-list to post question:

> https://sourceforge.net/projects/modules/lists/modules-interest

**Comment by xdelaruelle** [comment]
Hi Christian,

Modules was published on 1991. This founding paper can be cited the following way:

John L. Furlani, [Modules: Providing a Flexible User Environment](http://modules.sourceforge.net/docs/Modules-Paper.pdf) *Proceedings of the Fifth Large Installation Systems Administration Conference (LISA V)*, pp. 141–152, San Diego, CA, September 30 - October 3, 1991.

Cheers,
Xavier

**Comment by cmeesters** [comment]
Hi Xavier,

Thank you so much! I was hoping for you, that something more recent was published. But I know its hard to publish an update for software. 

Cheers
Christian

PS As a follow-up to our conversation a few years ago: Our site still uses lmod. Some tides change slowly, indeed.
