### ISSUE TITLE
Facing error with envsetup.sh 

### ISSUE THREAD

**Issue by Ranjana-Mattur** [cea-hpc/modules#530]
I face the below error when I source envsetup.sh . Can you please help as this is blocking my tasks.
Thanks.

Path : /google/gchips/workspace/redondo-us/cbf/shared/tvspe-diag-1/mattur/WORK_TILHI/tilhi_wa_2024_04_01/repo/tilhi/envsetup.sh

#####################################################################################
**ERROR: Can't find a usable init.tcl in the following directories: 
      /root/AllianceATE/GTKWave/lib/tcl8.5 /usr/lib/tcl8.5 /lib/tcl8.5 /usr/library /library /tcl8.5.15/library /tcl8.5.15/library
  
  
  
  This probably means that Tcl wasn't installed properly.**
  
      while executing
  "error $msg"
      (procedure "tclInit" line 61)
      invoked from within
  "tclInit"
      invoked from within
  "interp create $itrp"
      (procedure "execute-modulerc" line 34)
      invoked from within
  "execute-modulerc $dir/$elt $elt $elt"
      (procedure "getModules" line 95)
      invoked from within
  "getModules $dir $mod 0 [list rc_defs_included resolve]"
      (procedure "getPathToModule" line 49)
      invoked from within
  "getPathToModule $mod {} $notfounderr"
      (procedure "cmdModuleLoad" line 24)
      invoked from within
  "cmdModuleLoad load 1 {*}$args"
      (procedure "module" line 123)
      invoked from within
  "{*}$execcmdlist"
  Please report this issue at https://github.com/cea-hpc/modules/issues
application-specific initialization failed: Can't find a usable init.tcl in the following directories: 
    /root/AllianceATE/GTKWave/lib/tcl8.5 /usr/lib/tcl8.5 /lib/tcl8.5 /usr/library /library /tcl8.5.15/library /tcl8.5.15/library

#######################################################################################

**Comment by Ranjana-Mattur** [comment]
I face this issue only on the NC terminals. Otherwise on the regular
terminal I dont see this issue.
Please let me know if I have to open this bug with the infra team.

When I run tclsh on regular terminal it works fine. On NC terminal I see
the below error.

application-specific initialization failed: Can't find a usable init.tcl in
the following directories:
    /root/AllianceATE/GTKWave/lib/tcl8.5 /lib/tcl8.5 /lib/tcl8.5 /library
/library /tcl8.5.15/library /tcl8.5.15/library



This probably means that Tcl wasn't installed properly.


Thanks,
Ranjana

**Comment by xdelaruelle** [comment]
Tcl is not properly installed which breaks Modules. I suggest you to report this issue to your infra team.

You may see this error when you connect to the NC terminal if `module` command is used in the shell initialization process.

**Comment by Ranjana-Mattur** [comment]
Sure. Will report the issue to the infra team.


Thanks,
Ranjana
