### ISSUE TITLE
How to run `module` from Ruby script

### ISSUE THREAD

**Issue by fplazaonate** [cea-hpc/modules#535]
### Describe the bug
Hi,
I would like to initialize Environment Modules from a ruby script.
I have tried to import the file "/usr/share/modules/init/ruby.rb".
After that, I can't call the module function because it is a reserved keyword in ruby.
### To Reproduce

1 - Create a test.rb script with the following content
```
# Load the Environment Modules system into Ruby
require '/usr/share/modules/init/ruby.rb'

# Example usage: Load a module
module('load python')
```

2 - Execute the script
```
$ruby test.rb
test.rb:5: syntax error, unexpected '\n', expecting '.' or &. or :: or '['
module('load python')
```

**Comment by xdelaruelle** [comment]
Hello Florian,

As you say, `module` is a specific keyword in Ruby. So module is defined for this language as a `module` method from the `ENVModule` class.

Some usage example:

```ruby
require '/usr/share/Modules/init/ruby.rb'
ENVModule.module('list')
ENVModule.module('load', '-v', 'dot')
ENVModule.module('list')
```

Output of this script

```console
$ ruby test.rb
No Modulefiles Currently Loaded.
Loading dot
Currently Loaded Modulefiles:
 1) dot
```

I will update the documentation to provide this example.
