### ISSUE TITLE
List of environment variables needed for "modules"

### ISSUE THREAD

**Issue by cmeesters** [cea-hpc/modules#538]
Hi,

I am trying to make the SLURM-Executor for Snakemake more stable to submit jobs within job context (this work would affect executors for other batch systems, too). For this, I need to know the list of environment variables set and needed by "modules".

Alas, on our cluster, I am only able to check for lmod env variables.

Can somebody please paste all the list of environment variables used by modules, here? (Perhaps an output of `env | grep <prefix>`, but I do not even remember, whether there is a common prefix ...)

Thank you so much in advance!

Christian

**Comment by xdelaruelle** [comment]
Hi Christian,

All the environment variables set by or needed by Modules are listed at:
https://modules.readthedocs.io/en/latest/module.html#environment

In a concise way:
* ``__MODULES_*``
* ``_LMFILES_``
* ``LOADEDMODULES``
* ``MODULECONTACT``
* ``MODULEPATH``
* ``MODULERCFILE``
* ``MODULES_*``
* ``MODULESHOME``

If you also want to support older version of Modules (version 4), you should also add:

* ``*_modquar``
* ``*_modshare``

Regards,
Xavier

**Comment by cmeesters** [comment]
Hi Xavier,

Thank you so much! 

Regards,
Christian
