### ISSUE TITLE
Installation issue with macOS 15.0.1 and Xcode 16.0

### ISSUE THREAD

**Issue by rakeshphys** [cea-hpc/modules#551]
I am trying to install this software on my MacBook Air (Apple Chip M3, macOS 15.0.1, Xcode 16.0) using the following steps:

curl -LJO https://github.com/cea-hpc/modules/releases/download/v5.4.0/modules-5.4.0.tar.gz
tar xfz modules-5.4.0.tar.gz
cd modules-5.4.0
./configure --prefix=/opt/modules --with-tcl=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Tcl.framework/
make
sudo make install

After configuration, I get the following message
```
~/Downloads/modules-5.4.0
--------------------------------------------------
creating ./Makefile.inc
creating ./site.exp
```

The configuration is okay, I guess. But, the make step throws the following warnings and errors:

```
ld: warning: -single_module is obsolete
ld: warning: ignoring file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Tcl.framework/Versions/8.5/libtclstub8.5.a': fat file missing arch 'arm64', file has 'x86_64,arm64e'
Undefined symbols for architecture arm64:
  "_Tcl_InitStubs", referenced from:
      _Envmodules_Init in envmodules.o
  "_tclStubsPtr", referenced from:
      _Envmodules_GetFilesInDirectoryObjCmd in envmodules.o
      _Envmodules_ReadFileObjCmd in envmodules.o
      _Envmodules_ReadFileObjCmd in envmodules.o
      _Envmodules_InitStateUsernameObjCmd in envmodules.o
      _Envmodules_InitStateUsergroupsObjCmd in envmodules.o
      _Envmodules_InitStateUsergroupsObjCmd in envmodules.o
      _Envmodules_InitStateClockSecondsObjCmd in envmodules.o
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libtclenvmodules.dylib] Error 1
make: *** [lib/libtclenvmodules.dylib] Error 2
```

I also have an Intel-based MacBook Pro and had no trouble in installing the module software when I took the above procedure. Please provide a working solution to resolve the above installation problem.

**Comment by xdelaruelle** [comment]
Hello @rakeshphys,

From the error you obtain, it seems that the installed Tcl version you try to use is compiled for `x86_64,arm64e`. You are trying to compile Modules for arch `arm64` which cannot use the Tcl version you have selected.

You have two solutions, either:
* using or installing a Tcl version coping with arch `arm64`
* compiling Modules for arch `x86_64` or `arm64e`

You may also install Modules without its Tcl extension library. This way you can install Modules without compiling anything. Use the `--disable-libtclenvmodules` configure option to proceed this way.

You may also install Modules through Homebrew on MacOS. It may also ease you life: https://formulae.brew.sh/formula/modules

Regards,
Xavier

**Comment by rakeshphys** [comment]
Thanks [xdelaruelle](https://github.com/xdelaruelle) for your prompt and working reply. I installed it without Tcl. Please tell me if anything is disadvantageous if I am not using Tcl in the modules.

**Comment by xdelaruelle** [comment]
Using the Modules Tcl extension library only make a difference on large collection of modules when used by large number of users concurrently. There is no specific drawback not using this lib on a personnal installation.

**Comment by rakeshphys** [comment]
[xdelaruelle](https://github.com/xdelaruelle),  Thanks again for your insightful and unambiguous explanation!!
