### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by benpietras** [cea-hpc/modules#553]
### Describe the bug

I have the following error on login, which requests to post here. I am using the latest version and have tried 'sudo make uninstall' - which still did not resolve.

### To Reproduce

Login to system (sddm crashes, so I need to login via crtl-alt-f3 to cli).

Location and content of any modulerc or modulefile involved:

None - no modules loaded.

### Expected behavior

No error. Sddm works as it did.

### Error and debugging information

Error: expected boolean value but got ""
"if {!islockable || ![isConfigLocked $option]} {
          # call specific proc to initialize config option if any
          if {$initproc ne {}} {
     ..."
     (procedure "getConf" line 7)
     invoked from within
"getConf home"
        (procedure "module" line 338)
        invoked from within
"cmdModulAutoinit"
    (procedure "module" line 338)
        invoked from within
"{*}$exceccmdlist"
**Please report this issue at https://github.com/cea-hpc/modules/issues**

### Modules version and configuration

command not found

### Additional context

I'm on Archlinux, updated.

**Comment by xdelaruelle** [comment]
Thanks for the report. Could you please describe how Modules has been installed, especially:

* the options set to `configure` installation script
* any change made on the installed `modulecmd.tcl` script file
* environment variable set (`env | grep MODULES`)

**Comment by xdelaruelle** [comment]
The definition of the `home` config option in `modulecmd.tcl` seems to have been altered.

The error you obtain indicates that the *is lockable* property of the `home` option is set to an empty string instead of `0`. An empty string is not a valid value for this property.

Either there were a manual edit of the `modulecmd.tcl` script file or the default value for the `home` option (set through `./configure` script) breaks the option property definitions.

Could you please locate where the `modulecmd.tcl` script is installed and provide here the result of the following command: `grep " home " modulecmd.tcl`.

**Comment by benpietras** [comment]
Hi Xavier,

Thanks for the swift response, it was unexpected.

>  env | grep -i MODULES
is blank.

I ran `git pull` before reinstalling, which should have wiped any changes. Though, I did not make any in any case.

For 
`./configure `
see
https://pastebin.com/cmCi0nxK [ bzGgvihGen ]

`grep "home" modulecmd.tcl`
61:moduleshome = /usr/local/Modules

Don't waste too much time on this, but thank you.

**Comment by xdelaruelle** [comment]
Issue seems to be due to a faulty build of Modules. Cleaning the local installation, fetching again Modules sources then building/installing again should solve this issue.

**Comment by benpietras** [comment]
Thank you for the advice, regretfully not.

**Comment by xdelaruelle** [comment]
@benpietras You can still work together on this if this issue is not solved on yuor side, but I would need the precise list of commands you type to install Modules on your machine and the output of these commands.

**Comment by benpietras** [comment]
Hi Xavier.

Appreciate that. Sorry my level of responsiveness doesn't match your own!

```
git pull
git rev-parse HEAD
# 3b68dee799c0abb30e315f8b69493c58b0f28c59
 ./configure
make clean
make
sudo make install
```

I don't use a greeter, but login via cli. The error message persists after a reboot, login (but doesn't concern me greatly).

Cheers! :-)

**Comment by xdelaruelle** [comment]
Hi @benpietras,

I would suggest to also uninstall and fully clean your local repository before building and installating:

```console
sudo rm -rf /usr/local/Modules
make distclean
./configure
make
sudo make install
```

It should clear potentially unused anymore installed files and clean old generated files in git repository.

Cheers,
Xavier

**Comment by benpietras** [comment]
Hi Xavier,

Thank you for the steps. Regretfully, after them and a reboot, the original issue persists.

It's not a problem for me and time could be spent on better things - happy to close.

Cheers,
Ben
