### ISSUE TITLE
ERROR: Unable to locate a modulefile for 'license/lms@RoundRobin'

### ISSUE THREAD

**Issue by xaisc** [cea-hpc/modules#556]
If the module name contains the “@” , it will fail to load. There was no such problem before 5.0

**Comment by xdelaruelle** [comment]
The `@` is the specifier for version. It is advised to not use anymore this character in modulefile names.

If you cannot change your modulefile name, you may disable the [Advanced module version specifiers](https://modules.readthedocs.io/en/latest/module.html#advanced-module-version-specifiers) mechanism:

```console
$ module config advanced_version_spec 0
```

**Comment by xaisc** [comment]
Thanks, solved
