### ISSUE TITLE
remove-path won't remove paths with a $ in it.

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#8]
We use software that sets an env variable with :
seperated paths to know where to find things.  Instead
of hard coded path we put 
$var1:$var2:$var3:/usr/bin as an example because var1,
var2, var3
get defined by the tool when it starts.

in the module file we use 

prepend-path TOOL_PATH {\$var1:\$var2:\$var3}

This works fine when the module is loaded.
but when the module is unloaded $var1:$var2:$var3
are not removed from TOOL_PATH

I was able to fix this problem by adding one line to
the utility.c

added at line 2414 case '$':

2409    for( i=0, j=0; i&lt;path_len &amp;&amp; j&lt;(len - 1); i++,
j++) {
2410
2411        switch(*path) {
2412            case '.':
2413            case '+':
2414            case '$':
2415        *newpath++ = '\\';        /** devalue '.'
and '+'        **/
2416        j++;
2417        break;
2418        }

Could this fix be applied to future releases?

Thanks
MGH

Reported by: *anonymous

**Comment by asanakoy** [comment]
@xdelaruelle I think the issue should be reopened.
