### ISSUE TITLE
module collection is not fixed

### ISSUE THREAD

**Issue by xdelaruelle** [cea-hpc/modules#89]
The option to create a collection of modules is great, especially when you have a lot of modules with dependencies. I noticed that the module command simplifies the loaded modules, so it doesn't include the version if it is the default or if it is the only available version. If newer versions of the same module get installed after the creation of the collection, the chance is high that the collection changes: when restoring the collection, different modules get loaded, because the default has changed. This is usually not what a user wants. In my view, a collection should be static, so it should always include the full name and version of its modules.

Reported by: donnerssara

**Comment by xdelaruelle** [comment]
@jdonners Environment variable `MODULES_COLLECTION_PIN_VERSION` is added to always record module name + version when saving collection, even if version is the default one. Feature is enabled when `MODULES_COLLECTION_PIN_VERSION` is equal to `1`

**Comment by jdonners** [comment]
@xdelaruelle excellent, thanks for the effort!
